= create guest2.qcow2 using libguestfs-tools 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 23-11-2020

Create a new storage volume, _guest2.qcow2_.
Base it on Red Hat's ready-made KVM image, rhel-baseos-9.0-x86_64-kvm.qcow2. 
This KVM image acts as a base image, or template, from which we can make many more images. 
The original image - the template that we copy - is called a golden image. 

This is the procedure for making a customized copy. 
After this, we can build a new virtual machine using this copy.

* Install utilities on host1. 
* Examine the golden image. 
* Create an empty qcow2 image. 
* Copy the golden image. 
* Customize the new image. 


== a golden image 

Creating a VM using a golden image is quicker than a fresh install. 
Creating many VMs using a golden image does not mean they are all identical - Each new image is edited to make a few configuration changes. 
A new machine may need a unique MAC address, host name and private key. 
A golden image is often a base OS, rather than a complete installation. 
It contains a minimal set of packages, ready to extend for business applications. 

An alternative process is a _fresh install_, where all packages are  installed  from scratch onto an empty volume.
The _guest1_ VM is a fresh install, using a kickstart file to automate the process. 


== install utilities on host1

Before creating this VM, collect content and tools on _host1_.

* xref:virtual-network:libvirt-storage-volume-rhel8-kvm.adoc[]

This process uses the _virt-filesystems_, _virt-resize_ and _virt-customize_ utilities from the _libguestfs-tools_ package.

[source,shell]
----
[root@host1 images]# dnf provides virt-filesystems
Updating Subscription Management repositories.
Last metadata expiration check: 1:06:54 ago on Sun 07 Mar 2021 19:38:32 GMT.
libguestfs-tools-c-1:1.38.4-10.module+el8.0.0+3075+09be6b65.x86_64 : System administration tools for virtual machines
Repo        : rhel-8-for-x86_64-appstream-rpms
Matched from:
Filename    : /usr/bin/virt-filesystems

...(another half dozen results for newer package versions)...

libguestfs-tools-c-1:1.40.2-25.module+el8.3.0+7421+642fe24f.x86_64 : System administration tools for virtual machines
Repo        : rhel-8-for-x86_64-appstream-rpms
Matched from:
Filename    : /usr/bin/virt-filesystems

[root@host1 images]# 
----


== examine the golden image 

Install the _libguestfs-tools_ package. 

[source,shell]
----
sudo dnf install libguestfs-tools
----

View the partitions inside the _rhel-baseos-9.0-x86_64-kvm.qcow2_ file. 


=== use virt-inspector

The _virt-inspector_ utility can display this information. 
The command `virt-inspector rhel-baseos-9.0-x86_64-kvm.qcow2` displays a lot of information about this file. 
In fact, it produces a vast amount of data  - far more than required here.
It's a long XML document, mostly describing installed packages. 

[source,shell]
----
[root@host1 images]# virt-inspector rhel-baseos-9.0-x86_64-kvm.qcow2
<?xml version="1.0"?>
<operatingsystems>
  <operatingsystem>
    <root>/dev/sda3</root>

...(thousands of lines of XML)...

6yrQieoAAAAASUVORK5CYII=</icon>
  </operatingsystem>
</operatingsystems>
[root@host1 images]# 
----

Use XPATH to display the filesystem part of the XML document. 

[source,XML]
----
[root@host1 images]# virt-inspector -a rhel-baseos-9.0-x86_64-kvm.qcow2 | virt-inspector --xpath '//filesystems'
<filesystems>
  <filesystem dev="/dev/sda2">
    <type>vfat</type>
    <uuid>F537-0F4F</uuid>
  </filesystem>
  <filesystem dev="/dev/sda3">
    <type>xfs</type>
    <label>root</label>
    <uuid>fe1e8b67-e41b-44b8-bcfe-e0ec966784ac</uuid>
  </filesystem>
</filesystems>
[root@host1 images]# 
----


=== use virt-filesystems

Use the _virt-filesystems_ command to display a list of partitions. 

[source,shell]
----
[root@host1 ~]# cd /var/lib/libvirt/images/
[root@host1 images]# 
[root@host1 images]# virt-filesystems --parts --add rhel-baseos-9.0-x86_64-kvm.qcow2  
/dev/sda1
/dev/sda2
/dev/sda3
[root@host1 images]# 
----


Take a closer look at those partitions by listing file systems. 
The root file system is _/dev/sda3_, which is nearly 10GiB in size (10629414912 bytes). 

The file is about at tenth the size of this partition. 
A https://en.wikipedia.org/wiki/Qcow[QCOW] file can be compressed to save space. 

[source,shell]
----
[root@host1 images]# virt-filesystems --filesystems --long --add rhel-baseos-9.0-x86_64-kvm.qcow2 
Name       Type        VFS   Label  Size         Parent
/dev/sda2  filesystem  vfat  -      104857600    -
/dev/sda3  filesystem  xfs   root   10629414912  -
[root@host1 images]# 
[root@host1 images]# ls -lh rhel-baseos-9.0-x86_64-kvm.qcow2
-rw-r--r--. 1 qemu qemu 1.3G Nov 23 16:23 rhel-baseos-9.0-x86_64-kvm.qcow2
[root@host1 images]# 
----



== create an empty qcow2 image 

Copy the QCOW image file.  
Don't use this original file for creating a machine. 
It can remain as the backup file. 

First create an empty qcow2 image file. 
The command _virsh vol-create-as_ needs a pool name, the new file name and how big the volume should be. 
If you can't remember your pool name, run _virsh pool-list_ to check.

[source,shell]
----
[root@host1 images]# MY_COPY=guest2.qcow2
[root@host1 images]# SIZE=300G
[root@host1 images]# virsh vol-create-as --format qcow2 images $MY_COPY $SIZE
Vol guest2 created

[root@host1 images]# 
----

This huge 300G volume is compressed down into a tiny file. 
This is called a sparse volume. 
The whole 300 GiB is not allocated now - space is added later, when it is required.

[source,shell]
----
[root@host1 images]# ls -lh $MY_COPY
-rw-------. 1 root root 197K Feb 24 19:40 guest2.qcow2
[root@host1 images]# 
----

It doesn't take long for libvirt to notice the new file and add config to its volume inventory. 

List libvirt's config with this _virsh vol-info_ command. 

[source,shell]
----
[root@host1 images]# virsh vol-info guest2.qcow2 images
Name:           guest2.qcow2
Type:           file
Capacity:       300.00 GiB
Allocation:     200.00 KiB

[root@host1 images]# 
----

List all the volumes with `virsh vol-list images`.
If the new file isn't there, try running `virsh pool-refresh images`.




== copy the golden image

Fill up the new volume using the _virt_resize_ command. 
This doesn't actually resize one file in-place - it reads one file and overwrites a second file. 
Virt_resize expands the volume in the second file while it's copying.

Libvirt does come with a volume copying command, _virsh vol-clone_. It can make a new copy, but it can't change its size. 

[source,shell]
----
[root@host1 images]# MY_COPY=guest2.qcow2
[root@host1 images]# GOLDEN_IMAGE=rhel-baseos-9.0-x86_64-kvm.qcow2 
[root@host1 images]# 
[root@host1 images]# virt-resize --expand /dev/sda3 $GOLDEN_IMAGE $MY_COPY 
[   0.0] Examining rhel-baseos-9.0-x86_64-kvm.qcow2
**********

Summary of changes:

/dev/sda1: This partition will be left alone.

/dev/sda2: This partition will be left alone.

/dev/sda3: This partition will be resized from 9.9G to 299.9G.  The 
filesystem xfs on /dev/sda3 will be expanded using the ‘xfs_growfs’ 
method.

**********
[   5.7] Setting up initial partition table on guest2.qcow2
[  16.6] Copying /dev/sda1
[  16.7] Copying /dev/sda2
[  16.8] Copying /dev/sda3
 100% ⟦▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒⟧ 00:00
[  27.4] Expanding /dev/sda3 using the ‘xfs_growfs’ method

Resize operation completed with no errors.  Before deleting the old disk, 
carefully check that the resized disk boots and works correctly.
[root@host1 images]# 
----

The file is much bigger now, but still a fraction of its defined size. 

[source,shell]
----
[root@host1 images]# ls -lh
total 3.6G
-rw-r--r--. 1 qemu qemu 1.3G Nov 23 16:23 rhel-baseos-9.0-x86_64-kvm.qcow2
-rw-------. 1 root root 2.3G Nov 23 17:16 guest2.qcow2
[root@host1 images]# 
----


== customize the new image  

This image has no root password and no other accounts, so we can't log in.
Change this and a few other things with the ``virt-customize`` command.

Check out that insecure password. 


[source,shell]
----
virt-customize \
  --add            guest2.qcow2  \
  --root-password  password:'x%5ckA-1'  \
  --hostname       guest2.private.example.com  \
  --timezone       'Europe/London'  \
  --selinux-relabel
----

The _virt-customize_ command takes a few seconds. 
It prints an activity log, along with seconds elapsed.

[source,shell]
----
[nick@host ~]$ virt-customize --add guest-images/guest2.qcow2 --root-password password:'x%5ckA-1' --hostname guest2.private.example.com
[   0.0] Examining the guest ...
[   4.6] Setting a random seed
[   4.6] Setting the machine ID in /etc/machine-id
[   4.6] Setting the hostname: guest2.private.example.com
[   4.6] Setting the timezone: Europe/London
[   4.7] Setting passwords
[   5.9] SELinux relabelling
[  18.3] Finishing off
[nick@host ~]$ 
----

This new QCOW image file is ready for use. 


