= create guest2 using the KVM image
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 14-01-2021


Tell libvirt to create the _guest2_ virtual machine. 

Use the ready-made _guest2_ disk image. 
The _guest2_ disk image is a customized copy of the golden image.


== create the libvirt domain 

Create a VM using the ready-made _guest2_ disk image. 

There are two ways of doing this. 

* use XML config 
* use the virt-install command

== use XML config 

A new VM can be created using a command like ``virsh define my-machine.xml``, 
similar to the way a storage pool can be created using ``virsh pool-define storage-pool.xml``.

ut the XML configuration that defines a virtual machine is complicated. 
It's easier to use the ``virt-install`` command to do the hard work. 


== write a virt-install script

This ``virt-install`` command is pretty long, so it's split over many lines to make it a little clearer. 
And the values are parameterized to make them clearer, too.  

There are plenty of commands to run as root here. 

Use the root account. 

[source,shell]
----
[nick@host1 ~]$ sudo su -
[sudo] password for nick: 
[root@host1 ~]# 
----

Use the libvirt directory. 
This directory holds a few scripts used to create the libvirt networks. 

[source,shell]
....
[root@host1 ~]# cd libvirt
[root@host1 libvirt]# 
....

Create a shell script to hold the commands. 

[source,shell]
....
[root@host1 libvirt]# vim vm-guest2-build.sh
[root@host1 libvirt]# 
....

Add content. 
Copy and paste the variables into the file. 

This is a little different from the list for guest1. 
This specifies bridges, not libvirt networks. 
It also specifies image pool rather than path to the image file. 
[source,bash]
----
HOST=guest2
CPUS=1
MEMORY=2048
POOL=images
POOL=images
VOLUME=$HOST.qcow2
OS_VARIANT=rhel9.0
IF1_MAC=52:54:00:01:00:03
IF1_BRIDGE=privbr0
IF2_MAC=52:54:00:02:00:02
IF2_BRIDGE=privbr1
----

Copy and paste the virt-install command into the file. 

This version of the virt-install command is different to the ones used to create _myfirstvm_ and _guest1_. 

This is a little different from the command for guest1. 
* no need for initrd-inject or extra-args. 
* memory instead of ram. 
* the options all have equals and quoted arguments. 

[source,bash]
----
virt-install \
  --name="$HOST" \
  --vcpus=2 \
  --memory=4096 \
  --disk=vol=$POOL/$VOLUME  \
  --os-variant=$OS_VARIANT \
  --network="bridge:${IF1_BRIDGE},mac=$IF1_MAC"   \
  --network="bridge:${IF2_BRIDGE},mac=$IF2_MAC"   \
  --boot="uefi,hd,menu=on" \
  --import   \
  --noautoconsole
----

Here's an explanation of what's going on. 

* --name sets the name that libvirt uses (not the OS hostname). 
* --vcpus, --ram, --disk - The next three options add resources - 1 CPU, 2048MiB memory and a 10GiB disk.
* --boot sets the firmware -   UEFI rather than the older BIOS.
* --os-variant sets up some default values. 
The command ``osinfo-query os`` lists all the choices. 
* --network defines the ethernet interface and which libvirt network it's connected to.
* --import - use the disk to boot the new VM. 
* --noautoconsole - when the virt-install command kicks off the build of the VM, don't hang around and connect to the console. 
That's done as a seperate step. 

Read `man virt-install` for all the options (and there are a truck-load). 
The virt-install tool has a lot of default settings, so there is no need to specify options like `--connect qemu:///system` for the hypervisor and `--graphics spice` for a graphical desktop. 

Run the script. 

[source,shell]
----
[root@host2 libvirt]# chmod 754 vm-guest2-build.sh 
[root@host2 libvirt]# 
[root@host2 libvirt]# ./vm-guest2-build.sh 

Starting install...
Domain creation completed.
[root@host2 libvirt]# 
----

libvirt adds XML configuration 

Now there is a VM.

[source,shell]
----
[root@host1 ~]# virsh list --all
 Id   Name     State
------------------------
 1    guest1   running
 6    guest2   running

[root@host1 ~]# 
----




== delete the VM

if something goes wrong, clear your work and start again.
Copy the guest1 delete script, edit the new copy, and change the name from _guest1_ to _guest2_.

* xref:guest1-delete.adoc[]

