= create the guest2 VM 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 28-11-2020

Use a *fresh install* process (AKA clean install, or install from scratch). 
Build a machine and install the OS. 
Use a kickstart file to automate the process. 

This example creates a machine called _guest2_ and installs RHEL 8. 

* xref:guest1-virt-install.adoc[]


The guest2 machine has two interfaces, not one. 
One interface leads to the home network and onto the Internet, and the other leads to the private network. 

.guest2 has one interface 
....
  |
+-+-------------------------------------+
| enp1s0, guest1.lab.example.com        |
|                                       |
| enp2s0, guest1.private.example.com    |
+-+-------------------------------------+
  |
  | privbr0, the private network 
  | 192.168.152.0/24
  |
+-+-------------------------------------+
| enp1s0, guest2.lab.example.com        |
|                                       |
|                                       |
+---------------------------------------+
....

A command called _virt-install_ does the work. Two things are required before the _virt-install_ command is run. 

* RHEL 8 install ISO. This file is in libvirt's _images_ pool. 
* kickstart file. This is /root/libvirt/guest2.ks.



== the virt-install command 

The command to build a new machine is long, with lots of options. 
In this example the options are split over several lines, and some values are moved to variables, to make it a little easier to see what's going on. 

[source,shell]
....
HOST=guest2
NEW_DISK=/var/lib/libvirt/images/$HOST.qcow2
INSTALL_ISO=/var/lib/libvirt/images/rhel-8.3-x86_64-dvd.iso
KICKSTART_CONFIG=/root/libvirt/$HOST.ks
IF1_MAC=52:54:00:00:00:01
virt-install \
  --name="$HOST" \
  --vcpus=2 \
  --ram=4096 \
  --disk path=$NEW_DISK,size=50 \
  --os-variant rhel8.3 \
  --network network=privbr0,mac=$IF1_MAC   \
  --boot uefi,hd,menu=on \
  --location $INSTALL_ISO \
  --initrd-inject $KICKSTART_CONFIG \
  --extra-args "inst.ks=file:/$HOST.ks console=tty0 console=ttyS0,115200" \
  --noautoconsole
....


== create a VM 

Copy and paste the variables and virt-install command into a terminal. 

[source,shell]
----
[root@host1 libvirt]# HOST=guest2
...
[root@host1 libvirt]# virt-install \
>   --name="$HOST" \
...
>   --noautoconsole

Starting install...
Retrieving file vmlinuz...                        | 8.5 MB  00:00:00     
Retrieving file initrd.img...                     |  63 MB  00:00:00     
Allocating 'guest2.qcow2'                         |  50 GB  00:00:00     
Domain installation still in progress. You can reconnect to 
the console to complete the installation process.
[root@host1 libvirt]# 
----


=== delete the VM 

If something goes wrong, remove your additions. 

* Pull the plug on the VM with _virsh destroy_. 
* Remove libvirt's new VM config with _virsh undefine_. 
* Remove the new storage volume file with _virsh vol-delete_. For the impatient, you can avoid typing another command by adding another option to virsh undefine: _virsh undefine --nvram --remove-all-storage $HOST_. 


[source,shell]
....
[root@host1 libvirt]# virsh destroy $HOST
Domain guest2 destroyed

[root@host1 libvirt]# 
[root@host1 libvirt]# virsh undefine --nvram $HOST 
Domain guest2 has been undefined

[root@host1 libvirt]# 
[root@host1 libvirt]#  virsh vol-delete $HOST.qcow2 --pool images
Vol guest2.qcow2 deleted

[root@host1 libvirt]# 
....


== watch the install 

Use the console to watch progress. 

Hundreds of lines scroll by for two minutes. 

[source,shell]
....
[root@host1 libvirt]# virsh console $HOST
Connected to domain guest2
Escape character is ^]
[    3.630006] Freeing initrd memory: 64952K
[    3.630623] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    3.631678] software IO TLB: mapped [mem 0x6f0e2000-0x730e2000] (64MB)
...
....

After a few seconds, the anaconda install starts. 

[source,shell]
....
...
Starting installer, one moment...
anaconda 29.19.2.17-1.el8 for Red Hat Enterprise Linux 8.2 started.
 * installation log files are stored in /tmp during the installation
 * shell is available on TTY2
 * if the graphical installation interface fails to start, try again with the
   inst.text bootoption to start text installation
 * when reporting a bug add logs from /tmp as separate text/plain attachments
18:48:20 Not asking for VNC because of an automated install
18:48:20 Not asking for VNC because text mode was explicitly asked for in kickstart
Starting automated install...
Generating updated storage configuration
Checking storage configuration...

================================================================================

================================================================================
Installation

1) [x] Language settings                 2) [x] Time settings
       (English (United Kingdom))               (Europe/London timezone)
3) [x] Installation source               4) [x] Software selection
       (Local media)                            (Custom software selected)
5) [x] Installation Destination          6) [x] Kdump
       (Custom partitioning selected)           (Kdump is enabled)
7) [x] Network configuration
       (Wired (enp1s0) connected)

================================================================================
...
....


After that, packages install. 

[source,shell]
....
...
Installing iwl105-firmware.noarch (415/417)
Installing iwl1000-firmware.noarch (416/417)
Installing iwl100-firmware.noarch (417/417)
Performing post-installation setup tasks
Configuring filesystem.x86_64
Configuring crypto-policies.noarch
Configuring kernel-core.x86_64
...
....

Finally the system stops. 
The _reboot_ command in the kickstart file is ignored. 
The OS expects the machine to reboot, but libvirt and qemu stop this happening.
The _qemu-kvm_ process runs with about 60 options (see for yourself with _ps -fwwwC qemu-kvm_), and one of these is  _-no-reboot_ . 
To find out more, run _man virt-install_ and read about the _--noautoconsole_ option. 

[source,shell]
....
...
[  OK  ] Stopped Remount Root and Kernel File Systems.
[  OK  ] Reached target Shutdown.
[  OK  ] Reached target Final Step.
         Starting Reboot...
dracut Warning: Killing all remaining processes
Rebooting.
[  201.228326] reboot: Restarting system

[root@host1 libvirt]# 
....



== start the new machine 

After install completes, the machine is off. 


[source,shell]
....
[root@host1 libvirt]# virsh list --all
 Id   Name         State
-----------------------------
 1    guest2     shut off

[root@host1 libvirt]# 
....

Turn it on. 

[source,shell]
....
[root@host1 libvirt]# virsh start $HOST
Domain guest2 started

[root@host1 libvirt]# 
....

Connect to the console again. 
This time the login prompt appears. 

Try logging in. 

[source,shell]
....
[root@host1 libvirt]# virsh console $HOST
Connected to domain guest2
Escape character is ^]

Red Hat Enterprise Linux 8.2 (Ootpa)
Kernel 4.18.0-193.el8.x86_64 on an x86_64

guest2 login: root
Password: 
[root@guest2 ~]# 
....

Disconnect from the console with the control and right square bracket keys 
kbd:[Ctrl + ++]++ ] 

[source,shell]
....
[root@guest2 ~]# ^]
[root@host1 libvirt]# 
....

== stop the new machine 

The _virsh shutdown_ command tells the OS to power off. 
It's a graceful shutdown, unlike _virsh destroy_ which is like pulling the plug.

[source,shell]
....
[root@host1 libvirt]# virsh shutdown $HOST
Domain guest2 is being shutdown

[root@host1 libvirt]# 
....
