= set guest2's IP address using dnsmasq 
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 11-01-2021



set a VM's domain name and IP address using dnsmasq

.VMs use dnsmasq services 
....
.-------------------------------------.  
|                                     |
|  private1                           |
|                                     |
|   +----------+        +----------+  |
|   |          |        |          |  |
|   |  guest2  | DHCP   | dnsmasq  |  |
|   |          +------->|          |  |
|   |          |        |          |  |
|   |          | DNS    |          |  |
|   |          +------->|          |  |
|   +----------+        +----------+  |
.-------------------------------------.  
....


Set up a name and address for the new VM _guest2_. Use dnsmasq to fix the IP address _192.168.152.100_ and the 
https://en.wikipedia.org/wiki/Fully_qualified_domain_name[FQDN (Fully Qualified Domain Name)] _guest2.private.example.com_.





== assign a name and address

Add an XML tag to the network's configuration.

This dnsmasq config file can't be edited directly because it's created by libvirt - any changes would be overwritten. 
Instead, use ``virsh`` commands to add config. 




=== add the FQDN and IPv4 address to libvirt's config

It's easier to add the host name and address. 
Use _virsh net-update_, which doesn't require a network restart. 
The command contains the line of XML to be added. 
The name in the _name_ attribute matches the hostname set by the ``virt-customize`` command.
The ``--live`` and ``--config`` options make sure both the current configuration and the stored config are updated.

[source,shell]
....
sudo virsh net-update private0 add ip-dhcp-host \
    "<host  mac='52:54:00:00:00:01' name='guest2.private.example.com' ip='192.168.152.100' />" \
    --live \
    --config
....

Add the host line. 

[source,shell]
....
[nick@host1 ~]$ sudo virsh net-update private0 add ip-dhcp-host "<host mac='52:54:00:00:00:01' name='guest2.private.example.com' ip='192.168.152.100' />" --live --config
Updated network private0 persistent config and live state
[nick@host1 ~]$ 
....

You can remove this line by replacing ``add`` with ``delete``. 

Check your work with the command `sudo virsh net-dumpxml private0`. 
The config XML now looks like this. 

[source,xml]
....
<network>
  <name>private0</name>
  <uuid>88c35d22-05d7-4e1f-ae02-d1906f7a0bbc</uuid>
  <bridge name='private0' stp='on' delay='0'/>
  <mac address='52:54:00:23:0f:f9'/>
  <domain name='private.example.com' localOnly='yes'/>
  <ip address='192.168.152.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.152.2' end='192.168.152.254'/>
      <host mac='52:54:00:00:00:03' name='guest2.private.example.com' ip='192.168.152.100'/>
    </dhcp>
  </ip>
  <ip family='ipv6' address='2001:db8:ca2:3::1' prefix='64'>
  </ip>
</network>
....


=== add the FQDN and IPv4 address to the host 

Machine _host1_ doesn't use dnsmasq. 
The host machine has no idea what the name and address of this new VM are. 

Add a line to /etc/hosts. 

[source,shell]
....
[nick@host1 ~]$ sudo bash -c 'echo "192.168.152.100 guest2 guest2.private.example.com" >> /etc/hosts'
[nick@host1 ~]$ 
....


== check your work 

=== watch the activity log

When the _guest2_ VM starts, it uses DHCP to obtain an IP address.
The guest VM starts by broadcasting a 'looking for DHCP server' message and gets an answer from dnsmasq on the host machine. 
You can see the conversation taking place using ``journalctl``.

[source,shell]
....
[nick@host1 ~]$ journalctl -f
...
Feb 24 20:47:49 host1.lab.example.com dnsmasq-dhcp[30277]: DHCPREQUEST(private0) 192.168.152.100 52:54:00:00:00:03
Feb 24 20:47:49 host1.lab.example.com dnsmasq-dhcp[30277]: DHCPACK(private0) 192.168.152.100 52:54:00:00:00:03 guest2
Feb 24 20:47:51 host1.lab.example.com dnsmasq-dhcp[30277]: RTR-SOLICIT(private0)
Feb 24 20:47:51 host1.lab.example.com dnsmasq-dhcp[30277]: RTR-ADVERT(private0) 2001:db8:ca2:3::
....


=== stop and start the VM 

Check whether guest2 is running with ``virsh dominfo guest2``.
Stop the guest VM with ``virsh shutdown guest2``. 
Start with ``virsh start guest2``.



=== resolve the name 

dnsmasq only listens to the libvirt network interface. 

[source,shell]
....
[nick@host1 libvirt]# host guest2.private.example.com 192.168.152.1
Using domain server:
Name: 192.168.152.1
Address: 192.168.152.1#53
Aliases: 

guest2.private.example.com has address 192.168.152.100
[nick@host1 libvirt]# 
....

Can the host find it?
Try with the short name. 

[source,shell]
....
[nick@host1 ~]$ ping -c1 guest2
PING guest2 (192.168.152.100) 56(84) bytes of data.
64 bytes from guest2 (192.168.152.100): icmp_seq=1 ttl=64 time=0.226 ms

--- guest2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.226/0.226/0.226/0.000 ms
[nick@host1 ~]$ 
....


=== connect using SSH

The only account on this machine belongs to root. 
Root's SSH access should be blocked to increase security, but it's currently available. 
 
[source,shell]
....
[nick@host1 ~]$ ssh root@guest2
The authenticity of host 'guest2 (192.168.152.100)' can't be established.
ECDSA key fingerprint is SHA256:p3XZSmOmc2+pWAe4hhnvaJtTUoD6NM0epj6AhW1W2oI.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'guest2,192.168.152.100' (ECDSA) to the list of known hosts.
root@guest2's password: 
Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed Feb 24 20:55:01 2021 from 192.168.152.1
[root@guest2 ~]# 
....

Disconnect. 

[source,shell]
----
[root@guest2 ~]# exit
logout
Connection to guest2 closed.
[nick@host1 ~]$ 
----

