= set up the guest2 OS 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 24-02-2021


Carry out some first-run sysadmin on the new machine. 

Use the console to connect. 


== add another account 

Check for any home directories. 
None! 

[source,shell]
....
[root@guest2 ~]# ls /home/
[root@guest2 ~]# 
....

Add user _nick_. Run these commands.

[source,shell]
....
NAME=nick
useradd $NAME
usermod -a -G wheel $NAME
echo 'Password;1' | passwd --stdin $NAME
....


== connect with SSH

Disconnect from the console. 

Login with the new account. 

[source,shell]
....
[nick@host2 ~]$ ssh nick@192.168.152.114
nick@192.168.152.114's password: 
Activate the web console with: systemctl enable --now cockpit.socket

Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last failed login: Mon Aug  1 12:38:12 BST 2022 from 192.168.152.1 on ssh:notty
There were 3 failed login attempts since the last successful login.
[nick@guest2 ~]$ 
....

Logout

[source,shell]
....
[nick@guest2 ~]$ exit
logout
Connection to 192.168.152.114 closed.
[nick@host2 ~]$ 
....


== use key-based login 

Copy your public key from host1 for easier login. 


Generate a private key and public key. 

[source,shell]
....
[nick@host2 ~]$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/nick/.ssh/id_rsa): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /home/nick/.ssh/id_rsa
Your public key has been saved in /home/nick/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:aNCgs3UYfDOEOHuo4xb4tWa6sJaJ1VEyXwJZBbkeVo4 nick@host2.lab.example.com
The key's randomart image is:
+---[RSA 3072]----+
|   o+*++.        |
|  o.*=B o        |
|  o++*oX         |
|  o+ooE..        |
|...o +o.S        |
|+.. o..          |
|+++. .           |
|.O. +            |
|+ o=             |
+----[SHA256]-----+
[nick@host2 ~]$ 
....

Copy the public key.

[source,shell]
....
[nick@host2 ~]$ ssh-copy-id nick@192.168.152.114
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/nick/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
nick@192.168.152.114's password: 

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'nick@192.168.152.114'"
and check to make sure that only the key(s) you wanted were added.

[nick@host2 ~]$ 
....

SSH from your workstation to the machine. 

[source,shell]
....
[nick@host2 ~]$ ssh nick@192.168.152.114
Activate the web console with: systemctl enable --now cockpit.socket

Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Mon Aug  1 12:52:31 2022 from 192.168.152.1
[nick@guest2 ~]$ 
....



== add swap 

Add swap.

[source,shell]
....
# Add 4G swap
# 1024 K in M * 1024 M in G * 4 G = 4194304
SWAPFILE=/var/cache/swap
dd if=/dev/zero of=/var/cache/swap bs=1024 count=4194304
chmod 0600 $SWAPFILE
# Setup the swap file with the command:
mkswap $SWAPFILE
# To enable the swap file immediately but not automatically at boot time:
swapon $SWAPFILE
# To enable it at boot time, edit /etc/fstab to include the following entry:
echo "$SWAPFILE swap swap defaults 0 0" >> /etc/fstab
....


== harden security  

Anyone on the home network can get at this machine, so security is an issue. 

Disable root login. 

* Use the root account. 
* Edit /etc/ssh/sshd_config.
* Change PermitRootLogin to no.
* Restart the service with _systemctl reload sshd.service_


== proxy 


??? squid? 

Use squid on guest2 

[source,shell]
....
[root@guest2 ~]# vi /etc/profile.d/proxy.sh
export http_proxy=192.168.152.11:3128
export https_proxy=192.168.152.11:3128
....


== DNS  

[source,shell]
....
nmcli con mod System\ eth0 ipv4.dns 192.168.152.11
nmcli con mod System\ eth0 ipv4.ignore-auto-dns yes
....


== network routing 

!!! not useful
Not sure what the point of this is. 

[source,shell]
....
[root@guest2 ~]# ip route list
192.168.152.0/24 dev eth0 proto kernel scope link src 192.168.152.100 metric 100 
[root@guest2 ~]# 
[root@guest2 ~]# ip route add default via 192.168.152.11 
[root@guest2 ~]# 
[root@guest2 ~]# ip route list
default via 192.168.152.11 dev eth0 
192.168.152.0/24 dev eth0 proto kernel scope link src 192.168.152.100 metric 100 
[root@guest2 ~]# 
....

IP forwarding on guest2 

[source,shell]
....
[root@guest2 ~]# cat /proc/sys/net/ipv4/ip_forward
0
[root@guest2 ~]# 
[root@guest2 ~]# sysctl net.ipv4.ip_forward=1
net.ipv4.ip_forward = 1
[root@guest2 ~]# 
....

Check 

[source,shell]
....
[root@guest2 ~]# ping -c1 192.168.1.217 # enp1s0 on guest2
PING 192.168.1.217 (192.168.1.217) 56(84) bytes of data.
64 bytes from 192.168.1.217: icmp_seq=1 ttl=64 time=0.372 ms

--- 192.168.1.217 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.372/0.372/0.372/0.000 ms
[root@guest2 ~]# 
[root@guest2 ~]# ping -c1 192.168.122.1 # pubbr0 bridge on host1
PING 192.168.122.1 (192.168.122.1) 56(84) bytes of data.

--- 192.168.122.1 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

[root@guest2 ~]# 
....

delete 

[source,shell]
....
ip route delete default via 192.168.152.11
....




== subscribe 

Use RHSM (Red Hat Subscription Manager) to entitle this machine to Red Hat's services.

* xref:install-subscribe:host1-rhsm-entitlement.adoc[]

[source,shell]
....
subscription-manager status
subscription-manager register  --username <username>  --password <password>
subscription-manager attach  --pool=1234567890abcdef1234567890abcdef
....



== update packages 

The kickstart process registered this machine with Red Hat and entitled it to receive updates. 

[source,shell]
....
[root@guest2 ~]# dnf -y update
...
[root@guest2 ~]# systemctl reboot
Connection to guest2 closed by remote host.
Connection to guest2 closed.
workstation:~ nick$ 
....

Wait a minute and log in again. 

