= create guest3 running RHEL 8
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 11-01-2021

Build guest3. 
This is the first machine running RHEL 8.

.guest1 and guest2 network interfaces
----
            + pubbr0                                + privbr0                              + privbr1
            |                                       |                                      |
            |                                       |     +--------------------------+     | 
   Internet |     +--------------------------+      |     |  guest2.lab.example.com  |     |     +--------------------------+
  <---------+     | guest1.lab.example.com   |      +-----+ eth0                eth1 +-----+     |  guest3.lab.example.com  | 
            +-----+ enp1s0            enp2s0 +------+     |                          |     +-----+ enp1s0            enp2s0 |
            |     |                          |      |     +--------------------------+     |     |                          |
            |     +--------------------------+      |                                      |     +--------------------------+ 
----

This process is a compressed version of the process that built guest1. 
Three files are used. 

* vm-guest3-rhel8.ks - a kickstart file for automated install
* vm-guest3-build.sh - create the new VM
* vm-guest3-delete.sh - delete the VM

== use the libvirt directory 

Use the root account. 

[source,shell]
....
[nick@host1 ~]$ sudo su -
[sudo] password for nick: 
[root@host1 ~]# 
[root@host1 ~]# cd libvirt
[root@host1 libvirt]#
....

== create vm-guest3-rhel8.ks

This is the kickstart file for automated install.

[source,shell]
....
[root@host1 libvirt]# vi vm-guest3-rhel8.ks 
....

Add content. 

[source,shell]
....
# kickstart file
# https://github.com/nickhardiman/summit_OD1226/blob/main/kickstart_files/kickstart-rhel8-1.ks
# Kickstart user guide is here.
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html-single/performing_an_advanced_rhel_installation/index#kickstart_references
# This tool creates a kickstart file. 
# https://access.redhat.com/labs/kickstartconfig/

# command section
# -----------------------------------

# install
# don't use graphical install
text
# look for an installer DVD
cdrom
# Run the Setup Agent on first boot
firstboot --enable

# l10n (localization)
lang en_GB.UTF-8
timezone Europe/London --isUtc
keyboard uk

# network
network  --bootproto=dhcp --device=enp1s0 --ipv6=auto --activate
network  --hostname=guest3.lab.example.com

# licences and repos
# And have a look at the "subscription" section, in the post section below. 
repo --name="AppStream" --baseurl=file:///run/install/repo/AppStream
eula --agreed

# accounts
# The command "openssl passwd  -6 --salt SQXqGsYna84.3SL5" turns "Password;1" into this. 
rootpw --iscrypted $6$SQXqGsYna84.3SL5$gJw6v23ZZ7WEITfBoZmyNDsIKeoqhS2Mwfk.KpCRloK7EfxlhL3MAlTCO33fr7QRfoG.GvBH1seWtQqz5v82q1
user --groups=wheel --name=nick --password=$6$G3GIlnUH.JqcrAQl$I.q7gGoT37tcNnrGiHkeUTBtr8AAuoM/yy3P3FuEpJaSun6clgR8GlvKIbqOTgqNe.fIBV6xZOPiWvsduhXeC/ --iscrypted --gecos="nick"

# storage 
ignoredisk --only-use=vda
# Partition clearing information
clearpart --all --initlabel
part /boot/efi --fstype="efi"   --ondisk=vda --size=600 --fsoptions="umask=0077,shortname=winnt"
part /boot     --fstype="xfs"   --ondisk=vda --size=1024
part pv.03    --fstype="lvmpv"  --ondisk=vda --size=28672
volgroup rhel pv.03
# 13GiB * 1024 = 13312MiB
logvol /     --fstype="xfs"  --size=13312  --name=root --vgname=rhel
logvol /var  --fstype="xfs"  --size=13312  --name=var  --vgname=rhel
logvol swap  --fstype="swap" --size=256    --name=swap --vgname=rhel


# applications and services 
# Do not configure the X Window System
skipx
services --enabled="chronyd"
selinux --enforcing
firewall --enabled --http --ssh

# done
# skip anaconda's prompt "Installation complete. Press ENTER to quit:"
reboot

# extra sections 
# -----------------------------------

# package selection section
# user guide: 
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html/managing_software_with_yum/index
%packages
# This is an environment group of packages.
# View the full list of groups to choose from by running this command.
#   dnf group list --hidden
@^minimal-environment
# single package
kexec-tools
%end

# add-on section
# kdump kernel crash dump mechanism
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html-single/performing_an_advanced_rhel_installation/index#addon-com_redhat_kdump_kickstart-commands-for-addons-supplied-with-the-rhel-installation-program
%addon com_redhat_kdump --enable --reserve-mb='auto'
%end
#

# There is no point adding subscription-manager commands here.
# This machine is on a private network and can't contact 
# subscription.rhsm.redhat.com
....

Save your work. 


== create vm-guest3-build.sh

Create a shell script to hold the commands. 

[source,shell]
....
[root@host1 libvirt]# vim vm-guest3-build.sh
[root@host1 libvirt]# 
....

Add content. 
Copy and paste the variables and virt-install command into the file. 

The ISO version and the os-variant option don't match. 
Sometimes software takes a while to catch up with the latest release. 

[source,shell]
....
HOST=guest3
NEW_DISK=/var/lib/libvirt/images/$HOST.qcow2
INSTALL_ISO=/var/lib/libvirt/images/rhel-8.6-x86_64-dvd.iso
KICKSTART_CONFIG=vm-$HOST-rhel8.ks
IF1_MAC=52:54:00:03:00:03
IF1_NET=private1
virt-install \
  --name="$HOST" \
  --vcpus=2 \
  --ram=4096 \
  --disk path=$NEW_DISK,size=30 \
  --os-variant rhel8.5 \
  --network network=$IF1_NET,mac=$IF1_MAC   \
  --boot uefi,hd,menu=on \
  --location $INSTALL_ISO \
  --initrd-inject /root/libvirt/$KICKSTART_CONFIG \
  --extra-args "inst.ks=file:/$KICKSTART_CONFIG console=tty0 console=ttyS0,115200" \
  --noautoconsole
....

Set the execute flag. 

[source,shell]
----
[root@host2 libvirt]# chmod 754 vm-guest3-build.sh 
----


== create vm-guest3-delete.sh

Create a shell script to hold the commands. 

[source,shell]
....
[root@host1 libvirt]# vim vm-guest3-delete.sh
[root@host1 libvirt]# 
....

Add content. 

[source,shell]
....
HOST=guest3
virsh destroy $HOST
virsh undefine --nvram $HOST 
virsh vol-delete $HOST.qcow2 --pool images
....

Set the execute flag. 

[source,shell]
----
[root@host2 libvirt]# chmod 754 vm-guest3-delete.sh 
----


== build the VM

Run the script. 

[source,shell]
----
[root@host2 libvirt]# ./vm-guest3-build.sh 

Starting install...
Retrieving file vmlinuz...                                                                 |  10 MB  00:00:00     
Retrieving file initrd.img...                                                              |  80 MB  00:00:00     
Allocating 'guest3.qcow2'                                                                  |  30 GB  00:00:00     

Domain is still running. Installation may be in progress.
You can reconnect to the console to complete the installation process.
[root@host2 libvirt]# 
----

Watch the install. 

[source,shell]
----
virsh console guest3
----

The console session ends when the VM shuts down. 

Restart the new machine and find the IP address. 

Connect using SSH. 
This throws a warning,  "bad signature for RSA key". 
This isn't a show-stopping error, despite the wording. 
See https://access.redhat.com/discussions/6960881.

[source,shell]
----
[root@host2 libvirt]# virsh start guest3
Domain 'guest3' started

[root@host2 libvirt]# 
[root@host2 libvirt]# sudo virsh net-dhcp-leases private1
 Expiry Time           MAC address         Protocol   IP address           Hostname   Client ID or DUID
------------------------------------------------------------------------------------------------------------
 2022-08-01 15:35:28   52:54:00:03:00:03   ipv4       192.168.162.158/24   -          01:52:54:00:03:00:03

[root@host2 libvirt]# 
[root@host2 libvirt]# ssh nick@192.168.162.158
The authenticity of host '192.168.162.158 (192.168.162.158)' can't be established.
ED25519 key fingerprint is SHA256:wNpLEKtF1Sjy5SiQv0nGG7LOhqoK/8CghtOh3L3YmMc.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.162.158' (ED25519) to the list of known hosts.
nick@192.168.162.158's password: 
client_global_hostkeys_private_confirm: server gave bad signature for RSA key 0: error in libcrypto
[nick@guest3 ~]$ 
----
