= clone guest2's image to create guest4 
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 07-03-2021


.guest1 and guest2 network interfaces
----
            + pubbr0                                + privbr0                              + privbr1
            |                                       |                                      |
            |     +--------------------------+      |     +--------------------------+     | 
   Internet |     |  guest1.lab.example.com  |      |     |  guest2.lab.example.com  |     |
  <---------+     |                          |      +-----+ enp1s0            enp2s0 +-----+ 
            +-----+ enp1s0            enp2s0 +------+     |                          |     |
            |     |                          |      |     |                          |     |
            |     +--------------------------+      |     +--------------------------+     |
                                                    |     +--------------------------+     |
                                                    |     |  guest4.lab.example.com  |     |
                                                    +-----+ enp1s0            enp2s0 +-----+ 
                                                    |     |                          |     |
                                                    |     |                          |     |
                                                          +--------------------------+ 

----


Create another VM like guest2 using virt-clone, virt-sysprep and virt-customize. 
This is almost an exact copy of machine layout and storage volume. 

Instead of installing from scratch, the way _guest1_ was created, base it on guest2.

Start by creating a new image file that holds the storage volume.
Feel free to say _disk_, _storage volume_ or _image file_. 

* _guest4_ thinks it is a disk. 
* _host1_ thinks it is an image file. 
* _Libvirt_ thinks it is a file containing a storage volume. 

The _guest2.qcow2_ storage volume has all the files guest4 needs.
Make a copy of guest2's storage and customize it a little.
This takes less time and effort than installing the OS from scratch.

If guest2 is still running, virt-clone refuses to work, saying _Domain with devices to clone must be paused or shutoff_.

Use the root account. 

Shutdown guest2. 

[source,shell]
----
[root@host1 ~]# virsh shutdown guest2
Domain guest2 is being shutdown

[root@host1 ~]# 
[root@host1 ~]# virsh list --all
 Id   Name     State
-------------------------
 1    guest1   running
 -    guest2   shut off

[root@host1 ~]# 
----


Copy the guest2 VM.

[source,shell]
----
[root@host1 ~]# virt-clone --original rhel-baseos-9.0-x86_64-kvm.qcow2 --name guest4 --file /var/lib/libvirt/images/guest4.qcow2
Allocating 'guest4.qcow2'                                          |  30 GB  00:00:03     
Allocating 'guest4_VARS.fd'                                        | 528 kB  00:00:00     

Clone 'guest4' created successfully.
[root@host1 ~]# 
----

The new _guest4.qcow2_ file needs work. 
For instance, it contains the wrong hostname. 

== view the hostname with virt-inspector

The _virt-inspector_ utility can display the hostname. 
In fact, it produces a vast amount of data about all kinds of operating system things. 
The output is an XML document - it's thousands of lines long, and mostly describes installed packages. 
The _virt-customize_ utility is included in the _guestfs-tools_ package.

Use XPATH to display the hostname part of the XML document. 

[source,shell]
----
[root@host1 ~]# virt-inspector -a /var/lib/libvirt/images/guest4.qcow2 | virt-inspector --xpath '//hostname'
<hostname>guest2.private.example.com</hostname>
[root@host1 ~]# 
----



== reset the VM with virt-sysprep

The new VM contains unwanted data.
It has guest2's host keys, network settings. log entries and so on. 
The virt-sysprep command can clean up the new machine by removing these. 

[source,shell]
----
[root@host1 ~]# virt-sysprep --domain guest4
[   0.0] Examining the guest ...
[   2.0] Performing "abrt-data" ...
[   2.0] Performing "backup-files" ...

...(about 40 actions)...

[   2.7] Setting a random seed
[   2.7] Setting the machine ID in /etc/machine-id
[   2.8] Performing "lvm-uuids" ...
[root@host1 ~]# 
----


== change the hostname with virt-customize 

Change the hostname. 

[source,shell]
----
virt-customize \
  --add       /var/lib/libvirt/images/guest4.qcow2  \
  --hostname  guest4.private.example.com \
  --selinux-relabel
----

Run the command. 

[source,shell]
----
[root@host1 ~]# virt-customize \
>   --add       /var/lib/libvirt/images/guest4.qcow2  \
>   --hostname  guest4.private.example.com \
>   --selinux-relabel
[   0.0] Examining the guest ...
[   4.2] Setting a random seed
[   4.2] Setting the hostname: guest4.private.example.com
[   4.2] SELinux relabelling
[  11.9] Finishing off
[root@host1 ~]# 
----



== view libvirt's list of volumes 

Libvirt keeps a list of volumes in its storage pools. 
It should already know about the new file guest4.qcow2. 

List all the volumes in the _images_ storage pool with the `virsh vol-list images` command.

If the new file is not there, tell libvirt to update its list with `virsh pool-refresh images`. 
For instance, guest4.qcow2 is missing from this list. 

[source,shell]
----
[root@host1 ~]# virsh vol-list images
 Name                               Path
----------------------------------------------------------------------------------------------
 guest1.qcow2                       /var/lib/libvirt/images/guest1.qcow2
 guest2.qcow2                       /var/lib/libvirt/images/guest2.qcow2
 rhel-8.3-x86_64-dvd.iso            /var/lib/libvirt/images/rhel-8.3-x86_64-dvd.iso
...
[root@host1 ~]# 
----

Refresh.

[source,shell]
----
[root@host1 libvirt]# virsh pool-refresh images
Pool images refreshed

[root@host1 libvirt]# virsh vol-list images
 Name                               Path
----------------------------------------------------------------------------------------------
 guest1.qcow2                       /var/lib/libvirt/images/guest1.qcow2
 guest2.qcow2                       /var/lib/libvirt/images/guest2.qcow2
 guest4.qcow2                       /var/lib/libvirt/images/guest4.qcow2
 rhel-8.3-x86_64-dvd.iso            /var/lib/libvirt/images/rhel-8.3-x86_64-dvd.iso
...
----


Get more details with the _virsh vol-info_ command. 

[source,shell]
----
[root@host1 libvirt]# virsh vol-info guest4.qcow2 images
Name:           guest4.qcow2
Type:           file
Capacity:       30.00 GiB
Allocation:     2.53 GiB

[root@host1 libvirt]# 
----


== delete the new VM

If something goes wrong, remove the new machine and image file with this command. 

[source,shell]
----
virsh undefine --nvram --remove-all-storage guest4
----


== start both machines 

[source,shell]
----
virsh start guest2
virsh start guest4
----
