= create a kickstart file for guest1 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 11-01-2021

Start the process of building guest1. 
Three files are used. 

* vm-guest1-build.sh - create the new VM
* vm-guest1-delete.sh - delete the VM
* vm-guest1-rhel9.ks - a kickstart file for automated install

Create a kickstart file for the virtual machine guest1.

This machine is built using a *fresh install* build process, as opposed to a golden image build process. 
Build a machine and install the OS. 
Use a kickstart file to automate the process. 


== a fresh install 

A fresh install (AKA clean install, or install from scratch) asks the user what is required, then builds the system to match. 
The kickstart file provides answers to what is required, so there is no need to ask the user anything. 

The resulting machine will contain some old packages. 
It won't be up-to-date until a _dnf update_ is run.
Packages are copied from the installer ISO, and these don't get updates; they aren't re-made every time a package is updated.  The older an ISO is, the more packages need updating. 

Many types of machine may be installed using many kickstart files. 
A library of these kickstart files takes up less space than a library of golden image files. 

An alternative process is to use an existing machine's storage file as a _golden image_, and make a copy. 
Another alternative is to install over the network. 


== use the libvirt directory 

Create a new https://en.wikipedia.org/wiki/Kickstart_(Linux)[kickstart] file.
This file will contain all the configuration instructions for the kickstart program to follow. 

The naming policy for this file is "__machine_name__.ks". 
The storage policy is to stick everything in one directory off root's home. 
This kickstart config file goes in the _libvirt_ directory, along with bridge scripts and libvirt XML definitions. 

Use the root account. 

[source,shell]
....
[nick@host1 ~]$ sudo su -
[sudo] password for nick: 
[root@host1 ~]# 
....

Use the libvirt directory to hold new scripts and config files. 
This directory already holds a few network scripts.

[source,shell]
....
[root@host1 ~]# cd libvirt
[root@host1 libvirt]#
[root@host2 libvirt]# ls
libvirt-service-enable.sh  libvirt-socket-enable.sh
libvirt-socket-check.sh    libvirt-socket-start.sh
[root@host2 libvirt]# 
....

== create a kickstart file

Create the kickstart file for guest1. 

[source,shell]
....
[root@host1 libvirt]# vi vm-guest1-rhel9.ks 
....

The kickstart content is about 50 lines of text containing dozens of commands. 

The product document 
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/index[Performing an advanced RHEL installation] 
is all about kickstart installs.
Search the   
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/kickstart-commands-and-options-reference_installing-rhel-as-an-experienced-user[list of commands] to find an explanation of each line. . 

An online https://access.redhat.com/labs/kickstartconfig/[kickstart generator] can create kickstart content. The administrator fills in a form and the generator converts it to kickstart config. 

Add content. 

[source,shell]
....
# kickstart file
# https://github.com/nickhardiman/summit_OD1226/blob/main/kickstart_files/kickstart-rhel9-1.ks
# Kickstart user guide is here.
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html-single/performing_an_advanced_rhel_installation/index#kickstart_references
# This tool creates a kickstart file. 
# https://access.redhat.com/labs/kickstartconfig/

# command section
# -----------------------------------

# install
# don't use graphical install
text
# look for an installer DVD
cdrom
# Run the Setup Agent on first boot
firstboot --enable

# l10n (localization)
lang en_GB.UTF-8
timezone Europe/London --utc
keyboard --vckeymap=gb

# network
network  --bootproto=dhcp --device=enp1s0 --ipv6=auto --activate
network  --bootproto=dhcp --device=enp2s0 --ipv6=auto --activate
network  --hostname=guest1.lab.example.com

# licences and repos
# And have a look at the "subscription" section, in the post section below. 
#repo --name="AppStream" --baseurl=file:///run/install/repo/AppStream
eula --agreed

# accounts
# root and nick, both with password "Password;1".
# The command "openssl passwd  -6 --salt SQXqGsYna84.3SL5" turns "Password;1" into this. 
rootpw --iscrypted $6$SQXqGsYna84.3SL5$gJw6v23ZZ7WEITfBoZmyNDsIKeoqhS2Mwfk.KpCRloK7EfxlhL3MAlTCO33fr7QRfoG.GvBH1seWtQqz5v82q1
user --groups=wheel --name=nick --password=$6$G3GIlnUH.JqcrAQl$I.q7gGoT37tcNnrGiHkeUTBtr8AAuoM/yy3P3FuEpJaSun6clgR8GlvKIbqOTgqNe.fIBV6xZOPiWvsduhXeC/ --iscrypted --gecos="nick"

# storage 
# The virtual machine has a 30GB disk.
# All these partitions must fit in that space.
ignoredisk --only-use=vda
# Partition clearing information
clearpart --all --initlabel
part /boot/efi --fstype="efi"   --ondisk=vda --size=600 --fsoptions="umask=0077,shortname=winnt"
part /boot     --fstype="xfs"   --ondisk=vda --size=1024
# 28GiB * 1024 = 28672MiB
part pv.03    --fstype="lvmpv"  --ondisk=vda --size=28672
volgroup rhel pv.03
logvol /     --fstype="xfs"  --size=13312  --name=root --vgname=rhel
logvol /var  --fstype="xfs"  --size=13312  --name=var  --vgname=rhel
logvol swap  --fstype="swap" --size=256    --name=swap --vgname=rhel

# applications and services 
# Do not configure the X Window System
skipx
services --enabled="chronyd"
selinux --enforcing
firewall --enabled --http --ssh

# after installing the OS
# skip anaconda's prompt "Installation complete. Press ENTER to quit:"
reboot

# extra sections 
# -----------------------------------

# package selection section
# user guide: 
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html/managing_software_with_yum/index
%packages
# This is an environment group of packages.
# View the full list of groups to choose from by running this command.
#   dnf group list --hidden
@^minimal-environment
# single package
kexec-tools
%end

# add-on section
# kdump kernel crash dump mechanism
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html-single/performing_an_advanced_rhel_installation/index#addon-com_redhat_kdump_kickstart-commands-for-addons-supplied-with-the-rhel-installation-program
%addon com_redhat_kdump --enable --reserve-mb='auto'
%end
#

# last jobs
%post --log=/root/ks-post.log
# subscription
# use your Red Hat developer account and your subscription entitlement.
/usr/sbin/subscription-manager register --username=nick --password='some password!' 
/usr/sbin/subscription-manager attach --pool=123456789abcdef123456789abcdef12
%end
....

Save your work. 

