= create a kickstart file for guest1 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 11-01-2021

Create a kickstart file for the virtual machine guest1.
This machine will be built using a *fresh install* build process, as opposed to a golden image build process. 
Build a machine and install the OS. 
Use a kickstart file to automate the process. 



== a fresh install 

A fresh install (AKA clean install, or install from scratch) asks the user what is required, then builds the system to match. 
The kickstart file provides answers to what is required, so there is no need to ask the user anything. 

The resulting machine will contain some old packages. 
It won't be up-to-date until a _dnf update_ is run.
Packages are copied from the installer ISO, and these don't get updates; they aren't re-made every time a package is updated.  The older an ISO is, the more packages need updating. 

Many types of machine may be installed using many kickstart files. 
A library of these kickstart files takes up less space than a library of golden image files. 

An alternative process is to use an existing machine's storage file as a _golden image_, and make a copy. 
Another alternative is to install over the network. 


== create a kickstart file

Create a new https://en.wikipedia.org/wiki/Kickstart_(Linux)[kickstart] file.
This file will contain all the configuration instructions for the kickstart program to follow. 

The naming policy for this file is "__machine_name__.ks". 
The storage policy is to stick everything in one directory off root's home. 
This kickstart config file goes in the _libvirt_ directory, along with bridge scripts and libvirt XML definitions. 

[source,shell]
....
[root@host1 images]# cd
[root@host1 ~]# mkdir libvirt
[root@host1 ~]# cd libvirt
[root@host1 libvirt]# vi guest1.ks 
....

The kickstart content is about 50 lines of text containing dozens of commands. 

The product document 
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/index[Performing an advanced RHEL installation] 
is all about kickstart installs.
Search the   
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/kickstart-commands-and-options-reference_installing-rhel-as-an-experienced-user[list of commands] to find an explanation of each line. . 

An online https://access.redhat.com/labs/kickstartconfig/[kickstart generator] can create kickstart content. The administrator fills in a form and the generator converts it to kickstart config. 

[source,shell]
....
# kickstart file for guest1.lab.example.com

# install
# don't use graphical install
text
# look for an installer DVD
cdrom
# Run the Setup Agent on first boot
firstboot --enable

# l10n (localization)
lang en_GB.UTF-8
timezone Europe/London --isUtc
keyboard uk

# network
network  --bootproto=dhcp --device=enp1s0 --ipv6=auto --activate
network  --bootproto=dhcp --device=enp2s0 --ipv6=auto --activate
network  --hostname=guest1.lab.example.com

# licences and repos
# And have a look at the "subscription" section, in the post section below. 
repo --name="AppStream" --baseurl=file:///run/install/repo/AppStream
eula --agreed

# accounts
# The command "openssl passwd  -6 --salt SQXqGsYna84.3SL5" turns "Password;1" into this. 
rootpw --iscrypted $6$SQXqGsYna84.3SL5$gJw6v23ZZ7WEITfBoZmyNDsIKeoqhS2Mwfk.KpCRloK7EfxlhL3MAlTCO33fr7QRfoG.GvBH1seWtQqz5v82q1
user --groups=wheel --name=nick --password=$6$G3GIlnUH.JqcrAQl$I.q7gGoT37tcNnrGiHkeUTBtr8AAuoM/yy3P3FuEpJaSun6clgR8GlvKIbqOTgqNe.fIBV6xZOPiWvsduhXeC/ --iscrypted --gecos="nick"

# storage 
ignoredisk --only-use=vda
# Partition clearing information
clearpart --all --initlabel
part /boot/efi --fstype="efi"   --ondisk=vda --size=600 --fsoptions="umask=0077,shortname=winnt"
part pv.217    --fstype="lvmpv" --ondisk=vda --size=40175
part /boot     --fstype="xfs"   --ondisk=vda --size=1024
volgroup rhel --pesize=4096 pv.217
logvol /     --fstype="xfs"  --size=1024  --name=root --vgname=rhel --grow
logvol swap  --fstype="swap" --size=256   --name=swap --vgname=rhel

# applications and services 
# Do not configure the X Window System
skipx
services --enabled="chronyd"

# done
# skip anaconda's prompt "Installation complete. Press ENTER to quit:"
reboot


# special install sections

%packages
# This is a group of packages. 
# To view the full list of groups, run
#   dnf group list --hidden
@^minimal-environment
# This is a single package.
kexec-tools

%end

%addon com_redhat_kdump --enable --reserve-mb='auto'

%end

# password policy (for the anaconda installer, not PAM)
%anaconda
pwpolicy root --minlen=6 --minquality=1 --notstrict --nochanges --notempty
pwpolicy user --minlen=6 --minquality=1 --notstrict --nochanges --emptyok
pwpolicy luks --minlen=6 --minquality=1 --notstrict --nochanges --notempty
%end

# last jobs
%post --log=/root/ks-post.log
# subscription
# use your Red Hat developer account
/usr/sbin/subscription-manager register --username=nick --password='some password!' 
/usr/sbin/subscription-manager attach --pool=123456789abcdef123456789abcdef12
# package update
/usr/bin/dnf -y update 
%end

....


== check the kickstart file 

The kickstart validation utility _ksvalidator_ provides a static analysis of the new file.
It's not installed by default. 
The validator helps to catch mistakes like typos, like this. 

[source,shell]
....
[root@host1 libvirt]# ksvalidator guest1.ks 
The following problem occurred on line 3 of the kickstart file:

Unknown command: ingoredisk

[root@host1 libvirt]# 
....

Install the kickstart tools package. 
The package also contains tools _ksflatten_, _ksshell_ and _ksverdiff_.

[source,shell]
....
[root@host1 libvirt]# dnf install pykickstart 
...
Complete!
[root@host1 libvirt]# 
....

Validate the file. 
No news is good news. 

[source,shell]
....
[root@host1 libvirt]# ksvalidator guest1.ks 
[root@host1 libvirt]# 
....

