= enable guest2's second interface 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 29-07-2022

??? required? 

.guest1 and guest2 network interfaces
----
            + pubbr0                                + privbr0                              + privbr1
            |                                       |                                      |
            |     +--------------------------+      |     +--------------------------+     |
            |     |  guest1.lab.example.com  |      |     |  guest2.lab.example.com  |     |
  Internet  |     |                          |      |     |                          |     |
  <---------+-----+ enp1s0            enp2s0 +------+-----+ eth0                eth1 +-----+
            |     |                          |      |     |                          |     |
            |     +--------------------------+      |     +--------------------------+     |
----


== display interface settings

This machine has two network interfaces, eth0 and eth1.
Guest1 has enp1s0 and enp2s0.


[source,shell]
....
[root@guest2 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:01:00:03 brd ff:ff:ff:ff:ff:ff
    altname enp1s0
    inet 192.168.1.84/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 85948sec preferred_lft 85948sec
    inet6 2a00:23a8:4b47:fc01:7be6:bae2:6eb1:174d/64 scope global dynamic noprefixroute 
       valid_lft 62207990sec preferred_lft 31103990sec
    inet6 fdaa:bbcc:ddee:0:d917:6b72:adb7:a3fb/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::11e3:af21:a7be:c17e/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:02:00:02 brd ff:ff:ff:ff:ff:ff
    altname enp2s0
    inet 192.168.152.114/24 brd 192.168.152.255 scope global dynamic noprefixroute eth1
       valid_lft 3151sec preferred_lft 3151sec
    inet6 2001:db8:ca2:3:efdc:2d50:178e:e68d/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::7e15:d95e:6a56:b8b4/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
[root@guest2 ~]# 
....

NetworkManager created a configuration to manage enp2s0, but it is not set to start automatically. 

[source,shell]
....
[nick@guest2 ~]$ nmcli con 
NAME    UUID                                  TYPE      DEVICE 
enp1s0  b5220e04-f959-454c-8c89-4b0006f0050a  ethernet  enp1s0 
enp2s0  82d6f9e9-1364-4685-89dd-143c676c946a  ethernet  --     
[nick@guest2 ~]$ 
....

== autoconnect 

Turn on autoconnect and check again. 

[source,shell]
....
[nick@guest2 ~]$ sudo nmcli con mod enp2s0 connection.autoconnect yes
[sudo] password for nick: 
[nick@guest2 ~]$ 
[nick@guest2 ~]$ nmcli con 
NAME    UUID                                  TYPE      DEVICE 
enp1s0  b5220e04-f959-454c-8c89-4b0006f0050a  ethernet  enp1s0 
enp2s0  82d6f9e9-1364-4685-89dd-143c676c946a  ethernet  enp2s0 
[nick@guest2 ~]$ 
....

A dnsmasq DHCP server manages IP addresses for this network.
The server issues an IP address to guest2. 

Check the interface. 

[source,shell]
....
[nick@guest2 ~]$ ip addr show dev enp2s0
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:00:00:02 brd ff:ff:ff:ff:ff:ff
    inet 192.168.126.28/24 brd 192.168.126.255 scope global dynamic noprefixroute enp2s0
       valid_lft 3547sec preferred_lft 3547sec
    inet6 fe80::12d7:778d:1fe6:386f/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
[nick@guest2 ~]$ 
....


== check the DHCP lease

Open another terminal. 

Check on _host1_. 

[source,shell]
....
[nick@host1 ~]$ sudo virsh net-dhcp-leases privbr0 
 Expiry Time           MAC address         Protocol   IP address          Hostname   Client ID or DUID
-----------------------------------------------------------------------------------------------------------
 2021-01-12 18:40:32   52:54:00:00:00:02   ipv4       192.168.126.28/24   guest2     01:52:54:00:00:00:02

[nick@host1 ~]$ 
....


== fix default routes

NetworkManager created two default network routes for the two interfaces. 

[source,shell]
....
[root@guest2 ~]# ip route list
default via 192.168.1.254 dev enp1s0 proto dhcp metric 100 
default via 192.168.126.1 dev enp2s0 proto dhcp metric 101 
192.168.1.0/24 dev enp1s0 proto kernel scope link src 192.168.1.217 metric 100 
192.168.126.0/24 dev enp2s0 proto kernel scope link src 192.168.126.100 metric 101 
[root@guest2 ~]# 
....

General traffic should be pushed out to the Internet, not towards the private network. 
The only default route should be for enp1s0. 

The attribute to change is never-default. 

[source,shell]
....
[root@guest2 ~]# nmcli con show enp2s0 | grep never-default
ipv4.never-default:                     no
ipv6.never-default:                     no
[root@guest2 ~]# 
....

Change the attribute. 

[source,shell]
....
[root@guest2 ~]# nmcli connection modify enp2s0 ipv4.never-default yes
[root@guest2 ~]# nmcli connection modify enp2s0 ipv6.never-default yes
[root@guest2 ~]# 
....

Restart the connectin. 

[source,shell]
....
[root@guest2 ~]# nmcli con down enp2s0
Connection 'enp2s0' successfully deactivated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/2)
[root@guest2 ~]# 
[root@guest2 ~]# nmcli con up enp2s0
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/3)
[root@guest2 ~]# 
....


== check routing 

!!! if guest2 is attached to public0 and private0, this is OK
 if guest2 is attached to private0 and private1, this doesnt work. fixed by:
 ip route add default via 192.168.152.72
 but thats not great.
see https://hardiman.consulting/rhel/8/virtual-machine/guest2-os-setup.html


Check the routing table. 

Running _ip r_ is the same as running _ip route list_.

[source,shell]
....
[root@guest2 ~]# ip r
default via 192.168.1.254 dev enp1s0 proto dhcp metric 100 
192.168.1.0/24 dev enp1s0 proto kernel scope link src 192.168.1.217 metric 100 
192.168.126.0/24 dev enp2s0 proto kernel scope link src 192.168.126.100 metric 101 
[root@guest2 ~]# 
....

Ping Google. 

[source,shell]
....
[root@guest2 ~]# ping -c1 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=10.4 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 10.363/10.363/10.363/0.000 ms
[root@guest2 ~]# 
....


