= add a subscription the kickstart file
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 29-07-2022


If a machine is not registered with Red Hat, it can't use Red Hat repositories. 
RHEL comes with a utility named subscription-manager, a client which helps customers use the central Red Hat Subscription Management service. 

[source,shell]
....
[root@guest1 ~]# dnf repolist
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

No repositories available
[root@guest1 ~]# 
....


== add subscription user, password and pool ID

These two lines can be customized,  to automatically entitle your new machine to updates from Red Hat. 

Edit the kickstart file.

Update these username, password and pool values. 

[source,shell]
....
/usr/sbin/subscription-manager register --username=rocky --password='balboa4thewin' 
/usr/sbin/subscription-manager attach --pool=abcd56789abcdef123456789abcdefaa
....

