= examine the RHEL KVM image
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 23-11-2020

Look inside Red Hat's ready-made KVM image, rhel-baseos-9.0-x86_64-kvm.qcow2. 
We will use this image to create a new storage volume, _guest2.qcow2_.


== install utilities

Examine the KVM image with utilities _virt-inspector_ and _virt-filesystems_.
Copy it with a few more utilities: _virt-filesystems_, _virt-resize_ and _virt-customize_. 
These are part of the _guestfs-tools_ package.

[source,shell]
----
[nick@host2 ~]$ dnf provides virt-inspector
Not root, Subscription Management repositories not updated

This system is not registered with an entitlement server. You can use subscription-manager to register.

guestfs-tools-1.46.1-6.el9.x86_64 : Tools to access and modify virtual machine disk images
Repo        : rhel-9-for-x86_64-appstream-rpms
Matched from:
Filename    : /usr/bin/virt-inspector

[nick@host2 ~]$ 
----

Install the _libguestfs-tools_ package. 

[source,shell]
----
sudo dnf install guestfs-tools
----

List utilities this package provides. 

[source,shell]
----
[nick@host2 ~]$ rpm -ql guestfs-tools | grep /usr/bin/
/usr/bin/virt-alignment-scan
/usr/bin/virt-builder
/usr/bin/virt-builder-repository
/usr/bin/virt-cat
/usr/bin/virt-customize
/usr/bin/virt-df
/usr/bin/virt-diff
/usr/bin/virt-edit
/usr/bin/virt-filesystems
/usr/bin/virt-format
/usr/bin/virt-get-kernel
/usr/bin/virt-index-validate
/usr/bin/virt-inspector
/usr/bin/virt-log
/usr/bin/virt-ls
/usr/bin/virt-make-fs
/usr/bin/virt-resize
/usr/bin/virt-sparsify
/usr/bin/virt-sysprep
/usr/bin/virt-tail
[nick@host2 ~]$ 
----

== use virt-inspector

View the partitions inside the _rhel-baseos-9.0-x86_64-kvm.qcow2_ file. 

The _virt-inspector_ utility can display this information. 
The command `virt-inspector rhel-baseos-9.0-x86_64-kvm.qcow2` displays a lot of information about this file. 
In fact, it produces a vast amount of data  - far more than required here.
It's a long XML document, mostly describing installed packages. 

[source,shell]
----
[nick@host2 ~]$ virt-inspector /var/lib/libvirt/images/rhel-baseos-9.0-x86_64-kvm.qcow2
<?xml version="1.0"?>
<operatingsystems>
  <operatingsystem>
    <root>/dev/sda4</root>

...(thousands of lines of XML)...

twZoi5BMAwMbqepJn5D+TVGq7kA09KCwiy1Ztm1mQ/p7ZCkpKSkpKSkpKSkpKSkpcfE/4FVa
6yrQieoAAAAASUVORK5CYII=</icon>
  </operatingsystem>
</operatingsystems>
[nick@host2 ~]$ 
----

Use XPATH to display the filesystem part of the XML document. 

[source,XML]
----
[nick@host2 ~]$ virt-inspector -a /var/lib/libvirt/images/rhel-baseos-9.0-x86_64-kvm.qcow2 | virt-inspector --xpath '//filesystems'
<filesystems>
  <filesystem dev="/dev/sda2">
    <type>vfat</type>
    <uuid>7B77-95E7</uuid>
  </filesystem>
  <filesystem dev="/dev/sda3">
    <type>xfs</type>
    <label>boot</label>
    <uuid>5e75a2b9-1367-4cc8-bb38-4d6abc3964b8</uuid>
  </filesystem>
  <filesystem dev="/dev/sda4">
    <type>xfs</type>
    <label>root</label>
    <uuid>fb535add-9799-4a27-b8bc-e8259f39a767</uuid>
  </filesystem>
</filesystems>
[nick@host2 ~]$ 
----


=== use virt-filesystems

Use the _virt-filesystems_ command to display a list of partitions. 

[source,shell]
----
[nick@host2 ~]$ virt-filesystems --parts --add  /var/lib/libvirt/images/rhel-baseos-9.0-x86_64-kvm.qcow2
/dev/sda1
/dev/sda2
/dev/sda3
/dev/sda4
[nick@host2 ~]$ 
----

Take a closer look at those partitions by listing file systems. 
The root file system is _/dev/sda4_, which is about 9 GiB in size (take 9990811648 bytes,  divide by 1024 for KiB, and divide by 1024 again for MiB, and finally divide by 1024 for GiB. Try running `echo "9990811648 / 1024 / 1024 / 1024" | bc` on the CLI). 


[source,shell]
----
[nick@host2 ~]$ virt-filesystems --filesystems --long  --add  /var/lib/libvirt/images/rhel-baseos-9.0-x86_64-kvm.qcow2
Name       Type        VFS   Label  Size        Parent
/dev/sda2  filesystem  vfat  -      209489920   -
/dev/sda3  filesystem  xfs   boot   518684672   -
/dev/sda4  filesystem  xfs   root   9990811648  -
[nick@host2 ~]$ 
----

The file is a fraction the size of this partition. 
It's only 696582144 bytes, which is about 665 mebibytes. 
A https://en.wikipedia.org/wiki/Qcow[QCOW] file can be compressed to save space. 

[source,shell]
----
[nick@host2 ~]$ ls -l  /var/lib/libvirt/images/rhel-baseos-9.0-x86_64-kvm.qcow2
-rw-r--r--. 1 root root 696582144 Jul 27 16:38 /var/lib/libvirt/images/rhel-baseos-9.0-x86_64-kvm.qcow2
[nick@host2 ~]$ 
[nick@host2 ~]$ ls -lh  /var/lib/libvirt/images/rhel-baseos-9.0-x86_64-kvm.qcow2
-rw-r--r--. 1 root root 665M Jul 27 16:38 /var/lib/libvirt/images/rhel-baseos-9.0-x86_64-kvm.qcow2
[nick@host2 ~]$ 
----



