= examine libvirt's private0 network 
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 11-01-2021



RHEL includes a complete system for managing VMs (virtual machines) - the KVM hypervisor, QEMU machine emulator and libvirt tools. 
The libvirt daemon uses http://www.thekelleys.org.uk/dnsmasq/doc.html[dnsmasq] to provide 
https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol[DHCP] 
and https://en.wikipedia.org/wiki/Domain_Name_System[DNS] services. 
This article configures dnsmasq to set a fixed IPv4 address and domain name for our new guest VM. 

The _private0_ DHCP setup isn't great if you want to SSH to your new VM, because it takes some work to figure out what IPv4 address to use.  
When the guest VM boots up, it is given the address 192.168.152...er...something. 
The dnsmasq DHCP service assigns addresses from an IP pool, so the VM gets a random address from the range 192.168.152.0/24. 

Instead of searching for the address after every boot, it's easier to assign a fixed IP address. 
All we need to get started is the MAC address, and that was fixed by the _virt-install_ command when the VM was created (``52:54:00:00:00:03``). 

People remember names better than numbers. A fixed IP address is easier to use than a random IP address, and a DNS name is easier still.  
Out of the box, dnsmasq reads names and addresses from the /etc/hosts file. 
Add _guest2.private.example.com_ to two places. 

* the host's /etc/hosts file, so the host can look up the guest's name
* the host's dnsmasq configuration, so guests can look up the name


== dnsmasq services 

Usually _systemd_ is in charge of running services, but not here. 
The _libvirtd_ daemon controls _dnsmasq_ services, not systemd. 
Running the command ``systemctl status dnsmasq`` says dnsmasq isn't running. 

[source,shell]
....
[nick@host1 ~]# systemctl status dnsmasq
● dnsmasq.service - DNS caching server.
   Loaded: loaded (/usr/lib/systemd/system/dnsmasq.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[nick@host1 ~]# 
....

One pair of processes - a parent and child - are started for each libvirt network that needs DHCP.
The _public0_ network doesn't use dnsmasq.
The _default_ and _private0_ networks do.

[source,shell]
....
[nick@host1 ~]# ps -fwwC dnsmasq
UID          PID    PPID  C STIME TTY          TIME CMD
dnsmasq     2077       1  0 08:16 ?        00:00:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
root        2078    2077  0 08:16 ?        00:00:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
dnsmasq    16756       1  0 20:16 ?        00:00:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/private0.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
root       16757   16756  0 20:16 ?        00:00:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/private0.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
[nick@host1 ~]#  
....



== check the IP pool 

View the dnsmasq configuration. 
Its config files are in the folder /var/lib/libvirt/dnsmasq/. 

This ``dhcp-range`` line tells dnsmasq what IP pool to manage for the _private0_ network. 

[source,shell]
....
[nick@host1 ~]$ sudo grep dhcp-range /var/lib/libvirt/dnsmasq/private0.conf
[sudo] password for nick: 
dhcp-range=192.168.152.2,192.168.152.254,255.255.255.0
dhcp-range=2001:db8:ca2:3::1,ra-only
[nick@host1 ~]$ 
....

View the libvirt configuration. 
libvirt writes that dnsmasq configuration after reading its own network configuration.
You can see libvirt's configuration  using the ``virsh net-dumpxml`` command.
There are about 20 lines of XML that define the network.
These are all listed further down. 

The IP pool config is between a pair of dhcp tags.  

[source,shell]
....
[nick@host1 ~]$ sudo virsh net-dumpxml private0
...
    <dhcp>
      <range start='192.168.152.2' end='192.168.152.254'/>
    </dhcp>
...
[nick@host1 ~]$ 
....


== assign a name and address

Add an XML tag to the network's configuration.

This dnsmasq config file can't be edited directly because it's created by libvirt - any changes would be overwritten. 
Instead, use ``virsh`` commands to add config. 


