= plan the virtual machines 
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 21-06-2022



[source,shell]
....
+-------------------------------------------+
|          host1.lab.example.com            |
|                  192.168.1.195 +--+-------+---(home network) 
|                                   |       |
|                            pubbr0 |       |   
|                    192.168.1.0/24 |       |   
|                                   |       |
|  +-----------------------------+  |       |
|  |      guest1.lab.example.com |  |       |
|  |               192.168.1.217 +--+       |   
|  |                             |          |
|  | guest1.private1.example.com |          |
|  |              192.168.152.11 +--+       |
|  +-----------------------------+  |       |
|                                   |       |
|                           privbr0 |       |   
|                  192.168.152.0/24 |       |   
|                                   |       |
|  +-----------------------------+  |       |
|  | guest2.private1.example.com |  |       |
|  |             192.168.152.100 +--+       |
|  |                             |          |
|  | guest2.private2.example.com |          |
|  |             192.168.162.100 +--+       |
|  +-----------------------------+  |       |
|                                   |       |
|                           privbr1 |       |   
|                  192.168.162.0/24 |       |   
|                                   |       |
|  +-----------------------------+  |       |
|  | guest3.private2.example.com |  |       |
|  |             192.168.162.101 +--+       |
|  |                             |          |
|  +-----------------------------+          |
|                                           |
+-------------------------------------------+
....


== guest1 

Machines host1 and guest1 are connected to pubbr0.  
You can get to these machines from the workstation, to view web pages, send mail and so on. 
IP addresses are assigned by the home network. 
I have a home router provided by my ISP, which has a built-in DHCP server. 
This DHCP server dishes out IPv4 addresses in the range 192.168.1.0/24.

The virtual machine guest1 is connected to both bridges pubbr0 and privbr0 - it acts as a gateway between the other guests and the outside world. 

== guest2 and guest3

Two machines are only connected to privbr0 - guest2 and guest3. 
These are protected.
You can only SSH to these machines from host1 or guest1. 
They can only get to the home network and Internet via guest1. 
It's good for security, but bad for laziness because work is required to make these hidden machines useful. 


