= Err, where am I? 
Nick Hardiman <nick@silvan.uk>
:source-highlighter: highlight.js
:revdate: 01-01-2021


xref:author.adoc[I'm Nick]. 
The site you are looking at here is my collection of hardware and software docs. 

If you are looking for tech help, stick a word in the search bar above. 
I hope you find something that helps. 

This section is all about RHEL and the many sysadmin things you can do with a free Red Hat Developer subscription.  
There's a pop-up selector bottom left that takes you to my other documentation sections.  


== this section 

[NOTE]
====
These docs have nothing to do with the official https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/[Product Documentation for Red Hat Enterprise Linux].
====

What can you do with a free Red Hat Developer subscription?  
A surprising amount, actually. 
As you can see from the navbar on the left, articles cover sysadmin tasks like these.  

* Install RHEL on a physical machine
* Create a network of virtual machines.
* Add containers to VMs. 
* Set up developer environments. 

These pages are for system administrators, not business administrators. 
The kind of people who enjoy hands on a keyboard, can cope with the CLI, and want to learn.


== get in touch

Something wrong? 
https://github.com/nickhardiman/articles-rhel8/issues[Open an issue on GitHub].

