= Err, where am I? 
Nick Hardiman <nick@silvan.uk>
:source-highlighter: highlight.js
:revdate: 01-01-2021


xref:author.adoc[I'm Nick]. 
The site you are looking at here is my collection of hardware and software docs. 

If you are looking for tech help, stick a word in the search bar above. 
I hope you find something that helps. 


== here, on this site 

The _Here_ option above, up top in the navbar, can take you to my other documentation sections. There's a pop-up selector bottom left that does the same kind of thing. 

Here's my wishlist of things to document. 

*  Fedora on a Raspberry Pi 4 
*  RHEL on an ASUS PN50 
*  OCP4 on an ASUS PN51 
*  Satellite 6 on an HPE Proliant Gen10 Microserver
*  VMware Vsphere 7 on an Intel NUC
*  Ansible to tie it all together


== this section 

[NOTE]
====
These docs have nothing to do with the official https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/[Product Documentation for Red Hat Enterprise Linux].
====

What can you do with a free Red Hat Developer subscription?  
A surprising amount, actually. 
As you can see from the navbar on the left, articles cover sysadmin tasks like these.  

* Install RHEL on a physical machine
* Create a network of virtual machines.
* Add containers to VMs. 
* Set up developer environments. 

These pages are for system administrators, not business administrators. 
The kind of people who enjoy hands on a keyboard, can cope with the CLI, and want to learn.


== get in touch

Something wrong? 
https://github.com/nickhardiman/articles-rhel8/issues[Open an issue on GitHub].

