= enable libvirt's modular daemons
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 05-01-2022

The https://libvirt.org/[libvirt] project provides a virtualization management system. 
It ties together a few infrastructure building blocks like QEMU, bridge, DHCP and DNS.



== manually enable libvirt sockets

Enable sockets for 6 of the services. 
There are no less than 18 sockets to enable, because each service uses 3 sockets - the main socket for communication, plus one for administration and a read-only socket. 

The QEMU virtual machine service virtqemud has three systemd unit files.

* virtqemud-admin.socket
* virtqemud-ro.socket
* virtqemud.socket

[source,shell]
----
[root@host1 ~]# for drv in qemu network nodedev nwfilter secret storage
  do
    systemctl enable virt$+{drv}+d{,-ro,-admin}.socket
  done
Created symlink /etc/systemd/system/sockets.target.wants/virtnetworkd-ro.socket → /usr/lib/systemd/system/virtnetworkd-ro.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtnetworkd-admin.socket → /usr/lib/systemd/system/virtnetworkd-admin.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtnodedevd-ro.socket → /usr/lib/systemd/system/virtnodedevd-ro.socket.
...
Created symlink /etc/systemd/system/sockets.target.wants/virtsecretd-admin.socket → /usr/lib/systemd/system/virtsecretd-admin.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtstoraged-ro.socket → /usr/lib/systemd/system/virtstoraged-ro.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtstoraged-admin.socket → /usr/lib/systemd/system/virtstoraged-admin.socket.
[root@host1 ~]# 
----


== tell Ansible to enable libvirt sockets

Edit the role.

[source,shell]
----
vim ~/ansible/roles/virtualization-host/tasks/main.yml
----

Add tasks. 

[source,YAML]
----
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
- name: enable libvirt's systemd socket files
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  loop:
    - virtnetworkd-admin.socket
    - virtnetworkd-ro.socket
    - virtnetworkd.socket
    - virtnodedevd-admin.socket
    - virtnodedevd-ro.socket
    - virtnodedevd.socket
    - virtnwfilterd-admin.socket
    - virtnwfilterd-ro.socket
    - virtnwfilterd.socket
    - virtqemud-admin.socket
    - virtqemud-ro.socket
    - virtqemud.socket
    - virtsecretd-admin.socket
    - virtsecretd-ro.socket
    - virtsecretd.socket
    - virtstoraged-admin.socket
    - virtstoraged-ro.socket
    - virtstoraged.socket
----


== manually enable libvirt services 

Enable most of the modular daemons. 
virtlockd and virtlogd are indirect ???
virtinterfaced is not required because ???
virtproxyd is only needed for requests from other hosts. 


[source,shell]
----
[root@host1 ~]# for drv in qemu network nodedev nwfilter secret storage
  do
    systemctl enable virt$+{drv}+d.service
  done
Created symlink /etc/systemd/system/sockets.target.wants/virtlogd.socket → /usr/lib/systemd/system/virtlogd.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtlockd.socket → /usr/lib/systemd/system/virtlockd.socket.
Created symlink /etc/systemd/system/multi-user.target.wants/virtnetworkd.service → /usr/lib/systemd/system/virtnetworkd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/virtnodedevd.service → /usr/lib/systemd/system/virtnodedevd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/virtnwfilterd.service → /usr/lib/systemd/system/virtnwfilterd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/virtsecretd.service → /usr/lib/systemd/system/virtsecretd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/virtstoraged.service → /usr/lib/systemd/system/virtstoraged.service.
[root@host1 ~]# 
----


== tell Ansible to enable libvirt services

Edit the role.

[source,shell]
----
vim ~/ansible/roles/virtualization-host/tasks/main.yml
----

Add this task to the bottom of the file.  

[source,YAML]
----
- name: enable libvirt's systemd service files
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  loop:
    - virtnetworkd.service
    - virtnodedevd.service
    - virtnwfilterd.service
    - virtqemud.service
    - virtsecretd.service
    - virtstoraged.service
----


== manually start libvirt sockets

[source,shell]
----
[root@host1 ~]# for drv in qemu network nodedev nwfilter secret storage
  do
    systemctl start virt$+{drv}+d{,-ro,-admin}.socket
  done
[root@host1 ~]# 
----


== tell Ansible to start libvirt sockets

Edit the role.

[source,shell]
----
vim ~/ansible/roles/virtualization-host/tasks/main.yml
----

Add tasks. 

[source,YAML]
----
- name: start libvirt's systemd socket files
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
  loop:
    - virtnetworkd-admin.socket
    - virtnetworkd-ro.socket
    - virtnetworkd.socket
    - virtnodedevd-admin.socket
    - virtnodedevd-ro.socket
    - virtnodedevd.socket
    - virtnwfilterd-admin.socket
    - virtnwfilterd-ro.socket
    - virtnwfilterd.socket
    - virtqemud-admin.socket
    - virtqemud-ro.socket
    - virtqemud.socket
    - virtsecretd-admin.socket
    - virtsecretd-ro.socket
    - virtsecretd.socket
    - virtstoraged-admin.socket
    - virtstoraged-ro.socket
    - virtstoraged.socket
----


== run 

[source,shell]
----
[nick@host1 ansible]$ ansible-playbook --ask-become-pass virtualization-host.yml 
BECOME password: 
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [set up virtualization-host] **********************************************

TASK [virtualization-host : Install the 'Virtualization Host' environment group] ***
ok: [localhost]

TASK [virtualization-host : enable libvirt's systemd socket files] *************
ok: [localhost] => (item=virtnetworkd-admin.socket)
ok: [localhost] => (item=virtnetworkd-ro.socket)
ok: [localhost] => (item=virtnetworkd.socket)
...
PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

[nick@host1 ansible]$ 
----
