= build an image with buildah
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 31-01-2021


Build a new container from scratch.
Create a container image using _buildah_. 

== buildah 

This procedure doesn't use a dockerfile. 
Instead, the file system and base image are built by running a few commands manually. 
If you want to know more, try the commands in 
https://servicesblog.redhat.com/2019/10/09/say-hello-to-buildah-podman-and-skopeo/[Say “Hello” to Buildah, Podman, and Skopeo].

Make sure you have already installed the container-tools module. 

* xref:container-tools.adoc[]


== the perl web service

The content is a simple web service. 
This service is written in Perl, using a web framework called https://mojolicious.org/[mojolicious]. 
The _dnf_ package utility installs RPM packages that provide the OS and application, and 
perl installs the perl modules for the web service.


== start building a new image

Carry out these commands as root. 

Most of this works fine as a non-root user, but there are a few technical headaches. 
To find out more about rootless containers, check out 
https://www.redhat.com/sysadmin/rootless-podman-makes-sense[Running rootless Podman as a non-root user]. 
And for a description of how a rootless container works, have a look at 
https://www.redhat.com/sysadmin/behind-scenes-podman[What happens behind the scenes of a rootless Podman container?]


[source,shell]
----
[nick@guest3 ~]$ sudo su -
[sudo] password for nick: 
Last login: Thu Aug  6 12:39:14 EDT 2020 on pts/0
[root@guest1 ~]# 
----

Check before. There are no images yet, and no containers built from those images. 

[source,shell]
----
[root@guest1 ~]# buildah images
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
[root@guest1 ~]# 
[root@guest1 ~]# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
[root@guest1 ~]# 
----


Container files are stored in the directory /var/lib/containers/storage/overlay-containers/.

[source,shell]
----
[root@guest1 ~]# find /var/lib/containers/storage/
/var/lib/containers/storage/
/var/lib/containers/storage/mounts
/var/lib/containers/storage/tmp
/var/lib/containers/storage/overlay
/var/lib/containers/storage/overlay/l
/var/lib/containers/storage/overlay/backingFsBlockDev
/var/lib/containers/storage/storage.lock
/var/lib/containers/storage/userns.lock
/var/lib/containers/storage/overlay-images
/var/lib/containers/storage/overlay-images/images.lock
/var/lib/containers/storage/overlay-containers
/var/lib/containers/storage/overlay-containers/containers.lock
/var/lib/containers/storage/overlay-layers
/var/lib/containers/storage/overlay-layers/layers.lock
[root@guest1 ~]# 
[root@guest1 ~]# du -sh /var/lib/containers/storage/
8.0K	/var/lib/containers/storage/
[root@guest1 ~]# 
----


Create a container and add things to it. 
The _buildah from scratch_ command creates a new container called _working-container_.
It doesn't make an image - first the container is customized by adding things to the file system, then a new image is made from the file system. 

List this new container with `buildah containers`. 
If you want to start again, remove it with `buildah rm working-container`.

[source,shell]
----
[root@guest1 ~]# buildah from scratch
working-container
[root@guest1 ~]# 
[root@guest1 ~]# buildah images
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
[root@guest1 ~]# 
[root@guest1 ~]# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
b7e26ec492d1     *                  scratch                          working-container
[root@guest1 ~]#  
----

The framework for this new container is stored in the overlay and overlay-containers directories. 
New files will be added to the _merged_ directory. 

[source,shell]
----
[root@guest1 ~]# find /var/lib/containers/storage/overlay
/var/lib/containers/storage/overlay
/var/lib/containers/storage/overlay/l
/var/lib/containers/storage/overlay/l/WWABSETQARBBDF2PKZJO6RBU62
/var/lib/containers/storage/overlay/backingFsBlockDev
/var/lib/containers/storage/overlay/3213a9663182e9adc7de9ebc1bc68090ff4f26ab5a9a7228dabe77d864f1c562
/var/lib/containers/storage/overlay/3213a9663182e9adc7de9ebc1bc68090ff4f26ab5a9a7228dabe77d864f1c562/diff
/var/lib/containers/storage/overlay/3213a9663182e9adc7de9ebc1bc68090ff4f26ab5a9a7228dabe77d864f1c562/link
/var/lib/containers/storage/overlay/3213a9663182e9adc7de9ebc1bc68090ff4f26ab5a9a7228dabe77d864f1c562/work
/var/lib/containers/storage/overlay/3213a9663182e9adc7de9ebc1bc68090ff4f26ab5a9a7228dabe77d864f1c562/merged
/var/lib/containers/storage/overlay/3213a9663182e9adc7de9ebc1bc68090ff4f26ab5a9a7228dabe77d864f1c562/empty
[root@guest1 ~]# 
[root@guest1 ~]# find /var/lib/containers/storage/overlay-containers/
/var/lib/containers/storage/overlay-containers/
/var/lib/containers/storage/overlay-containers/containers.lock
/var/lib/containers/storage/overlay-containers/containers.json
/var/lib/containers/storage/overlay-containers/4ddfba6f2b2e6f4ba4290cca42af3bc87d53a15c0f0bbab75c109171fe07b79d
/var/lib/containers/storage/overlay-containers/4ddfba6f2b2e6f4ba4290cca42af3bc87d53a15c0f0bbab75c109171fe07b79d/userdata
/var/lib/containers/storage/overlay-containers/4ddfba6f2b2e6f4ba4290cca42af3bc87d53a15c0f0bbab75c109171fe07b79d/userdata/buildah.json
[root@guest1 ~]# 
[root@guest1 ~]# du -sh /var/lib/containers/storage/
28K	/var/lib/containers/storage/
[root@guest1 ~]# 
----


Tell buildah to mount this new root file system.
The command replies with the full path to that _merged_ directory. 
Keep a copy of the path - we need this for the _dnf install_ command. 

To unmount it, change `mount` to `umount`.

[source,shell]
----
[root@guest1 ~]# MOUNT_DIR=$(buildah mount working-container)
[root@guest1 ~]# 
[root@guest1 ~]# echo $MOUNT_DIR
/var/lib/containers/storage/overlay/bf033e812dd6b65a1e4a587b6a6b3ea54841e03fcced3fb8e4094e0946d3e631/merged
[root@guest1 ~]# 
----

== install RPM modules 

The new container won't have access to the OS's tools. 
Add a few inside the new file system - bash, coreutils, perl, dnf, iproute, and vi.
Use this dnf command to install the RPM packages that provide these tools.
The command only names 6 packages, but 280 packages are required when all the dependencies are worked out.  
This takes up a serious amount of space. 

[source,shell]
----
dnf install \
  --installroot=$MOUNT_DIR \
  --releasever=/  \
  --setopt=install_weak_deps=false \
  --setopt=tsflags=nocontexts \
  --setopt=module_platform_id=platform:el8 \
  --assumeyes  \
  bash coreutils perl dnf iproute vi
----

Run the command. 

[source,shell]
----
[root@guest1 ~]# dnf install   --installroot=$MOUNT_DIR   --releasever=/    --setopt=install_weak_deps=false   --setopt=tsflags=nocontexts   --setopt=module_platform_id=platform:el8   --assumeyes    bash coreutils perl dnf iproute vi
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Last metadata expiration check: 0:00:33 ago on Mon 15 Feb 2021 11:07:20 GMT.
Dependencies resolved.
================================================================================
 Package           Arch   Version        Repository                        Size
================================================================================
Installing:
 bash              x86_64 4.4.19-12.el8  rhel-8-for-x86_64-baseos-rpms    1.5 M
 coreutils         x86_64 8.30-8.el8     rhel-8-for-x86_64-baseos-rpms    1.2 M
 dnf               noarch 4.2.23-4.el8   rhel-8-for-x86_64-baseos-rpms    513 k
...
Complete!
[root@guest1 ~]# 
[root@guest1 ~]# du -sh /var/lib/containers/storage/
1.2G	/var/lib/containers/storage/
[root@guest1 ~]# 
----

Clear some space by removing cached data.

[source,shell]
----
[root@guest1 ~]# dnf clean all  --installroot $MOUNT_DIR  --releasever=/
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

17 files removed
[root@guest1 ~]# 
[root@guest1 ~]# du -sh /var/lib/containers/storage/
1002M	/var/lib/containers/storage/
[root@guest1 ~]# 
----


== install perl modules 

Convince perl to install in the new file system using the chroot command. 

The new file system doesn't have anything clever like DNS, so 
start by editing the hosts file. 

[source,shell]
----
[root@guest1 ~]# chroot $MOUNT_DIR
bash-4.4# echo "151.101.130.217 cpanmin.us" >> /etc/hosts
bash-4.4# echo "151.101.62.217 cpan.metacpan.org" >> /etc/hosts
bash-4.4# 
----

Install mojolicious. 

[source,shell]
----
bash-4.4# curl -L https://cpanmin.us | perl - -M https://cpan.metacpan.org -n Mojolicious
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  295k  100  295k    0     0  2067k      0 --:--:-- --:--:-- --:--:-- 2067k
--> Working on Mojolicious
Fetching https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-8.57.tar.gz ... OK
Configuring Mojolicious-8.57 ... OK
Building Mojolicious-8.57 ... OK
Successfully installed Mojolicious-8.57
1 distribution installed
bash-4.4# 
[root@guest1 ~]# du -sh /var/lib/containers/storage/
1.1G	/var/lib/containers/storage/
[root@guest1 ~]# 
----

Configure a web service. 

The command to start this new web service is `/usr/local/bin/morbo /hello.pl`. 
The _morbo_ command starts a web server - this file was installed along with mojolicious. 
This command makes the _hello.pl_ perl script. 

[source,shell]
----
echo "use Mojolicious::Lite;
get '/' => {text => 'I ♥ Mojolicious!'};
app->start;" > hello.pl
----

Create the perl script.

[source,shell]
----
bash-4.4# pwd
/
bash-4.4# 
bash-4.4# echo "use Mojolicious::Lite;
> get '/' => {text => 'I ♥ Mojolicious!'};
> app->start;" > hello.pl
bash-4.4# 
----

That's it. We're done with the chroot. 

[source,shell]
----
bash-4.4# exit
exit
[root@guest1 ~]# 
----

== finish the image

Set the default command to run to _/bin/bash_. 
This isn't what we'll use below.

Add a label. 
After the image is created, you can see this label using the command `podman inspect localhost/myperl`.

[source,shell]
----
[root@guest1 ~]# buildah config --cmd /bin/bash working-container
[root@guest1 ~]# 
[root@guest1 ~]# buildah config --label name=myperlservice working-container
[root@guest1 ~]# 
----

That's it for the container work.  
Unmount the file system. 
The container is still running. 

[source,shell]
----
[root@guest1 ~]# buildah unmount working-container
b7e26ec492d14eef0bd10c576a73168ef359be819c60a7ddd4ee2f6165f2260a
[root@guest1 ~]# 
[root@guest1 ~]# buildah unmount working-container
[root@guest1 ~]# 
[root@guest1 ~]# buildah images
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
[root@guest1 ~]# 
[root@guest1 ~]# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
4ddfba6f2b2e     *                  scratch                          working-container
[root@guest1 ~]# 
----

Create the image. 

[source,shell]
----
[root@guest1 ~]# buildah commit working-container myperl
Getting image source signatures
Copying blob 46b9422120aa done  
Copying config 1cca4b34f6 done  
Writing manifest to image destination
Storing signatures
1cca4b34f6abb293ef53e36546df1036d435c3df5894989d098b37900fe7f587
[root@guest1 ~]# 
[root@guest1 ~]# buildah images
REPOSITORY         TAG      IMAGE ID       CREATED          SIZE
localhost/myperl   latest   1cca4b34f6ab   41 seconds ago   547 MB
[root@guest1 ~]# 
[root@guest1 ~]# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
4ddfba6f2b2e     *                  scratch                          working-container
[root@guest1 ~]# 
----



== run with podman 

Check there are no containers, either running or stopped. 

[source,shell]
----
[root@guest1 ~]# podman ps -a
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
[root@guest1 ~]# 
----

Create a new container. 

The name of this new container is mojoservice. 
We've already created a repo name and a label name, and now we add a container name.

* The image repo is named "localhost/myperl".
* The "name" label in the config is "myperlservice". You can see this in the `skopeo` output above.
* The container name is "mojoservice". The `podman ps` command below shows this. 

This is the command to create a container. 
The last line is the command that runs our web service. 

[source,shell]
----
podman run \
  -p 3000:3000 \
  --detach \
  --name mojoservice \
  localhost/myperl \
  /usr/local/bin/morbo /hello.pl
----

Start a container and check. 

[source,shell]
----
[root@guest1 ~]# podman run -p 3000:3000 --detach --name mojoservice localhost/myperl /usr/local/bin/morbo /hello.pl
0ac2718c35df066bd8cf4da2d9992ed20d734e2b7c74cb955b42563237cd7a00
[root@guest1 ~]# 
[root@guest1 ~]# podman ps -a
CONTAINER ID  IMAGE                    COMMAND               CREATED        STATUS            PORTS                   NAMES
0ac2718c35df  localhost/myperl:latest  /usr/local/bin/mo...  5 seconds ago  Up 4 seconds ago  0.0.0.0:3000->3000/tcp  mojoservice
[root@guest1 ~]# 
----

Don't be distracted by the word pod in podman. 
This command runs a container, not a pod. 
To find out more about pods and containers, read 
https://developers.redhat.com/blog/2019/01/15/podman-managing-containers-pods/[Podman: Managing pods and containers in a local container runtime].

You can see the process responsible for this pod. 
It's an absolutely huge `conmon` command with 50 options, and no less than 1700 characters long. 
Luckily this is all created behind the scenes, and you don't have to understand any of this. 

[source,shell]
----
[root@guest1 ~]# ps -fwwC conmon
UID          PID    PPID  C STIME TTY          TIME CMD
root        1744       1  0 09:31 ?        00:00:00 /usr/bin/conmon --api-version 1 -s -c 635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5 -u 635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5/userdata -p /var/run/containers/storage/overlay-containers/635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5/userdata/pidfile -l k8s-file:/var/lib/containers/storage/overlay-containers/635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket --log-level error --runtime-arg --log-format=json --runtime-arg --log --runtime-arg=/var/run/containers/storage/overlay-containers/635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5/userdata/oci-log --conmon-pidfile /var/run/containers/storage/overlay-containers/635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /var/run/containers/storage --exit-command-arg --log-level --exit-command-arg error --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /var/run/libpod --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mountopt=nodev,metacopy=on --exit-command-arg --events-backend --exit-command-arg file --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5
[root@guest1 ~]# 
----


Does it work? 
Does the web service in the container respond?

It could do with an extra newline, but yes, all good. 

[source,shell]
----
[root@guest1 ~]# curl http://localhost:3000
I ♥ Mojolicious![root@guest1 ~]# 
----

Stop the new container. 

[source,shell]
----
[root@guest1 ~]# podman stop mojoservice
0ac2718c35df066bd8cf4da2d9992ed20d734e2b7c74cb955b42563237cd7a00
[root@guest1 ~]# 
----

If you want to get rid of the new container and image, 
clean up with `podman rm mojoservice` and `podman rmi localhost/myperl`.



