= update packages with DNF
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 12-01-2021

Connect with SSH and update packages with DNF.

If a system is installed from an ISO, there are probably newer packages to install. 
Install media don't get updated with the latest packages. 
The older the ISO file, the more packages require updates. 

If a system is installed from Red Hat's CDN, there may not be newer packages. 



== errata (updates, bug fixes and security patches)

Red Hat calls package updates _errata_ or _advisories_. There are three types. 

* A Red Hat Security Advisory (RHSA) package fixes security problems. 
* A Red Hat Bug Advisory (RHBA) fixes code problems. 
* A Red Hat Enhancement Advisory (RHEA) provides new features. 

For more information, read the article https://access.redhat.com/articles/2130961[Explaining Red Hat Errata (RHSA, RHBA, and RHEA)].

== install 

DNF packages are already installed. 
There's the dnf package which provides dnf itself, dnf-plugins-core which extends what dnf can do, python3-dnf which fills up /usr/lib/python3.6/site-packages/dnf/, and others.   

These packages provide DNF version 4. 

[source,shell]
----
[root@host1 images]# dnf --version
4.10.0
  Installed: dnf-0:4.10.0-5.el9_0.noarch at Sun 03 Jul 2022 09:32:58 GMT
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Mon 21 Mar 2022 10:08:17 GMT

  Installed: rpm-0:4.16.1.3-12.el9_0.x86_64 at Sun 03 Jul 2022 09:32:32 GMT
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Tue 05 Apr 2022 19:08:08 GMT
[root@host1 images]# 
----



== view errata

Use DNF to list all the updates this machine can get. 

If the system is up to date, the reply looks like this. 

[source,shell]
----
[root@host1 ~]# dnf updateinfo --list
Updating Subscription Management repositories.
Last metadata expiration check: 1:22:40 ago on Mon 25 Jul 2022 08:26:33 GMT.
[root@host1 ~]# 
----

If updates are available, they appear like this. 

[source,shell]
----
RHSA-2022:0052 Critical/Sec. package1-1.2.3-1.el9.x86_64
RHEA-2022:4727 enhancement   package2-1.2.3-1.el9.x86_64
RHBA-2022:3337 bugfix        package3-1.2.3-1.el9.x86_64
----

You can find out more about https://access.redhat.com/errata/#/[Red Hat Product Errata] on the https://access.redhat.com/[customer portal].
Security administrators can also search the  https://access.redhat.com/security/security-updates/#/cve[Red Hat CVE (Common Security Advisory) database].


== download repositories 

Packages will be downloaded from enabled repositories. 

[source,shell]
----
[root@host1 ~]# dnf repolist 
Updating Subscription Management repositories.
repo id                                            repo name
rhel-9-for-x86_64-appstream-rpms                   Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
rhel-9-for-x86_64-baseos-rpms                      Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
[root@host1 ~]# 
----


== update 

If the system is up to date, the reply looks like this. 

[source,shell]
----
[root@host1 ~]# dnf -y update
Updating Subscription Management repositories.
Last metadata expiration check: 0:34:38 ago on Mon 25 Jul 2022 17:12:41 BST.
Dependencies resolved.
Nothing to do.
Complete!
[root@host1 ~]# 
----

If some packages are updated and new ones are added, the reply looks like this. 

[source,shell]
----
[root@host1 ~]# dnf -y update
Updating Subscription Management repositories.
Last metadata expiration check: 0:04:07 ago on Mon 25 Jul 2022 17:12:41 BST.
Dependencies resolved.
...
Transaction Summary
======================================================
Install   3 Packages
Upgrade  74 Packages
...
Complete!
[root@host1 ~]# 
----



== reboot if the kernel is updated

Reboot to swap from the current kernel to the new one. 


[source,shell]
----
[root@host1 ~]# systemctl reboot
[root@host1 ~]# Connection to host1 closed by remote host.
Connection to host1 closed.
MacBook-Pro:~ nick$ 
----


