= Bash shell resource files
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 26-07-2022

An https://www.gnu.org/software/bash/manual/bash.html#Interactive-Shells[interactive shell] is connected to a user terminal - it reads from the keyboard and writes to the screen. 

A Bash login shell is for use by a person. 
A non-login shell is for use by a program. 


== interactive shell vs. non-interactive shell 

The shell knows whether it is interactive.
It behaves differently frorm a non-interactive shell. 
To see the interactive option, use the variable *$-* to display a list of shell options.
The option _i_ means interactive.
If you want to know what the other letters mean, run _man bash_ and look for _set_ in the _BASH BUILTIN COMMANDS_ section.

[source,shell]
---- 
[nick@host1 ~]$ echo $-
himBHs
[nick@host1 ~]$ 
----

Also, if it's got a prompt, it's an interactive shell.



== login shell vs. non-login shell

A Bash login shell is for use by a person. 
A non-login shell is for use by a program. 

run only /etc/profile

Bash non-login shells run only /etc/bashrc

One of the shell options describes whether the bash shell is a login shell. 
When you login, you get a login shell.
When a script runs, it gets its own shell but there is no login. 

If a bash shell runs a command and exits, it doesn't need to be a login shell.

[source,shell]
---- 
[nick@host1 ~]$ shopt login_shell
login_shell    	on
[nick@host1 ~]$ 
[nick@host1 ~]$ bash -c 'shopt login_shell'
login_shell    	off
[nick@host1 ~]$ 
----

Another sign of a login shell - a peculiar one - is a hyphen added to the name.

[source,shell]
---- 
[nick@host1 ~]$ echo $0
-bash
[nick@host1 ~]$ 
[nick@host1 ~]$ bash -c 'echo $0'
bash
[nick@host1 ~]$ 
----



