= use the vi editor
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 25-01-2021

The next few pages involve a lot of editing of a lot of libvirt files. 
The editor used here is vi. 
It's not everyone's favourite, and there are many alternative editors. 
But vi is installed by default in the world of Red Hat.
You can rely on it being available, so it is worth climbing vi's learning curve, with its modes, single character commands and cryptic resource file. 



help 

movement   

modes 

[source,shell]
----
----



== vi and vim 

Install vim. 

[source,shell]
----
[nick@host1 ~]$ sudo dnf install vim
[sudo] password for nick: 
Updating Subscription Management repositories.
Last metadata expiration check: 2:00:42 ago on Mon 25 Jan 2021 08:07:53 GMT.
Dependencies resolved.
====================================================================================================================================
 Package                     Architecture        Version                        Repository                                     Size
====================================================================================================================================
Installing:
 vim-enhanced                x86_64              2:8.0.1763-15.el8              rhel-8-for-x86_64-appstream-rpms              1.4 M
Installing dependencies:
 gpm-libs                    x86_64              1.20.7-15.el8                  rhel-8-for-x86_64-appstream-rpms               39 k
 vim-common                  x86_64              2:8.0.1763-15.el8              rhel-8-for-x86_64-appstream-rpms              6.3 M
 vim-filesystem              noarch              2:8.0.1763-15.el8              rhel-8-for-x86_64-appstream-rpms               48 k

Transaction Summary
====================================================================================================================================
Install  4 Packages

Total download size: 7.8 M
Installed size: 30 M
Is this ok [y/N]: 
----

alias 

[source,shell]
----
[nick@host1 ~]$ which vi
alias vi='vim'
	/usr/bin/vim
[nick@host1 ~]$ 
----

Viminfo stores state information, like command history and file marks. 

[source,shell]
----
[nick@host1 ~]$ cat .viminfo 
# This viminfo file was generated by Vim 8.0.
# You may edit it if you are careful!
...
----

== configuration 

virc and vimrc 


This file contains a few terminal control commands. 
A terminal comes with many commands for highlighting text, erasing it, moving the cursor and so on. 
Listing the _/etc/vimrc_ file leads to some odd terminal behaviour if these commands (the ones starting with `^[[`) are executed, rather than printed. 

(Is "dm" the tcap code for "delete mode"? man terminfo)

[source,bash]
----
if &term=="xterm"
     set t_Co=8
     set t_Sb=^[[4%dm
     set t_Sf=^[[3%dm
endif
----

Avoid this with -v, show nonprinting characters. 

[source,shell]
----
[nick@host1 ~]$ cat -v /etc/vimrc 
if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif
...
" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"
[nick@host1 ~]$ 
----



syntax highlighting 

[source,shell]
----
----



copy and paste 

[source,shell]
----
----



cursor column  

[source,shell]
----
----

