= use cockpit 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 14-01-2021


https://cockpit-project.org/[Cockpit] is a server management system with a web-based control panel.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/index[cockpit] 
is installed on RHEL 8 hosts, but not enabled. 

Connecting to a RHEL 8 host displays an MOTD (Message of the Day) that lets the user know cockpit is waiting to be enabled.

[source,shell]
----
workstation:~ nick$ ssh 10.0.1.45
Activate the web console with: systemctl enable --now cockpit.socket

Last login: Thu May 14 17:29:53 2020 from 10.0.1.3
[nick@host1 ~]$ 
----

== components 

* https://cockpit-project.org/guide/133/cockpit-bridge.1.html
* https://cockpit-project.org/guide/149/cockpit-ws.8.html


== enable cockpit 

Enable and start the systemd unit cockpit.socket. 
Connecting to the socket starts cockpit.service.

[source,shell]
....
[nick@host1 ~]$ systemctl status cockpit.socket
● cockpit.socket - Cockpit Web Service Socket
   Loaded: loaded (/usr/lib/systemd/system/cockpit.socket; disabled; vendor pre>
   Active: inactive (dead)
     Docs: man:cockpit-ws(8)
   Listen: [::]:9090 (Stream)
[nick@host1 ~]$ 
[nick@host1 ~]$ sudo systemctl enable --now cockpit.socket
[sudo] password for nick: 
Created symlink /etc/systemd/system/sockets.target.wants/cockpit.socket → /usr/lib/systemd/system/cockpit.socket.
[nick@host1 ~]$ 
....

After it's enabled, the MOTD message changes. 

[source,shell]
----
workstation:~ nick$ ssh 10.0.1.45
Web console: https://host.lab.example.com:9090/ or https://10.0.1.40:9090/

Last login: Thu May 14 17:29:53 2020 from 10.0.1.3
[nick@host1 ~]$ 
----


== web browser 

The service is available on port 9090, with an URL along the lines of https://10.0.1.45:9090/.

The default server config uses a self-signed certificate.

from `man remotectl`: 
The remotectl program is a tool for configuring remote access to this system. 
Currently it manages cockpit's SSL certificate.

[source,shell]
----
[nick@host1 ~]$ sudo remotectl certificate
[sudo] password for nick: 
certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
[nick@host1 ~]$ 
----

 Web browsers don't like self-signed certificates. 
 Chrome displays this warning.

[source,shell]
----
Your connection is not private
Attackers might be trying to steal your information from 10.0.1.45 (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID
----

Luckily it still offers the option to `Proceed to 10.0.1.45 (unsafe)`.

Chrome continues to cause problems behind the scenes. 
The journal may contain many _gnutls_handshake_ errors. 

[source,shell]
----
[nick@host1 ~]$ sudo journalctl -f
...
Jul 23 17:43:02 host1 cockpit-tls[14712]: cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.
----

== one cockpit, many servers 

Add a hostname onto the end of the URL. 
https://10.0.1.40:9090/@guest2.lab.example.com

First attempt shows

[source,shell]
----
Couldn't connect to the machine 
Cannot connect to an unknown machine 
Troubleshoot 
----

Troubleshoot button displays a second page.

[source,shell]
----
Add machine to dashboard 
Address 192.168.122.3
Color 
Cancel Add 
----


Servers are copied to the config file 
/etc/cockpit/machines.d/99-webui.json.


=== from cockpit to remote machines

Cockpit itself works by having a web interface that talks to the client using SSH as a transport mechanism
Instead of running a bash shell on the client, it runs cockpit-bridge.
This uses the cockpit PAM stack to authenticate and run commands, talk to dbus, etc. and sends the results back in a way the GUI can understand. 
So we need ssh ports open between the cockpit and clients.


