= exaine network settings
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 13-09-2021

Use the commands _nmcli connection show_, _nmcli device status_ and _ip addr show_ to see how the network is configured. 


== nmcli

NetworkManager manages network settings in Fedora. 
The nmcli command is a tool for using NetworkManager on the command line. 

List configured connections

!!! after messing with virtual network 

[source,shell]
....
[nick@host2]~% nmcli con
NAME           UUID                                  TYPE      DEVICE  
pubbr0         400b4e4f-b246-48f2-80fb-f096932acaf7  bridge    pubbr0  
privbr0        56d11792-11e2-4f9f-8e3a-3b7f9b54f274  bridge    privbr0 
privbr1        82bfd4d1-7cfe-4b8a-b646-efdb25e263c7  bridge    privbr1 
virbr0         9d0f763d-eaa4-47d9-b58b-e435a9d2fb0f  bridge    virbr0  
pubbr0-enp2s0  c5069310-850b-48a7-894e-607b0cc719e2  ethernet  enp2s0  
enp2s0         3d4c0a3e-c48b-35fa-a756-a1f7d2c5bf70  ethernet  --      
[nick@host2]~% 
....

Network Manager can also show a list of devices. 
This is longer because it shows devices that are not currently active. 
For instance, there is a wifi device but no wifi connection.

[source,shell]
....
[nick@host2]~% nmcli device status
DEVICE          TYPE      STATE                   CONNECTION    
pubbr0          bridge    connected               pubbr0        
privbr0         bridge    connected (externally)  privbr0       
privbr1         bridge    connected (externally)  privbr1       
virbr0          bridge    connected (externally)  virbr0        
enp2s0          ethernet  connected               pubbr0-enp2s0 
wlp3s0          wifi      disconnected            --            
p2p-dev-wlp3s0  wifi-p2p  disconnected            --            
lo              loopback  unmanaged               --            
[nick@host2]~% 
....

The IP address list command _ip addr show_ has a lot more detail, so it can be harder to spot the same information. 
This list no longer shows device _enp2s0f0_. 
Its address _192.168.1.195_ now belongs to _pubbr0_.


== ip 

[source,shell]
....
[nick@host2]~% ip -brief address show
lo               UNKNOWN        127.0.0.1/8 ::1/128 
enp2s0           UP             
wlp3s0           DOWN           
pubbr0           UP             192.168.1.135/24 2a00:23a8:4b47:fc01:a9bc:24fb:f14:d0c6/64 fdaa:bbcc:ddee:0:347f:b720:809:de2a/64 fe80::2616:c44a:d156:6e2c/64 
virbr0           DOWN           192.168.122.1/24 
privbr0          DOWN           192.168.152.1/24 2001:db8:ca2:3::1/64 
privbr1          DOWN           192.168.162.1/24 2001:db8:ca2:3::1/64 
[nick@host2]~% 
[nick@host2]~% ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master pubbr0 state UP group default qlen 1000
    link/ether 7c:10:c9:b9:1e:b0 brd ff:ff:ff:ff:ff:ff
...
7: privbr1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:00:02:01 brd ff:ff:ff:ff:ff:ff
    inet 192.168.162.1/24 brd 192.168.162.255 scope global privbr1
       valid_lft forever preferred_lft forever
    inet6 2001:db8:ca2:3::1/64 scope global tentative 
       valid_lft forever preferred_lft forever
[nick@host2]~% 
....



