= use SSH
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 10-06-2020


remote SSH login
protocol
keypair 
key-based login 
`ssh-copy-id`
SSH tunnel
/home/nick/.ssh/config 

.SSH from workstation to host1
....
.---------------.      .---------------.
|               |      |               |
|  workstation  |----->|  host1        |
|               |      |               |  
.---------------.      .---------------.
....

== access

Access covers all the components needed to one machine to contact another.
A broken network cable, strict firewall software and bad packet routing can all break access.

== authentication

The most common type of security is password authentication.
An account has a user name and a password. 

== key-based authentication 

Key-based authentication is better, but more complicated. 
The server world has a lot of key-based authentication.

Each user account has a user name, a public key and a private key.

== host key checking 

Each host also has a pair of keys. 

SSH keeps track of public keys. 
When a user connects to a new host using the SSH client, things happen in the background. 

. The SSH service on that host hands over its public key.
. The SSH client looks for the host name in its ``known_hosts`` file.
. If the host name doesn't match, the SSH client asks the user if it's safe to trust this new host. 

[source,shell]
----
The authenticity of host 'host1 (10.42.0.3)' can't be established.
ECDSA key fingerprint is SHA256:/a/PXH7tXpkjhKMjOkQHsCdikOlwW78+sNhzptfh0C4.
ECDSA key fingerprint is MD5:dd:45:41:de:34:32:dc:cd:63:a2:05:92:17:99:bf:e6.
Are you sure you want to continue connecting (yes/no)?
----

If the user agrees, the SSH client adds another line to the ``known_hosts`` file.


== connect from workstation to host1

start session. 

[source,shell]
----
workstation:~ nickh$ ssh nick@host1
The authenticity of host 'host1 (10.42.0.2)' can't be established.
ECDSA key fingerprint is SHA256:JE7mKX8bNSWPbdPUhcL9YzZeO2S4/rPBZsiOodZJCaI.
ECDSA key fingerprint is MD5:9d:3f:da:94:6e:cb:86:46:d9:63:b6:d5:4d:ae:9a:12.
Are you sure you want to continue connecting (yes/no)? 
----

agree 

[source,shell]
----
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'host1,10.42.0.2' (ECDSA) to the list of known hosts.
nick@host1's password: 
----

password-based login

[source,shell]
----
nick@host1's password: 
Last login: Sat Sep 11 10:00:06 2021 from 213.123.178.101
[nick@host1 ~]$ 
----

end session. 

[source,shell]
----
[nick@host1 ~]$ exit
logout
Connection to host1 closed.
workstation:~ nickh$
----




== the .ssh directory 


[source,shell]
----
[nick@host1 ~]# ls .ssh
ls: cannot access .ssh: No such file or directory
[nick@host1 ~]# 
----

== the known_hosts file 

If you answer yes to the ``continue connecting`` question, ssh copies the public key to its known_hosts file. 

Look at this file and you see one line containing address and public key.

[source,shell]
----
[nick@workstation ~]# cat .ssh/known_hosts 
host2 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKCNA/GEj3h0IkkxKuYB/CtgijQU/JWpbVGnGfdip9cy
[nick@workstation ~]# 
----

== check login

user authentication audit messages on the server

----
[nick@rhel9 ~]$ sudo -i
[root@rhel9 ~]# 
[root@rhel9 ~]# ausearch -m USER_AUTH | head
----
time->Tue Oct  8 07:06:13 2024
type=USER_AUTH msg=audit(1728367573.905:55): pid=943 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:local_login_t:s0-s0:c0.c1023 msg='op=PAM:authentication grantors=pam_unix acct="root" exe="/usr/bin/login" hostname=localhost.localdomain addr=? terminal=/dev/tty1 res=success'
----
time->Tue Oct  8 07:12:30 2024
type=USER_AUTH msg=audit(1728367950.230:88): pid=5044 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=pubkey acct="nick" exe="/usr/sbin/sshd" hostname=? addr=192.168.19.1 terminal=ssh res=failed'
----
time->Tue Oct  8 07:12:30 2024
type=USER_AUTH msg=audit(1728367950.234:89): pid=5044 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=pubkey acct="nick" exe="/usr/sbin/sshd" hostname=? addr=192.168.19.1 terminal=ssh res=failed'
----
[root@rhel9 ~]# 
----