= write "hello world" in assembler
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 22-02-2020


Devices get data into a computer, the CPU shifts the data around and changes it, and devices get the data back out of the computer. 
There's a world of complication behind that, which most people never see. 
The automation is so good there's no reason to tinker behind the scenes. 


It's hard to get to grips with what's going at the interface between hardware and software. 
Analogies are good for getting started, but don't really explain what's going on. 

The software kernel is like plumbing - without pipes, no water comes out of the taps. 
Except there is no tube, no water and no tap. 

The hardware is divided into CPU and memory. 
The CPU has registers. 

Learn what's going on by learning to program with assembly language. 

== hello world 

[source,armasm]
----
# https://tldp.org/HOWTO/Assembly-HOWTO/hello.html
# as hello-x86.s -o hello-x86.o
# ld hello-x86.o -o hello-x86

.text                           # section declaration

                                # we must export the entry point to the ELF linker or
    .global _start              # loader. They conventionally recognize _start as their
                                # entry point. Use ld -e foo to override the default.

_start:

                                # write our string to stdout

      movl    $len,%edx           # third argument: message length
      movl    $msg,%ecx           # second argument: pointer to message to write
      movl    $1,%ebx             # first argument: file handle (stdout)
      movl    $4,%eax             # system call number (sys_write)
      int     $0x80               # call kernel

                                # and exit

      movl    $0,%ebx             # first argument: exit code
      movl    $1,%eax             # system call number (sys_exit)
      int     $0x80               # call kernel

.data                           # section declaration

msg:
    .ascii    "Hello, world!\n"   # our dear string
    len = . - msg                 # length of our dear string.text
----

== compile hello-x86.s 

[source,armasm]
----
[root@host1 assembler]# as hello-x86.s -o hello-x86.o
[root@host1 assembler]# ld hello-x86.o -o hello-x86
[root@host1 assembler]# 
[root@host1 assembler]# ls -l  hello-x86*
-rwxr-xr-x. 1 root root 1008 Feb 23 20:21 hello-x86
-rw-r--r--. 1 root root  888 Feb 23 20:21 hello-x86.o
-rw-r--r--. 1 root root 1239 Feb 23 20:21 hello-x86.s
[root@host1 assembler]# 
----

== run hello-x86

[source,armasm]
----
[root@host1 assembler]# ./hello-x86 
Hello, world!
[root@host1 assembler]# 
----

