= check out the kernel
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 08-01-2021

Your new RHEL 8 system is running a downstream version of the Linux kernel. 
Find out a few things with these commands. 

== kernel version 

Find the version. 

Actually, the version isn't very informative. 
The release is. 

[source,shell]
----
[nick@host1 ~]$ uname --kernel-version
#1 SMP PREEMPT Tue Jun 14 11:32:10 EDT 2022
[nick@host1 ~]$ 
[nick@host1 ~]$ uname --kernel-release
5.14.0-70.17.1.el9_0.x86_64
[nick@host1 ~]$ 
----

The *5.14* part of that release, the major and minor numbers at the beginning of the line, correspond to the upstream kernel. 
The upstream 5.14 kernel is described in mind-bending detail at https://kernelnewbies.org/Linux_5.14[Kernelnewbies].

The 5.14 release is not the https://www.kernel.org/[latest release] - Fedora gets updated kernels far more frequently than RHEL does.
The RHEL kernel is kept as stable, secure and bug-free as possible.
For more information, see the article 
https://www.redhat.com/en/blog/what-latest-kernel-release-my-version-red-hat-enterprise-linux[What is the latest kernel release for my version of Red Hat Enterprise Linux?
].

The *el9_0* part shows the upstream kernel code was copied for RHEL and worked on for the 8.3 release. 


== kernel file 

The kernel file is called https://en.wikipedia.org/wiki/Vmlinux[vmlinux]. 
The /boot/ directory holds the compressed version (vmlinuz) and the name has the kernel release and machine architecture tacked on the end. 

Use the _file_ command to describe the kernel file. 

[source,shell]
----
[nick@host1 ~]$ ls /boot/vmlinuz-*
/boot/vmlinuz-0-rescue-e93d80a3bae3487db0e1856ba4aa139d  /boot/vmlinuz-5.14.0-70.17.1.el9_0.x86_64
[nick@host1 ~]$ file /boot/vmlinuz-5.14.0-70.17.1.el9_0.x86_64
/boot/vmlinuz-5.14.0-70.17.1.el9_0.x86_64: Linux kernel x86 boot executable bzImage, version 5.14.0-70.17.1.el9_0.x86_64 (mockbuild@x86-vm-07.build.eng.bos.redhat.com) #1 SMP PREEMPT Tue Jun 14 11:32:10 EDT 2022, RO-rootFS, swap_dev 0xA, Normal VGA
[nick@host1 ~]$ 
----


== kernel packages 

When the system is installed, there is only one kernel package installed. 

The first upgrade usually adds another kernel package, and the /boot directory stores two kernel files. 
The GRUB menu lets the user choose which one to boot. 


[source,shell]
----
[nick@host1 ~]$ sudo dnf list kernel
[sudo] password for nick: 
Updating Subscription Management repositories.
Last metadata expiration check: 2:39:00 ago on Mon 25 Jul 2022 20:48:03 BST.
Installed Packages
kernel.x86_64                               5.14.0-70.17.1.el9_0                                @rhel-9-for-x86_64-baseos-rpms
[nick@host1 ~]$ 
----


== kernel command line 

Grub menu line is defined here. 

[source,shell]
----
[nick@host1 ~]$ grep CMDLINE /etc/default/grub 
GRUB_CMDLINE_LINUX="crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet"
[nick@host1 ~]$ 
----

This GRUB line can be edited by the user when the machine starts up.
The command line that was actually used is here. 

The second half of this line matches the line in /etc/default/grub. 

[source,shell]
----
[nick@host1 ~]$ cat /proc/cmdline
BOOT_IMAGE=(hd0,gpt2)/vmlinuz-5.14.0-70.17.1.el9_0.x86_64 root=/dev/mapper/rhel-root ro crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet
[nick@host1 ~]$ 
----


== kernel log 

The kernel keeps its own activity log. 
This is partly because it has to keep track of its activity when the system starts, before all the regular logging things are available.
Log messages are kept in a https://en.wikipedia.org/wiki/Circular_buffer[circular buffer] im memory. 
Manual pages call this the _log buffer_ or _ring buffer_. 

While the system is running, kernel messages also appear in _/var/log/messages_. 
There is no separate _/var/log/kern.log_. 

Important messages are copied to the console. 
In the olden days, when computers had consoles and operators hanging around to see the messages, this made sense. 
These days, a server machine has no screen, let alone someone looking at it. 

View the kernel log with the _journalctl_ command. 

[source,shell]
----
[nick@host1 ~]$ journalctl --dmesg
Jul 19 08:25:33 localhost kernel: Linux version 5.14.0-70.17.1.el9_0.x86_64 (mo>
Jul 19 08:25:33 localhost kernel: The list of certified hardware and cloud inst>
Jul 19 08:25:33 localhost kernel: Command line: BOOT_IMAGE=(hd0,gpt2)/vmlinuz-5>
...
----


== kernel threads 

The kernel has its own space and runs its own tasks. 
These tasks are called threads, and are started by the kernel thread daemon. 

Use the _ps_ command to see the kernel thread daemon and its children. 

[source,shell]
----
[nick@host1 module2]# ps faux 
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           2  0.0  0.0      0     0 ?        S    10:27   0:00 [kthreadd]
root           3  0.0  0.0      0     0 ?        I<   10:27   0:00  \_ [rcu_gp]
root           4  0.0  0.0      0     0 ?        I<   10:27   0:00  \_ [rcu_par_gp]
...
----



== kernel modules 

The kernel is a modular system - it can be extended by loading modules. 
Modules can create threads, use the /proc file system, manage devices and so on.  
Many modules are loaded by the RHEL 8 kernel. 

List modules with the _lsmod_ command. 

[source,shell]
----
[nick@host1 module2]# lsmod 
Module                  Size  Used by
rfcomm                 86016  4
binfmt_misc            20480  1
tcp_diag               16384  0
...
----

