= add tasks to the role virtualization-host
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 05-01-2022

Install Red Hat libvirt packages.
Many packages are available. The most useful ones are in an environment group named _Virtualization Host_.
The _Virtualization Host_ group insstalls libguestfs, libvirt, qemu-kvm, virtio-win and about 80 supporting packages.


== find the environment group 

/Users/nhardima/Documents/red-hat/job/blog/github/articles-fedora-rpi4/modules/command-line/pages/dnf-group-view.adoc

[source,shell]
....
[nick@host1 roles]$ sudo dnf group list
[sudo] password for nick: 
Updating Subscription Management repositories.
Last metadata expiration check: 1:01:22 ago on Wed 05 Jan 2022 21:05:48 GMT.
Available Environment Groups:
   Server
   Minimal Install
   Workstation
   Custom Operating System
   Virtualization Host
Installed Environment Groups:
...
   Smart Card Support
   Console Internet Tools
   Development Tools
[nick@host1 roles]$ 
....



An environment group contains groups. 

[source,shell]
....
[nick@host1 roles]$ dnf group info 'Virtualization Host'
Not root, Subscription Management repositories not updated

This system is not registered with an entitlement server. You can use subscription-manager to register.

Red Hat Enterprise Linux 9 for x86_64 - BaseOS Beta (RPMs)                                          1.7 MB/s | 1.8 MB     00:01    
Red Hat Enterprise Linux 9 for x86_64 - AppStream Beta (RPMs)                                       5.9 MB/s | 8.9 MB     00:01    
Environment Group: Virtualization Host
 Description: Minimal virtualization host.
 Mandatory Groups:
   Base
   Core
   Standard
   Virtualization Hypervisor
   Virtualization Tools
 Optional Groups:
   Debugging Tools
   Network File System Client
   Remote Management for Linux
   Virtualization Platform
[nick@host1 roles]$ 
....


== the CLI command 

use Ansible to install the group, rather than manually installing by running commands on the CLI. 
The manual install is easy - it's one command. 
The automated install takes many more lines of code. 

[source,shell]
....
sudo dnf group install "Virtualization Host"
....




== add a task to the role

Add a task. 
Use the group ID, not the group name. 

.~/ansible/roles/virtualization-host/tasks/main.yml
[source,yaml]
....
---
# tasks file for virtualization-host
- name: Install the 'Virtualization Host' environment group
  dnf:
    name: '@virtualization-host-environment'
    state: present
....






