= sign up for a Red Hat Developer Subscription
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 31-12-2020

Sign up for a Red Hat Developer Subscription.


== check out the developer home page

* Open a web browser. 
* Head for the https://developers.redhat.com/[Red Hat Developer] site. 

The first thing to notice about this page is the number of navigation menus. 
There's one at the top, with links to other Red Hat sites. 
There's one below that, with links to site areas, and another below that organized by technology. 
And there's a list of the latest blog posts, which is a kind of navbar, and a bunch more down the bottom, in the page footer.
Sure, the http://developers.google.com/[Google developer site] has rows of portal-style portlets, but how many navbars has it got?
It's the same story at the https://developer.microsoft.com/en-gb/[Microsoft developer center] - inferior in the navbar counting department. 


== sign up to the developer network

Create an account at the https://developers.redhat.com/[Red Hat Developer] site. 

Find the link here: https://developers.redhat.com/ > Log In > Don't have an account? Create one now.

Developer registration is not the same as https://www.redhat.com/wapps/ugc/register.html[customer portal registration] - the customer portal is for purchased support. 

Decide if you want to agree to Red Hat's https://developers.redhat.com/terms-and-conditions[terms and conditions] and participate in the Red Hat Developer Program.


== VIP access

The first thing to notice after your first login is - not much changes. 
Pretty much all the content on the developer site is public.
However, your new account does give you a backstage pass to the https://access.redhat.com/[customer portal].

