= install RHEL 8 (Red Hat Enterprise Linux version 8)
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 31-12-2020

Install RHEL 8 on your workstation for free. 


== install the OS

https://developers.redhat.com/articles/faqs-no-cost-red-hat-enterprise-linux/
one (1) physical system with up to eight processor sockets. 
an unlimited number of guest virtual machines (VMs).

These bullet points loosely based on 
https://developers.redhat.com/articles/getting-red-hat-developer-subscription-what-rhel-users-need-know/

* https://developers.redhat.com/products/rhel/download[Download Red Hat Enterprise Linux Server].
* https://developers.redhat.com/rhel8/install-rhel8/[Install on bare metal]. Remember to encrypt the disk.
* Attach your system to your subscription.
* Download updates from Red Hat.



== check out the desktop

If you've only used RHEL servers, you've probably only seen the command line.
You may not have a clue what RHEL's desktop looks like. 
Think Fedora from a couple years ago - RHEL 8 is based on Fedora 28.

The Fedora and RHEL distributions are years apart because they have different reasons for being. 
Fedora gets the latest and greatest updates, while RHEL provides a stable platform.



== check SSH

Use your workstation. 

Find the IP address. 

Log in over SSH. 

When you SSH to your fresh install, you see this MOTD (Message Of The Day).
If you're on the Gnome desktop, you can only see these messages by looking at their files - ``cat /etc/motd.d/*``.

[source,shell]
----
workstation:~ nick$ ssh 10.0.1.4
Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Thu May 14 17:29:53 2020 from 10.0.1.3
[nick@rhel8 ~]$ 
----


