= create a public bridge
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 23-11-2020

Add another network to libvirt's configuration.
The config tells libvirt about bridge _pubbr0_.

== the default network 


List networks. Libvirt comes with one defined network. 

[source,shell]
....
[nick@host1 ~]$ sudo virsh net-list
[sudo] password for nick: 
 Name      State    Autostart   Persistent
--------------------------------------------
 default   active   yes         yes

[nick@host1 ~]$ 
....

== create the libvirt network pubbr0  

Add another network to libvirt's configuration.
The config tells libvirt about bridge _pubbr0_.




== write XML

This XML file defines the new network.

[source,XML]
....
<network>
  <name>pubbr0</name>
  <forward mode="bridge"/>
  <bridge name="pubbr0" />
</network>
....


The files directory holds the new XML file. 

[source,XML]
....
[nick@host1 ~]$ cd  ~/ansible/roles/virtualization-host/files
[nick@host1 files]$ 
....

Add the XML to a file. 

[source,shell]
....
[nick@host1 files]$ vim net-pubbr0.xml 
....



== manually create the libvirt network


Tell libvirt about the new configuration.

[source,shell]
....
[root@host1 libvirt]# virsh net-define net-pubbr0.xml
Network pubbr0 defined from net-pubbr0.xml

[root@host1 libvirt]# 
....

Check with the _virsh net-list_ command. 

[source,shell]
....
[root@host1 libvirt]# virsh net-list --all
 Name      State      Autostart   Persistent
----------------------------------------------
 default   active     yes         yes
 pubbr0    inactive   no          yes

[root@host1 libvirt]# 
....




== start the libvirt network

This is a temporary change. 
The network stays active until the machine turns off. 
After the next reboot, this will be inactive again. 

OLD NAMING 

[source,shell]
....
[root@host1 libvirt]# virsh net-start pubbr0
Network br0 started

[root@host1 libvirt]# 
[root@host1 libvirt]# virsh net-list --all
 Name         State    Autostart   Persistent
-----------------------------------------------
 default      active   yes         yes
 pubbr0       active   no          yes

[root@host1 libvirt]# 
....

Make the change permanent. 

[source,shell]
....
[root@host1 libvirt]# virsh net-autostart pubbr0
Network br0 marked as autostarted

[root@host1 libvirt]# 
....

Check. 

[source,shell]
....
[root@host1 libvirt]# virsh net-list --all
 Name      State    Autostart   Persistent
--------------------------------------------
 default   active   yes         yes
 pubbr0    active   yes         yes

[root@host1 libvirt]# 
....


== use ansible to create the pubbr0 network 


[source,shell]
....
vim ~/ansible/roles/virtualization-host/tasks/linux-bridge.yml
....

Add more tasks. 

[source,YAML]
....
# https://docs.ansible.com/ansible/latest/collections/community/libvirt/virt_net_module.html
#

- name: install RPM packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3-libvirt
    - python3-lxml

# Define a new network
- community.libvirt.virt_net:
    command: define
    name: pubbr0
    xml: '{{ lookup("file", "net-pubbr0.xml") }}'

# Start a network
- community.libvirt.virt_net:
    command: create
    name: pubbr0

# Ensure that a network is active (needs to be defined and built first)
- community.libvirt.virt_net:
    state: active
    name: pubbr0

# Ensure that a given network will be started at boot
- community.libvirt.virt_net:
    autostart: yes
    name: pubbr0
....


Check. 

[source,shell]
....
[nick@host1 ansible]$ sudo virsh net-list --all
 Name      State    Autostart   Persistent
--------------------------------------------
 default   active   yes         yes
 pubbr0    active   yes         yes

[nick@host1 ansible]$ 
....



== delete libvirt's pubbr0 

If it's not right, remove the new config with _virsh net-undefine_.

[source,shell]
....
[root@host1 libvirt]# virsh net-undefine pubbr0
Network pubbr0 has been undefined

[root@host1 libvirt]# 
....
