= create a virtual machine, then delete it
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 11-01-2021

Create a VM, then destroy it. 
This new virtual machine exists inside the physical host machine. 
It can talk to the Internet via the host's ethernet interface. 

Use the golden image method of installation. 
Instead of installing packages and configuring the system using a kickstart file, copy the KVM file. 


.physical machine and virtual machine 
....
.--------------------.
|                    |
|  host1             |
|                    |   
|   +------------+   |    
|   |            |   |  
|   |  myfirstvm |---+--> Internet
|   |            |   |   
|   +------------+   |  
.--------------------.  
....



== create a storage volume 

A qcow2 file was downloaded from Red Hat's portal. 
Copy this to use for our new VM. 

[source,shell]
----
[nick@host1 ~]$ sudo cp /var/lib/libvirt/images/rhel-8.2-x86_64-kvm.qcow2 /var/lib/libvirt/images/myfirstvm.qcow2
[nick@host1 ~]$ 
----

== refresh the images pool

Sometimes libvirt takes its time picking up on new files. 
Make sure libvirt notices the new volume by refreshing the pool.

[source,shell]
----
[nick@host1 ~]$ sudo virsh pool-refresh images
Pool images refreshed

[nick@host1 ~]$ 
----

== create a virtual machine 

Create a VM using a ready-made disk image (guest-images/myfirstvm.qcow2). This is not the same as using an install ISO - the OS is already installed. 

A new VM can be created using a command like ``virsh define myfirstvm.xml``, 
similar to the way a storage pool can be created using ``virsh pool-define storage-pool.xml``.
But the XML configuration that defines a virtual machine is complicated. 
It's easier to use the ``virt-install`` command to do the hard work. 

This ``virt-install`` command creates a virtual machine.
The ``--os-variant`` option sets some values, including 2 CPUs and 1536 MB memory.

[source,shell]
----
sudo virt-install \
  --name myfirstvm \
  --disk vol=images/myfirstvm.qcow2  \
  --os-variant rhel8.2 \
  --noautoconsole  \
  --import
----

This command creates a _guest domain_. In https://libvirt.org/goals.html[libvirt terminology], this command creates a domain on the node, which translates as a new guest machine running on the host machine.  
 

[source,shell]
----
[nick@host1 ~]# sudo virt-install   --name myfirstvm   --disk vol=images/myfirstvm.qcow2   --os-variant rhel8.2   --noautoconsole    --import
Using rhel8.2 default --memory 1536

Starting install...
Domain creation completed.
[nick@host1 ~]#
----


== use the console 

Connect to the console with the command ``virsh console myfirstvm``.

It may take a few seconds for boot-up to finish. 
The login prompt may not appear until you hit the ``Enter`` key. 

The hostname is _localhost_. 
The ``--name`` option in the virt-install command doesn't change the hostname, or indeed anything in the KVM image. 

[source,shell]
----
[root@host1 ~]$ virsh console myfirstvm
Connected to domain myfirstvm
Escape character is ^]
(Enter)
Red Hat Enterprise Linux 8.2 (Ootpa)
Kernel 4.18.0-193.el8.x86_64 on an x86_64

Activate the web console with: systemctl enable --now cockpit.socket

localhost login: 
----

We can't log in, because no root password is set. 

Disconnect from the console with this key combination. 
kbd:[Ctrl + ++]++ ] 

[source,shell]
----
myfirstvm login:  ^]
[root@host1 ~]$ 
----


== stop the VM

Stop the new VM with the command ``virsh shutdown myfirstvm``. 
This is a graceful shutdown, like running ``systemctl poweroff``.

If you want to pull the plug, use ``virsh destroy myfirstvm``.

[source,shell]
....
[root@host1 ~]$ virsh shutdown myfirstvm
Domain myfirstvm is being shutdown

[root@host1 ~]$ 
[root@host1 ~]$ virsh list --all
 Id    Name                           State
----------------------------------------------------
 -     myfirstvm                      shut off

[root@host1 ~]$ 
....


== restart the VM

Restart the new VM with the command ``virsh start myfirstvm``.

This ``virsh start`` command runs a huge ``qemu-kvm`` command with dozens of options. 
You can see it by running ``ps -fwwwC qemu-kvm``.

[source,shell]
....
[root@host1 ~]$ virsh start myfirstvm
Domain myfirstvm started

[root@host1 ~]$ 
[root@host1 ~]$ virsh list
 Id    Name                           State
----------------------------------------------------
 1     myfirstvm                      running

[root@host1 ~]$ 
....




== delete the VM

Delete the new VM with the command  ``virsh destroy myfirstvm``.

Power off the machine. 
Don't bother to shut it down gracefully. 

[source,shell]
....
[root@host1 ~]$ virsh destroy myfirstvm
Domain myfirstvm destroyed

[root@host1 ~]$ 
....


Delete the new machine. 
The opposite of define is undefine. 
Remove its configuration and the new volume file. 

[source,shell]
....
[root@host1 ~]# virsh undefine myfirstvm
Domain myfirstvm has been undefined
Volume 'vda'(/var/lib/libvirt/images/myfirstvm.qcow2) removed.

[root@host1 ~]# 
[root@host1 ~]$ virsh list --all
 Id    Name                           State
----------------------------------------------------

[root@host1 ~]$ 
....

This command does not delete the volume file. 
We could use the option --remove-all-storage to clean up this file, but we need the file for creating an XML file. 

== create an XML configuration file

Run the virt-install command again, this time with the extra option --print-xml. 

[source,shell]
----
sudo virt-install \
  --name myfirstvm \
  --disk vol=images/myfirstvm.qcow2  \
  --os-variant rhel8.2 \
  --noautoconsole  \
  --import  \
  --print-xml  \
   > ~/ansible/roles/virtualization-host/tests/vm-myfirstvm.xml
----

Instead of configuring a new VM, this command now displays configuration. 
The configuration is in an XML document.

Copy the XML to a file, ready for ansible to use. 

[source,shell]
----
[nick@host1 ~]$ sudo virt-install   --name myfirstvm   --disk vol=images/myfirstvm.qcow2    --os-variant rhel8.2   --noautoconsole    --import    --print-xml    > ~/ansible/roles/virtualization-host/tests/vm-myfirstvm.xml
[nick@host1 ~]$ 
----

View the XML. 
This XML describes everything libvirt needs to create a VM. 

[source,shell]
....
[nick@host1 ~]$ cat ~/ansible/roles/virtualization-host/tests/vm-myfirstvm.xml
<domain type="kvm">
  <name>myfirstvm</name>
  <uuid>d170b87b-9324-4cc4-a197-dc9f9080ef7b</uuid>
...
    </rng>
  </devices>
</domain>

[nick@host1 ~]$ 
....



== use ansible to create the VM 

This is a test of everything done so far.
Create a new playbook in the tests directory.

[source,shell]
....
[nick@host1 ~]$ vim ~/ansible/roles/virtualization-host/tests/vm-myfirstvm.yml
....

Write the playbook. 

[source,YAML]
....
---
# This playbook expects these two files to already exist. 
# rhel-8.2-x86_64-kvm.qcow2 - storage volume file downloaded from Red Hat
# vm-myfirstvm.xml - configuration for the virtual machine
#
# The playbook creates these resources, then deletes them.
# myfirstvm - a libvirt domain
# myfirstvm.qcow2 - a copy of the rhel file
#
- name: a new guest virtual machine 
  hosts: localhost 
  gather_facts: no
  become: yes

  tasks: 

  - name: copy the downloaded KVM image file
    ansible.builtin.copy:
      src: /var/lib/libvirt/images/rhel-8.2-x86_64-kvm.qcow2
      dest: /var/lib/libvirt/images/myfirstvm.qcow2

  - name: update pool catalog
    community.libvirt.virt_pool:
      name: images
      command: refresh

  # return code is 1 if the volume is missing
  - name: check
    ansible.builtin.command: 
      cmd: virsh vol-info myfirstvm.qcow2 images
    register: r_vol_info

  - name: display 
    debug:
      var: r_vol_info['stdout_lines']


  # define and launch the guest
  - name: define vm
    community.libvirt.virt:
      command: define
      xml: "{{ lookup('file', 'vm-myfirstvm.xml') }}"

  - name: start vm
    community.libvirt.virt:
      name: myfirstvm
      state: running

  - name: get domain info
    community.libvirt.virt:
      name: myfirstvm
      command: info
    register: r_domain_info

  - name: display domain info
    debug:
      var: r_domain_info['myfirstvm']


  # clean up
  - name: pull the plug
    community.libvirt.virt:
      name: myfirstvm
      state: destroyed

  - name: delete libvirt's domain
    community.libvirt.virt:
      name: myfirstvm
      command: undefine

  #https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-storage_volume_commands-deleting_storage_volumes
  - name: delete libvirt's volume
    command: 
      cmd: virsh vol-delete myfirstvm.qcow2 images
....

Run. 


[source,shell]
....
[nick@host1 ~]$ cd ~/ansible/
[nick@host1 ansible]$ 
[nick@host1 ansible]$  ansible-playbook --ask-become-pass roles/virtualization-host/tests/myfirstvm.yml
BECOME password: 
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [set up virtualization-host] ***********************************************

TASK [define vm] ****************************************************************
changed: [localhost]

TASK [start vm] *****************************************************************
changed: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

[nick@host1 ansible]$ 
....

This is idempotent. 
Run the playbook again and that _start vm_ task says _OK_, not changed. 

Check.

[source,shell]
....
[nick@host1 ansible]$ sudo virsh list --all
[sudo] password for nick: 
 Id   Name        State
---------------------------
 1    myfirstvm   running

[nick@host1 ansible]$ 
....



== delete using ansible 


[source,shell]
....
[nick@host1 ansible]$ vim roles/virtualization-host/tests/myfirstvm.yml
....

Add more tasks to the playbook. 

There is no "deleted" state. 
Use "command" instead. 

[source,YAML]
....
  - name: pull the plug
    community.libvirt.virt:
      name: myfirstvm
      state: destroyed

  - name: delete
    community.libvirt.virt:
      name: myfirstvm
      command: undefine
....

Run. 

[source,shell]
....
[nick@host1 ansible]$  ansible-playbook --ask-become-pass roles/virtualization-host/tests/myfirstvm.yml
BECOME password: 
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [set up virtualization-host] ***********************************************

TASK [define vm] ****************************************************************
ok: [localhost]

TASK [start vm] *****************************************************************
ok: [localhost]

TASK [pull the plug] ************************************************************
changed: [localhost]

TASK [delete] *******************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

[nick@host1 ansible]$ 
....



