= use the vim editor
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 25-01-2021

Vi was written way back in the 1970s.
It was a visual extension to the _ex_ line-based text editor.
Vi has been improved, copied and used by sysadmins ever since. 
The vi editor is installed by default on every RHEL machine.

If you want the frustrating experience of 1970s text editing, run `ex`.
When you give up on trying to get anything done, read chapter 5, https://www.oreilly.com/library/view/learning-the-vi/9780596529833/ch05.html[Introducing the ex Editor], in O'Reilly's book https://www.oreilly.com/library/view/learning-the-vi/9780596529833/[Learning the vi and Vim Editors].

Vi was forked and upgraded to make a new generation of text editors. 
In the 1990s https://en.wikipedia.org/wiki/Vim_(text_editor)[vim] appeared. 
Vim was itself used to create https://neovim.io/[neovim].

https://vimawesome.com/[Many vim plugins] are available, to help software coders with syntax checking, color scheme, code snippets, and other features. 
Plugins can change vim from a text editor to a development environment. 

If vim isn't already installed, it can be added to RHEL with the command  `sudo dnf install vim`.

== learn vim 

* book https://www.apress.com/gp/book/9781484202517[Pro Vim]
* wiki https://vim.fandom.com/wiki/Vim_Tips_Wiki
* vim help files https://vimhelp.org/
* tutorials on the web https://danielmiessler.com/study/vim/, https://www.openvim.com/, 
* tutorial in vim `vimtutor`



== config files


=== /etc/vimrc

This file contains dozens of vim settings. 
All vim users on the system get these settings. 


The _/etc/vimrc_ file contains text formatting instructions for the terminal, with strange-looking key combinations like `^[[4%dm`. 
These combinations tell the terminal to do things like highlight text, erase it, and move the cursor. 

[source,bash]
----
if &term=="xterm"
     set t_Co=8
     set t_Sb=^[[4%dm
     set t_Sf=^[[3%dm
endif
----

Displaying the _/etc/vimrc_ file with the command `cat /etc/vimrc` leads to some odd terminal behaviour.
These commands are executed, rather than printed. 
Avoid this with -v (show nonprinting characters). 

[source,shell]
----
[nick@host1 ~]$ cat -v /etc/vimrc 
" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif
...
if filereadable("/etc/vimrc.local")
  source /etc/vimrc.local
endif
[nick@host1 ~]$ 
----


=== ~/.vimrc 

Extra vim config important to the user is stored in this config file. 
This one-liner makes it easier to edit YAML files. 

[source,shell]
----
[nick@host1 ~]$ cat .vimrc
autocmd FileType yaml setlocal ai sw=2 ts=2 et cuc
[nick@host1 ~]$ 
----

A serious vim user may have a .vimrc file that is hundreds of lines long. 



=== ~/.vim/

Vim fans store their plugins in this directory. 


=== ~/.viminfo 

Viminfo stores state information, like command history and file marks. 

[source,shell]
----
[nick@host1 ~]$ cat .viminfo 
# This viminfo file was generated by Vim 8.0.
# You may edit it if you are careful!
...
----

=== vim scripts 

Vim treats different types of file in different ways. 
Vim scripts make this work. 
the /usr/share/vim/ directory contains many vim scripts, organized in subdirectories like these. 

* color scheme: /usr/share/vim/vim82/colors/
* language syntax: /usr/share/vim/vim82/syntax/
* auto-indentation behaviour: /usr/share/vim/vim82/indent/

Open a few types of file, to see the syntax highlighting. 
These are important system files, so open them read-only for safety. 

[source,shell]
----
# Vim script
vim -R /etc/vimrc
# Python
vim -R /usr/lib/python3.9/site-packages/dnf/base.py
# Bash 
vim -R /usr/share/vim/vim82/macros/less.sh
----


