= install Ansible's RPM package
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 05-01-2022

Install Red Hat Ansible Core.



== the ansible control node and managed nodes

Host1 becomes a control node for initial configuration.
Later, a VM will be the control node. 


== install ansible 

Install ansible.

[source,shell]
----
sudo dnf install ansible-core
----

Installing Ansible doesn't install Python. 
RHEL 9 already has its own copy of Python (the executable is /usr/libexec/platform-python).
Ansible uses the OS's python.

[source,shell]
----
[nick@host1 ~]$ sudo dnf install ansible-core
Updating Subscription Management repositories.
Last metadata expiration check: 2:25:49 ago on Tue 04 Jan 2022 18:42:06 GMT.
Dependencies resolved.
================================================================================
 Package      Arch   Version        Repository                             Size
================================================================================
Installing:
 ansible-core x86_64 2.12.0-1.el9   rhel-9-for-x86_64-appstream-beta-rpms 2.4 M
Installing dependencies:
 git          x86_64 2.31.1-2.el9.2 rhel-9-for-x86_64-appstream-beta-rpms 128 k
 git-core     x86_64 2.31.1-2.el9.2 rhel-9-for-x86_64-appstream-beta-rpms 3.6 M
 git-core-doc noarch 2.31.1-2.el9.2 rhel-9-for-x86_64-appstream-beta-rpms 2.5 M
 perl-Error   noarch 1:0.17029-7.el9
                                    rhel-9-for-x86_64-appstream-beta-rpms  46 k
 perl-Git     noarch 2.31.1-2.el9.2 rhel-9-for-x86_64-appstream-beta-rpms  44 k
 perl-TermReadKey
              x86_64 2.38-11.el9    rhel-9-for-x86_64-appstream-beta-rpms  40 k
 perl-lib     x86_64 0.65-479.el9   rhel-9-for-x86_64-appstream-beta-rpms  24 k
 python3-babel
              noarch 2.9.1-2.el9    rhel-9-for-x86_64-appstream-beta-rpms 6.0 M
 python3-cffi x86_64 1.14.5-4.el9   rhel-9-for-x86_64-appstream-beta-rpms 257 k
 python3-cryptography
              x86_64 3.4.7-5.el9    rhel-9-for-x86_64-appstream-beta-rpms 784 k
 python3-jinja2
              noarch 2.11.3-4.el9   rhel-9-for-x86_64-appstream-beta-rpms 253 k
 python3-markupsafe
              x86_64 1.1.1-12.el9   rhel-9-for-x86_64-appstream-beta-rpms  38 k
 python3-packaging
              noarch 20.9-4.el9     rhel-9-for-x86_64-appstream-beta-rpms  81 k
 python3-ply  noarch 3.11-13.el9    rhel-9-for-x86_64-appstream-beta-rpms 110 k
 python3-pycparser
              noarch 2.20-5.el9     rhel-9-for-x86_64-appstream-beta-rpms 139 k
 python3-pyparsing
              noarch 2.4.7-7.1.el9  rhel-9-for-x86_64-baseos-beta-rpms    154 k
 python3-pytz noarch 2021.1-4.el9   rhel-9-for-x86_64-appstream-beta-rpms  56 k
 python3-resolvelib
              noarch 0.5.4-5.el9    rhel-9-for-x86_64-appstream-beta-rpms  38 k
 sshpass      x86_64 1.09-4.el9     rhel-9-for-x86_64-appstream-beta-rpms  29 k

Transaction Summary
================================================================================
Install  20 Packages

Total download size: 17 M
Installed size: 76 M
Is this ok [y/N]: 
----

The first RPM install is also the first GPG key install. 
The security team uses release keys and auxiliary keys to sign RPM packages. 
The DNF configuration tells DNF to install these keys and use them to check all downloaded RPM packages before installing them. 

[source,shell]
----
Importing GPG key 0xF21541EB:
 Userid     : "Red Hat, Inc. (beta key 2) <security@redhat.com>"
 Fingerprint: B08B 659E E86A F623 BC90 E8DB 938A 80CA F215 41EB
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
Is this ok [y/N]: 
----

Check your work by displaying Ansible's default configuration.

[source,shell]
----
[nick@host1 ~]$ ansible --version
ansible [core 2.12.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nick/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/nick/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.9 (main, Nov 16 2021, 00:00:00) [GCC 11.2.1 20211019 (Red Hat 11.2.1-6)]
  jinja version = 2.11.3
  libyaml = True
[nick@host1 ~]$ 
----


== examine the new system 

This package adds nearly 2,000 files to the file system. 
Older versions of Ansible installed a vast number of files - over 17,000. 

[source,shell]
----
[nick@host1 ~]$ rpm -ql ansible-core | wc -l
1776
[nick@host1 ~]$ 
----



== remove ansible-core

uninstall 
delete
