= second stage boot loader (GRUB)
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 18-08-2020

== GRUB  

There are a few GRUB programs, run in this sequence.

* The BIOS loads a tiny 
https://www.gnu.org/software/grub/manual/grub/html_node/Images.html[boot.img] file from the MBR (the very start of the disk). This boot image is a program that does nothing except kick off the next GRUB program. There isn't enough room in the MBR to store anything interesting. 
* The second program is a much bigger *core image*. This provides the framework to search for the _/boot/grub2_ directory and load the rest of GRUB from there. The core.img file is built from kernel module code by a utility called grub2-mkimage. 
* The _/boot/grub2_ directory contains a lot of code and configuration files. The core.img program runs the _/boot/grub2/i386-pc/normal.mod_ module, and that sets up everything required to complete the booting process. These modules display the boot menu, handle interaction, load kernel files into memory, and start the kernel stage. 


=== partition 

The core image is stored in its own small disk partition, called the https://en.wikipedia.org/wiki/BIOS_boot_partition[BIOS boot partition].
In this output, it's the Number 1 partition, marked with the flag _bios_grub_.


[source,shell]
----
[nick@guest3 ~]$ sudo parted -l
[sudo] password for nick: 
Model: Virtio Block Device (virtblk)
Disk /dev/vda: 12.9GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name     Flags
 1      1049kB  2097kB  1049kB               primary  bios_grub
 2      2097kB  107MB   105MB   fat16        primary  boot, esp
 3      107MB   12.9GB  12.8GB  xfs          primary


[nick@guest3 ~]$ 
----


=== config 

The /boot/efi/EFI/redhat/grub.cfg file, which GRUB previously used on UEFI systems, is now a symbolic link to the /boot/grub2/grub.cfg file.


== kernel 

The /boot/ directory contains the current kernel and a few older ones, in case the new kernel has issues. 

Each kernel version has a few files. 
* https://en.wikipedia.org/wiki/Vmlinux[vmlinuz], the kernel.
* https://en.wikipedia.org/wiki/Initial_ramdisk[initrd (initial ramdisk)]. This contains drivers and other files the kernel needs.
* https://en.wikipedia.org/wiki/System.map[System.map], a look-up table that maps symbols to memory locations.
* config, the configuration file used to build the kernel. 

The kernel release name is rather long. 

[source,shell]
----
[nick@guest1 ~]$ uname -r
4.18.0-193.6.3.el8_2.x86_64
[nick@guest1 ~]$ 
[nick@guest1 ~]$ KERNEL_RELEASE=$(uname -r)
[nick@guest1 ~]$ ls /boot/*$KERNEL_RELEASE*
/boot/config-4.18.0-193.6.3.el8_2.x86_64              
/boot/System.map-4.18.0-193.6.3.el8_2.x86_64
/boot/initramfs-4.18.0-193.6.3.el8_2.x86_64.img       
/boot/vmlinuz-4.18.0-193.6.3.el8_2.x86_64
/boot/initramfs-4.18.0-193.6.3.el8_2.x86_64kdump.img
[nick@guest1 ~]$ 
[nick@guest1 ~]$ head /boot/config-$KERNEL_RELEASE
#
# Automatically generated file; DO NOT EDIT.
# Linux/x86_64 4.18.0-193.6.3.el8_2.x86_64 Kernel Configuration
#

#
# Compiler: gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
#
CONFIG_64BIT=y
CONFIG_X86_64=y
[nick@guest1 ~]$ 
----


GRUB configuration defines a default kernel to run, if the user doesn't choose during the start-up process.
The default kernel is usually the latest one.
The last entry in this list is the newest. 

[source,shell]
----
[nick@guest1 ~]$ ls -lart /boot/vmlinuz-*
-rwxr-xr-x. 1 root root 8913760 Mar 27 14:48 /boot/vmlinuz-4.18.0-193.el8.x86_64
-rwxr-xr-x. 1 root root 8913760 Apr 23 06:16 /boot/vmlinuz-0-rescue-92b1f5dc7a31458b86b8af1f768ef406
-rwxr-xr-x. 1 root root 8917856 Jun  1 21:40 /boot/vmlinuz-4.18.0-193.6.3.el8_2.x86_64
-rwxr-xr-x. 1 root root 8917856 Jul  4 09:50 /boot/vmlinuz-0-rescue-5b3bf4e5791e42a283a85f36070e5fcc
-rwxr-xr-x. 1 root root 8917856 Jul 14 00:27 /boot/vmlinuz-4.18.0-193.13.2.el8_2.x86_64
[nick@guest1 ~]$ 
----

The grubby command manages configuration. 

[source,shell]
----
[nick@guest1 ~]$ sudo grubby --info=/boot/vmlinuz-$KERNEL_RELEASE
[sudo] password for nick: 
index=3
kernel="/boot/vmlinuz-4.18.0-193.6.3.el8_2.x86_64"
args="ro console=ttyS0 console=ttyS0,115200n8 no_timer_check net.ifnames=0 crashkernel=auto $tuned_params"
root="UUID=3cd0d4ca-93f6-423b-a469-70ab2b10b667"
initrd="/boot/initramfs-4.18.0-193.6.3.el8_2.x86_64.img $tuned_initrd"
title="Red Hat Enterprise Linux (4.18.0-193.6.3.el8_2.x86_64) 8.2 (Ootpa)"
id="5b3bf4e5791e42a283a85f36070e5fcc-4.18.0-193.6.3.el8_2.x86_64"
[nick@guest1 ~]$ 
----


The grub2-reboot command can tell GRUB which kernel to use on the next reboot. 

Check the current release, list options and choose an earlier kernel release.

[source,shell]
----
[nick@guest1 ~]$ uname -r
4.18.0-193.13.2.el8_2.x86_64
[nick@guest1 ~]$ 
[nick@guest1 ~]$ sudo grubby --info=ALL | grep title
title="Red Hat Enterprise Linux (4.18.0-193.el8.x86_64) 8.2 (Ootpa)"
title="Red Hat Enterprise Linux (0-rescue-92b1f5dc7a31458b86b8af1f768ef406) 8.2 (Ootpa)"
title="Red Hat Enterprise Linux (4.18.0-193.13.2.el8_2.x86_64) 8.2 (Ootpa)"
title="Red Hat Enterprise Linux (4.18.0-193.6.3.el8_2.x86_64) 8.2 (Ootpa)"
title="Red Hat Enterprise Linux (0-rescue-5b3bf4e5791e42a283a85f36070e5fcc) 8.2 (Ootpa)"
[nick@guest1 ~]$ 
[nick@guest1 ~]$ sudo grub2-reboot "Red Hat Enterprise Linux (4.18.0-193.6.3.el8_2.x86_64) 8.2 (Ootpa)"
[nick@guest1 ~]$ 
----

Use that kernel. 

[source,shell]
----
[nick@guest1 ~]$ sudo systemctl reboot 
Connection to guest1.lab.example.com closed by remote host.
Connection to guest1.lab.example.com closed.
[nick@host1 ~]$ 
[nick@host1 ~]$ ssh nick@guest1.lab.example.com
...
[nick@guest1 ~]$ uname -r
4.18.0-193.6.3.el8_2.x86_64
[nick@guest1 ~]$ 
----

Return to the default. 

[source,shell]
----
[nick@guest1 ~]$ sudo grub2-reboot "Red Hat Enterprise Linux (4.18.0-193.13.2.el8_2.x86_64) 8.2 (Ootpa)"
[sudo] password for nick: 
[nick@guest1 ~]$ 
[nick@guest1 ~]$ sudo systemctl reboot
Connection to guest1.lab.example.com closed by remote host.
Connection to guest1.lab.example.com closed.
[nick@host1 ~]$ 
[nick@host1 ~]$ ssh nick@guest1.lab.example.com
...
[nick@guest1 ~]$ uname -r
4.18.0-193.13.2.el8_2.x86_64
[nick@guest1 ~]$ 
----

