= install the 'Virtualization Host' environment group
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 12-01-2021




== the DNF environment group Virtualization Host  

After install, the word _Available_ changes to _Installed_.

[source,shell]
....
[nick@host2 ~]$  sudo dnf group list 'Virtualization Host'
[sudo] password for nick: 
Updating Subscription Management repositories.
Last metadata expiration check: 2:29:23 ago on Tue 26 Jul 2022 15:00:06 BST.
Available Environment Groups:
   Virtualization Host
[nick@host2 ~]$ 
....

Subgroups

[source,shell]
....
[nick@host2 ~]$  sudo dnf group info 'Virtualization Host'
Updating Subscription Management repositories.
Last metadata expiration check: 2:30:23 ago on Tue 26 Jul 2022 15:00:06 BST.
Environment Group: Virtualization Host
 Description: Minimal virtualization host.
 Mandatory Groups:
   Base
   Core
   Standard
   Virtualization Hypervisor
   Virtualization Tools
 Optional Groups:
   Debugging Tools
   Network File System Client
   Remote Management for Linux
   Virtualization Platform
[nick@host2 ~]$ 
....




== install the group


[source,shell]
....
[nick@host2 ~]$ sudo dnf group install 'Virtualization Host'
Updating Subscription Management repositories.
Last metadata expiration check: 2:34:31 ago on Tue 26 Jul 2022 15:00:06 BST.
Dependencies resolved.
================================================================================
 Package      Arch   Version             Repository                        Size
================================================================================
Installing group/module packages:
 libguestfs   x86_64 1:1.46.1-3.el9_0    rhel-9-for-x86_64-appstream-rpms 1.1 M
 libvirt      x86_64 8.0.0-8.1.el9_0     rhel-9-for-x86_64-appstream-rpms  15 k
 qemu-kvm     x86_64 17:6.2.0-11.el9_0.3 rhel-9-for-x86_64-appstream-rpms  67 k
...
 systemd-container
              x86_64 250-6.el9_0         rhel-9-for-x86_64-baseos-rpms    553 k
 usbredir     x86_64 0.12.0-2.el9        rhel-9-for-x86_64-appstream-rpms  53 k
 virtiofsd    x86_64 1.1.0-4.el9_0       rhel-9-for-x86_64-appstream-rpms 771 k
Installing Environment Groups:
 Virtualization Host
                                                                               
Installing Groups:
 Base                                                                          
 Core                                                                          
 Standard                                                                      
 Virtualization Hypervisor
                                                                               
 Virtualization Tools
                                                                               

Transaction Summary
================================================================================
Install  80 Packages

Total size: 258 M
Installed size: 1.0 G
Is this ok [y/N]: 
....


== remove the group 

Remove all 80 packages. 

[source,shell]
....
[nick@host2 ~]$ sudo dnf group remove 'Virtualization Host'
...
Removing Environment Groups:
 Virtualization Host
                                                                               
Removing Groups:
 Virtualization Tools
                                                                               
 Base                                                                          
 Virtualization Hypervisor
                                                                               

Transaction Summary
================================================================================
Remove  80 Packages

Freed space: 1.0 G
Is this ok [y/N]: 
....



== maintenance updates

