= create another libvirt private bridge
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 23-11-2020


Create a private bridge named _privbr1_.
Create a libvirt network named _private1_.


== the theory 

Guests are created in a private network.
Guests join this new _private1_ network and talk to each other.

A gateway is attached to both bridges. 
This is the only way to communicate with guests in the _private1_ network.


.libvirt networks 
....
.----------------------------.
|                            |
|  host1                     |
|                            |   
|   +----------+             |    
|   | gateway  |             |
|   | guest2   |             |  
|   |          +--> private0 |  
|   |          |             |  
|   |          +--> private1 |   
|   +----------+             |
.----------------------------.  
....

All guests can join this new _private1_ network and talk to each other.

.bridges 
....
.---------------------------.
|                           |
|  host1                    |
|                           |   
|   +----------+            |    
|   | gateway  |            |
|   | guest2   |            |  
|   |          |            |  
|   |  enp1s0  +--> privbr0 | 
|   |          |            |  
|   |  enp2s0  +--> privbr1 |   
|   +----------+            |
.---------------------------.  
....




== create the libvirt network private1

=== create an XML file

Create an XML file defining the interface. 

Run the command ``vim net-private1.xml``.

Add XML. 

This markup is based on the 
https://libvirt.org/formatnetwork.html#examplesPrivate[libvirt example].

.net-private1.xml
[source,XML]
----
<network>
  <name>private1</name>
  <bridge name="privbr1"/>
  <mac address='52:54:00:02:00:01'/>
  <domain name='private1.example.com' localOnly='yes'/>
  <ip address="192.168.162.1" netmask="255.255.255.0">
    <dhcp>
      <range start="192.168.162.2" end="192.168.162.254"/>
    </dhcp>
  </ip>
  <ip family="ipv6" address="2001:db8:ca2:3::1" prefix="64"/>
</network>
----


=== check the file with xmllint 

Check your work with xmllint. 
This is a tool for detecting errors in XML files. 

No news is good news. 

[source,shell]
----
[root@host1 libvirt]# xmllint --noout  ./net-private1.xml 
[root@host1 libvirt]# 
----

xmllint lists any problems it finds, and attempts to show where the problems are.   
In this case, a copy'n'paste missed the last line (_</network>_). 
Line 10 is a whole lot of nothing. 

[source,shell]
----
[root@host1 libvirt]# xmllint --noout net-private1-broken.xml 
net-private1-broken.xml:10: parser error : Premature end of data in tag network line 1

^
[root@host1 libvirt]# 
----


=== hand it to libvirt 

Create the new network. Run ``sudo virsh net-define net-private1.xml``

[source,shell]
....
[root@host1 libvirt]# virsh net-define net-private1.xml
Network private1 defined from net-private1.xml

[root@host1 libvirt]#  
....

The network is created and is persistent - it will still exist across reboots. 
But it is not in use.

[source,shell]
.... 
[root@host1 libvirt]# virsh net-list --all
 Name      State      Autostart   Persistent
----------------------------------------------
 default   active     yes         yes
 private1  inactive   no          yes

[root@host1 libvirt]# 
....

=== start the new network 

Set the new network to start on boot, and start it now. 

[source,shell]
....
[root@host1 libvirt]# virsh net-start private1
Network private1 started

[root@host1 libvirt]# virsh net-autostart private1
Network private1 marked as autostarted

[root@host1 libvirt]# 
[root@host1 libvirt]# virsh net-list --all
 Name      State    Autostart   Persistent
--------------------------------------------
 default   active   yes         yes
 private1  active   yes         yes

[root@host1 libvirt]# 
....


=== check interfaces 

Libvirt creates a new bridge. 
Two new interfaces appear on the host, *privbr1* and *privbr1-nic*.
There is no need to create a bridge manually using ``nmcli connection``, ``ip link`` or ``bridge link`` commands. 

[source,shell]
....
[nick@host1 ~]$ ip addr show
...
8: privbr1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:23:0f:f9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.152.1/24 brd 192.168.152.255 scope global privbr1
       valid_lft forever preferred_lft forever
    inet6 2001:db8:ca2:3::1/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe23:ff9/64 scope link 
       valid_lft forever preferred_lft forever
9: privbr1-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master privbr1 state DOWN group default qlen 1000
    link/ether 52:54:00:23:0f:f9 brd ff:ff:ff:ff:ff:ff
....


=== loosen permissions 

Only required for non-root? 

libvirt uses qemu to do the hard work, and qemu uses ACLs (Access Control Lists). 
It won't let anyone use the new _privbr1_ interface. 
Let the VMs use the new network by copying permissions for the current _virbr1_ interface. 
Permissions for _virbr1_ are set in qemu's config file. 

[source,shell]
....
[nick@host1 ~]$ cat /etc/qemu-kvm/bridge.conf 
allow virbr1
[nick@host1 ~]$ 
....

Add a similar line for the new bridge interface. 
[source,shell]
....
[nick@host1 ~]$ sudo sh -c 'echo "allow privbr1" >> /etc/qemu-kvm/bridge.conf'
[nick@host1 ~]$ 
....



