= examine the OS
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 13-01-2021

RHEL includes an OS plus many applications to make the user's life easier. 
It's hard to tell where the OS ends and the applications begin. 
So what exactly is an OS? 

== what is an OS 

It's easier to define what an OS is by going back to the era before Linux, and get a definition from the people who created UNIX. 
If you watch this https://techchannel.att.com/showpage/ATT-Archives[AT&T Archives]  video
https://techchannel.att.com/playvideo/2014/01/27/ATT-Archives-The-UNIX-System-Making-Computers-Easier-to-Use["The UNIX System: Making Computers Easier to Use"], you'll see https://en.wikipedia.org/wiki/Victor_A._Vyssotsky[Victor Vyssotsky] define an operating system and https://en.wikipedia.org/wiki/Dennis_Ritchie[Dennis Ritchie] describe the parts of the UNIX OS.
You'll also see an amazing array of 1982 sweaters. 


=== parts of an OS 

In the video, https://en.wikipedia.org/wiki/Dennis_Ritchie[Dennis Ritchie] says 
"the UNIX operating system is basically made up of three parts. 
The kernel, or operating system proper, is the part that manages the control of the machine, and supervises scheduling of the various user programs. 
The shell, which is the name we give to the command interpreter, looks after the communication between the user and the system itself. 
The third part, which is actually the largest, is the various utility programs which perform specific tasks like editing a file or sorting a bunch of numbers or making a plot. 
In other words, all the other programs that are not provided directly as part of the operating system kernel".



=== operating system software versus application software

Operating system is a collective term for software that makes a computer work, and that means different things to different people. 
Is the kernel the only true OS software? 
Does the list of utility programs include the graphical desktop?  
Where does operating system software stop and application software start? 

Vyssotsky says "The programs which tell a computer how to switch a telephone call, or compute a payroll, or play an electronic game are called application software. There's another type of software, the programs which control the resources of the computer itself - the memory of the computer, the processing elements, and the terminals connected to the computer. This latter type of software is called an operating system. Another way of saying what an operating system is, is that it's a collection of programs which make the intricate hardware of the computer seem more simple and comprehensible from the point of view of an applications programmer, so that the applications programmers can create software more easily". 

== read the release files 

Details about the OS release are stored in files in the /etc/ directory. 

[source,shell]
----
[nick@host1 ~]$ ls -l /etc/*release
lrwxrwxrwx. 1 root root 22 Sep 23 10:38 /etc/os-release -> ..//usr/lib/os-release
-rw-r--r--. 1 root root 45 Sep 23 10:38 /etc/redhat-release
lrwxrwxrwx. 1 root root 14 Sep 23 10:38 /etc/system-release -> redhat-release
[nick@host1 ~]$ 
----

The https://www.freedesktop.org/software/systemd/man/os-release.html[os-release file] contains operating system identification data, presented as a list of variables. 

[source,shell]
----
[nick@host1 ~]$ cat /usr/lib/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"
[nick@host1 ~]$ 
----

The redhat-release file is a one-line summary of the OS. 
This file is installed by the redhat-release package, along with many other release files. 

[source,shell]
----
[nick@host1 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.3 (Ootpa)
[nick@host1 ~]$ 
----
