= create an SSH host certificate
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 12-12-2023

== links

https://goteleport.com/blog/comparing-ssh-keys/

rotate host keys 
https://unix.stackexchange.com/questions/334597/how-to-roll-over-ssh-host-keys
https://lwn.net/Articles/637156/


complicated 
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-signing_ssh_certificates

https://www.lorier.net/docs/ssh-ca.html

!!!
SSSD complicates things. 
/var/lib/sss/pubconf/known_hosts

== SSH certificate stuff

Use SSH certificates for host authentication. 
An SSH certificate is not the same as an X.509 certificate used for securing the web. 
They both contain public keys and are both signed by a Certificate Authority, but the SSH certificate is simpler.

* CA RSA keys
* SSH host certificate
* SSH user certificate 
* SSH config

man ssh-keygen
----
CERTIFICATES
     ssh-keygen supports signing of keys to produce certificates that may be
     used for user or host authentication.  Certificates consist of a public
     key, some identity information, zero or more principal (user or host)
     names and a set of options that are signed by a Certification Authority
     (CA) key.  Clients or servers may then trust only the CA key and verify
     its signature on a certificate rather than trusting many user/host keys.
     Note that OpenSSH certificates are a different, and much simpler, format
     to the X.509 certificates used in ssl(8).
----



=== create CA keys

Create an RSA key pair.
These will be used to sign each host's SSH public key certificate.


Use the root account on secret.

[source,shell]
----
nickhardiman@nhardima-mac ~ % ssh nick@secret.source.example.com
Web console: https://secret.source.example.com:9090/ or https://192.168.11.8:9090/

Last login: Wed Jan 10 22:20:41 2024 from 192.168.1.168
[nick@secret ~]$ 
[nick@secret ~]$ sudo -i
[sudo] password for nick: 
[root@secret ~]# 
----

Make a working directory.

[source,shell]
----
[root@secret ~]# mkdir /etc/ssh/certificate
[root@secret ~]# 
----

Create _ca_ and _ca.pub_.

[source,shell]
----
[root@secret ~]# ssh-keygen -t rsa -N '' -f /etc/ssh/certificate/ca
Generating public/private rsa key pair.
Your identification has been saved in /etc/ssh/certificate/ca
Your public key has been saved in /etc/ssh/certificate/ca.pub
The key fingerprint is:
SHA256:GlaFhR7feyqVAELvLqB9tcv3OXAeemrs1oiA8tKeFOI root@secret.source.example.com
The key's randomart image is:
+---[RSA 3072]----+
|     ..  +o      |
|      ..=.       |
|       oo+ .     |
|       o. o .    |
|  . o.o S  . o   |
| ..+.+.= .. * .  |
|  E+o +.oo O +   |
|  ..oo o..O *.   |
|   oo   o=o=o.   |
+----[SHA256]-----+
[root@secret ~]# 
----

Anyone can read the ca.pub public key file. 
Only root can read the ca private key file. 

[source,shell]
----
[root@secret certificate]# ls -la
total 12
drwxr-xr-x. 2 root root   30 Jan 11 18:02 .
drwxr-xr-x. 6 root root 4096 Jan 11 18:02 ..
-rw-------. 1 root root 2622 Jan 11 18:02 ca
-rw-r--r--. 1 root root  584 Jan 11 18:02 ca.pub
[root@secret certificate]# 
----


== get the first public key to sign

Fetch a host public key from 
This is a fiddly process.

SSH does not allow root to log in remotely.
Directory permissions don't allow anyone but root to write to /etc/ssh/certificate/.



== ssh certificate login test

CA on secret.source.example.com

try nick@git.source.example.com --> nick@capsule.source.example.com

