= create an X.509 Certificate Authority
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 30-01-2021

Set up a Certificate Authority. 
Using a CA to sign certificates are one way of creating trust. 
It's not the only way - different processes are set up in different ways. 

* Web sites use server certificates signed by CA companies.
* SSH uses key pairs. Pretty much nobody adds certificates to SSH.
* Different types of certificate have appeared over the years - host certificates, user certificates, wildcard certificates, Extended Validation certificates and so on. 

This process sets up the required files in an ordinary user's home directory. 

== other (and probably better) ways

Other CLI tools for managing a CA and certificates

* https://jamielinux.com/docs/openssl-certificate-authority/
* https://github.com/smallstep/certificates 
* https://www.gnutls.org/manual/html_node/certtool-Invocation.html and certtool, example at https://www.qemu.org/docs/master/system/tls.html
* https://github.com/OpenVPN/easy-rsa

Red Hat's docs

* https://access.redhat.com/solutions/15497[How do I configure a CA and sign certificates using OpenSSL in Red Hat Enterprise Linux?]
* https://access.redhat.com/documentation/en-us/red_hat_certificate_system/9/html/planning_installation_and_deployment_guide/setting_up_a_root_certificate_authority
* https://access.redhat.com/products/red-hat-certificate-system/get-started

== a server certificate 

The process for adding a certificate to a service goes something like this. 

. User collects information about the service to be secured. 
. User creates a key pair - a private key and public key, for asymmetric cryptography. 
Asymmetric cryptography is the set of mathematical algorithms that do the encryption and decryption). 
. User creates a CSR (Certificate Signing Request) containing the public key and a few other values. 
. User sends the CSR to a CA (Certificate Authority).
. CA signs the certificate, with more fancy asymmetric cryptography. 
. CA sends the certificate back to the user.
. User adds the signed certificate to the service. 

== a CA certificate 

The CA uses its own key pair. 
The private key signs all the server certificates. 
The public key is contained in a CA certificate and distributed to all clients. 


== create a CA 

Use your account and home directory. 

There is a pki directory set up for root to use, in /etc/pki/. 

It's a pretty verbose process. 
The commands have many options, and the responses contain a lot of text. 

== make some files 

Make a directory to store the work. 

Add some subdirectories and files. 

* certreqs contains CSRs waiting to be signed 
* crl contains certificate revocation lists (not covered here)
* private contains the private key 
* newcerts contains certificates that have been signed
* index.txt is a list of certificates that have been issued
* cakey.pass is the password need to decrypt the private key
* serial is how many certificates have been issued. Each certificate gets a serial number. 

Connect to guest1.

Write a script to create required files. 

[source,shell]
....
vim certauth.sh
....

Add content. 

[source,shell]
....
mkdir certauth
cd certauth/
mkdir {certreqs,crl,private,newcerts}
chmod 700 private/
touch index.txt
echo 01 > serial
echo 'private key password' > cakey.pass
cp /etc/pki/tls/openssl.cnf .
....

Run and check. 

[source,shell]
....
[nick@guest1 ~]$ ./certauth.sh 
[nick@guest1 ~]$ 
[nick@guest1 ~]$ [nick@guest1 ~]$ cd certauth
[nick@guest1 certauth]$ ls -F
cakey.pass  crl/       newcerts/    private/
certreqs/   index.txt  openssl.cnf  serial
[nick@guest1 certauth]$ 
....

== edit the configuration file

The default configuration file is openssl.cnf.
Openssl looks for this file in the /etc/pki/tls directory. 

[source,shell]
....
[nick@control1 ~]$ openssl version -d
OPENSSLDIR: "/etc/pki/tls"
[nick@control1 ~]$ 
....

This is fine if the root user is doing all the work, but this process uses a regular user.
Create a configuration file by copying the original.
The original config file is almost - but not quite - ready to use. 
This file has hundreds of lines. 
We only need to change one. 

[source,shell]
....
[nick@guest1 certauth]$ vi ./openssl.cnf 
....

Find this _dir_ line.

There are two lines starting with dir. 
This one is in the _[ CA_default ]_ section. 
Don't bother changing the one in the _[ tsa_config1 ]_ section - that's for a Time-Stamp Authority, and we aren't making one of those. 
 
[source,INI]
....
[ CA_default ]

dir             = /etc/pki/CA           # Where everything is kept
....

Change the directory to _this directory_. 

[source,INI]
....
dir             = .           # Where everything is kept
....

That's it. 
There is no service to restart. 

