= create an X.509 server certificate
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 12-12-2023

This procedure creates a new certificate for server capsule.source.example.com. 
Server name is same as host name.
Certificate is signed by a CA on host.build.example.com 

. Create a private key.
. Create a config file to add optional extensions.
. Create a Certificate Signing Request.
. Use the Certificate Authority.
. Sign the CSR and create an X.509 certificate.

New files, in the order they are created

. capsule.source.example.com.key - the server's private key
. openssl.cnf - a config file for adding optional extra certificate extensions
. capsule.source.example.com.csr - the server's certificate signing request
. capsule.source.example.com.cer  - the server's signed certificate


== links

https://github.com/nickhardiman/ansible-collection-platform/blob/main/roles/server_cert/tasks/main.yml

CA certificate and key

https://github.com/nickhardiman/ansible-playbook-build/blob/main/bootstrap.sh


== Red Hat Satellite Capsule and CA

A capsule's certificate must be signed by the same CA that signed the satellite's certificate.

https://access.redhat.com/solutions/4781051


== Red Hat Satellite certificate extensions


Red Hat Satellite is fussy about its optional extras. 
https://access.redhat.com/documentation/en-us/red_hat_satellite/6.14/html-single/installing_satellite_server_in_a_connected_network_environment/index#Configuring_Server_with_a_Custom_SSL_Certificate_satellite

https://access.redhat.com/solutions/4254781
How to check Custom SSL certificate information after Satellite 6.x is installed?

https://access.redhat.com/articles/6433461
Consolidated Troubleshooting Article for Red Hat Satellite 6.x SSL Certificates Issues

a simple cert causes errors
----
Checking Key Usage extension on certificate for Key Encipherment 
[FAIL]

The /etc/pki/tls/certs/satellite.build.example.com.pem does not allow for the 'Key Encipherment' key usage.
----

== make a directory to work in

[source,shell]
....
mkdir ~/pki
cd ~/pki
....


== create a private key

Set the server name 

[source,shell]
....
[nick@capsule.source.example.com pki]$ NAME=capsule.source.example.com
[nick@capsule.source.example.com pki]$ 
....

Create the private key.

[source,shell]
....
[nick@capsule.source.example.com pki]$ openssl genrsa -out $NAME.key 2048
Generating RSA private key, 2048 bit long modulus (2 primes)
................................................+++++
...+++++
e is 65537 (0x010001)
[nick@capsule.source.example.com pki]$ 
....

View the file. 

This file is not encrypted, unlike the myca.key file.  

[source,shell]
....
[nick@capsule.source.example.com pki]$ cat capsule.source.example.com.key 
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAvJ/8MbRtlwwhw0hnYAfdApT1H/ZSbfWWjrwmLvKJzxR2E7HH
NyOsc/PnGxy7Flub+rfWXKnM7nBOt40vXWXetKDX8/lVCE2E3nq6tpK4s6EG+Gc7
t3V0KChvpU5Ar4sJ4EwZ5zqo4W38BbsSlDn2h7lVrw+DlnDp8iSKx0cN3VR+5bQi
...
9nTKgBSMolEAngGPBL1tfIGlak9aBkVy5ABp2rLBHmoAnNWExYjibG2noIZE13bZ
IViohwKBgCc+4d9AaYN5cwwiIzxHKl4EYigACh+PXjhmtwSMxISIzFOCy5hbgmmM
RS81/ON3Gns1SF/UDZgvKHC80T46nPOET+8pIhpIzGKkmaGJYje2Cv0RuUkiqv/L
gA+T7Vv27V0cK06En1TAljEr3g1U/0zBDEV4urTmSI2aVmWRf6Xp
-----END RSA PRIVATE KEY-----
[nick@capsule.source.example.com pki]$ 
....


== create a config file with a request for extensions

[source,shell]
....
vim openssl.cnf
....

Both the distinguished name and the alternative name are set to the server name.

Each field is in the format attribute=value. 


[source,ini]
....
[ req ]
req_extensions = v3_req
distinguished_name = req_distinguished_name
x509_extensions = usr_cert
prompt = no

[ req_distinguished_name ]
CN = capsule.source.example.com

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth, clientAuth, codeSigning, emailProtection
subjectAltName = @alt_names

[ usr_cert ]
basicConstraints=CA:FALSE
nsCertType = client, server, email
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth, codeSigning, emailProtection
nsComment = "OpenSSL Generated Certificate"
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer

[ alt_names ]
DNS.1 = capsule.source.example.com
....

The Distinguished Name can have many more optional attributes, not included here. 
For more information, see ???

[source,shell]
....
[ req_distinguished_name ]
C=
ST=
L=
O=
OU=
CN=
....


== create a Certificate Signing Request

[source,shell]
....
openssl req \
  -new \
  -key ~/pki/capsule.source.example.com.key \
  -config ~/pki/openssl.cnf \
  -out ~/pki/capsule.source.example.com.csr
....

Check extensions.

[source,shell]
----
openssl req -text -in ./capsule.source.example.com.csr | grep -i -A15 extensions
----

[source,shell]
----
[nick@capsule.source.example.com pki]$ openssl req -text -in ./capsule.source.example.com.csr | grep -i -A15 extensions
        Requested Extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment, Data Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication, Code Signing, E-mail Protection
            X509v3 Subject Alternative Name: 
                DNS:capsule.source.example.com
    Signature Algorithm: sha256WithRSAEncryption
         ce:1d:75:51:7f:86:4d:b2:39:e6:95:41:2b:40:8d:0b:ec:46:
         fd:c4:a4:b8:34:21:3f:de:7a:27:d1:10:0a:08:29:30:49:d6:
         69:26:70:1c:84:b9:b7:e0:c9:77:29:30:2c:e8:9b:1f:71:3e:
         b8:96:62:74:73:a6:f8:f4:b4:e7:0c:94:2f:bf:f3:c1:2a:ee:
         67:d4:23:01:ce:4b:1b:ff:92:8c:81:06:43:7e:91:6a:c2:59:
         ac:45:86:92:41:15:5f:c9:78:f1:35:24:8d:bc:df:48:08:ce:
[nick@capsule.source.example.com pki]$ 
----


== sign the CSR 

Certificate Authority files are required. 
These are on a different host. 

* host: host.build.example.com
* CA certificate, including CA public key:   /etc/pki/ca-trust/source/anchors/ca-certificate.pem 
* CA private key:  /etc/pki/tls/private/ca-certificate.key 

Open a terminal on the CA host _host.build.example.com_. 
Use the root account. 

Copy CSR and config to the CA host.

[source,shell]
----
[root@host.build.example.com pki]# scp nick@capsule.source.example.com:~/pki/capsule.source.example.com.csr .
The authenticity of host 'capsule.source.example.com (192.168.11.5)' can't be established.
ED25519 key fingerprint is SHA256:uBiuDoB8KDGdSomQOcEC6w/iKXYbdi6KOmh7E1gB2+M.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'capsule.source.example.com' (ED25519) to the list of known hosts.
(nick@capsule.source.example.com) Password: 
capsule.source.example.com.csr                100% 1094     1.9MB/s   00:00    
[root@host.build.example.com pki]# 
----


Sign the CSR.

Extensions are not copied from CSR to certificate by default. 
Use the _--copy_extensions copyall_ option. 

[source,shell]
....
openssl x509 \
  -req \
  -days 365 \
  -in     ./capsule.source.example.com.csr \
  -CA     /etc/pki/ca-trust/source/anchors/ca-certificate.pem \
  -CAkey  /etc/pki/tls/private/ca-certificate.key \
  -out    ./capsule.source.example.com.cer \
  -set_serial 01 \
  -sha256 \
  -copy_extensions copyall
....

Check the new certificate.

[source,shell]
----
openssl x509 -text -in ./capsule.source.example.com.cer 
# check the extensions only
openssl x509 -text -in ./satellite_cert.pem  | grep -i -A15 extensions
----

[source,shell]
----
[root@host.build.example.com pki]# date
Sun 21 Jan 16:36:22 GMT 2024
[root@host.build.example.com pki]# 
[root@host.build.example.com pki]# openssl x509 -text -in ./capsule.source.example.com.cer 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = UK, ST = mystate, O = myorg, OU = myou, CN = ca.source.example.com
        Validity
            Not Before: Jan 21 16:33:40 2024 GMT
            Not After : Jan 20 16:33:40 2025 GMT
        Subject: CN = capsule.source.example.com
...
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment, Data Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication, Code Signing, E-mail Protection
            X509v3 Subject Alternative Name: 
                DNS:capsule.source.example.com
            X509v3 Subject Key Identifier: 
                60:C2:29:B0:14:6E:89:A8:25:1D:41:CF:13:62:EE:0B:16:74:C5:10
            X509v3 Authority Key Identifier: 
                15:E1:A8:52:32:93:5C:2B:68:45:7B:F0:44:87:35:3B:3A:EE:E9:8A
...
[root@host.build.example.com pki]# 
----

Copy certificate to the requesting host.

[source,shell]
----
[root@host.build.example.com pki]# scp ./capsule.source.example.com.cer  nick@capsule.source.example.com:~/pki/
(nick@capsule.source.example.com) Password: 
capsule.source.example.com.cer                100% 1346     4.6MB/s   00:00    
[root@host.build.example.com pki]# 
----

Copy the CA public key certificate across as well, to complete the certificate chain.

[source,shell]
----
scp \
  /etc/pki/ca-trust/source/anchors/ca-certificate.pem \
  nick@capsule.source.example.com:~/pki/
----

There are now five files on the requesting host. 

[source,shell]
----
[nick@capsule.source.example.com pki]$ ls
ca-certificate.pem              capsule.source.example.com.csr  openssl.cnf
capsule.source.example.com.cer  capsule.source.example.com.key
[nick@capsule.source.example.com pki]$ 
----


== check a Satellite certificate

Check cert, key and CA together.

[source,shell]
----
katello-certs-check  \
  -c ./capsule.source.example.com.cer   \
  -k ./capsule.source.example.com.key   \
  -b ./ca-certificate.pem 
----

[source,shell]
----
[nick@capsule.source.example.com pki]$ katello-certs-check   -c ./capsule.source.example.com.cer   -k ./capsule.source.example.com.key   -b ./ca-certificate.pem 
Checking server certificate encoding: 
[OK]
...
Validation succeeded


To install the Red Hat Satellite server with the custom certificates, run:
...
[nick@capsule.source.example.com pki]$ 
----
