= why a home lab
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 31-12-2020



When you run your own home lab, the entire technology stack is under your control. That’s a good thing, because you’ve got the freedom to tear anything down. And it’s a bad thing, because the responsibility to make it work again rests only on you. Expect both reward and frustration.

If you’re happy with that extra load on your life, you can move on to picking your home lab hardware. 


== places where RHEL can go 

* a physical machine, like a server
* a cloud virtual machine
* a virtual machine on your Mac or Windows box

== a home lab 

A home lab doesn't have to be about computers. A scientist wouldn't fill a lab with PC hardware and networking equipment.

The home lab of an IT enthusiast is: 

* a collection of physical machines. These could be big second-hand servers stripped from data centers, or small mini-PCs based on laptop parts. 
* a collection of network components, like a small unmanaged ethernet switch, a pair of powerline sockets and an SFP transceiver.
* an expensive hobby. 
* in a basement, in a car garage, or in a closet. 
* accessed remotely, using a separate workstation. 
* an electricity bill multiplier, consuming a tiny 100 watts from USB plugs or a monster 100 amps from its own house circuits.
* cooled by silent fins  or cooled by roaring fans. 


== uses

* learn about how to build infrastructure
* experiment with architecture
* troubleshoot architectural issues
* practice upgrades
* test new devices


== resource requirements 

The entry-level computing muscle required to run RHEL 8 and a good selection of applications, from containers to graphical interface, is actually pretty achievable.  

* a CPU with 4 cores 
* 8 GiB memory 
* 100 GiB storage 

You're safe with pretty much any PC built in the last few years. 


== Do you want your own home lab? 

If you want freedom to experiment with the complete technology stack, you need your own hardware - a home lab where you can conduct your experiments. It’s your research environment for learning Internet protocols, swapping hypervisors, and hacking IaC. Install an OS, bond your network interfaces, write your ansible code, store it in gitlab, kick off a Jenkins pipeline, create VMs, and destroy containers. If your research isn’t going as well as you’d hoped, you can rip out layers and start again. 

If you don’t have your own home lab you can’t replace tech layers. If you are working in a shared space, you can’t tear things down without affecting other people’s work. If you work with cloud resources, you have no access to the lower layers of the tech stack. 


=== No! Ugh, sounds like a drag 

If you work in a homogenous environment, the answer to ‘do I need one’ is probably no. If you’re a cloud-native developer who writes web front ends, why do you want to spend precious time and money on lower layers of the technology stack? 

Building a home lab is costly. 
You can spend hundreds on hardware, and hundreds more on electricity bills. 
The less cash you spend, the more compromises you make.

Maintaining a home lab is a hobby. 
If you don't have much free time, don't take it on. 

Maintaining a home lab requires constant learning. 
Dealing with home lab sysadmin is an extra cognitive load that you may have no reason to take on.





=== Why yes, I feel strangely excited

If you work in a heterogeneous environment, the answer is probably yes. If you do IaC (Infrastructure as Code) work both on-premise and off, you may need to try different combinations of hardware, OS and applications to see what works best. This kind of experimentation often requires access to the full tech stack, from network cable to web UI. 

Your employer probably won’t pay for your hardware playground, so it’s your money on the line. A home lab can be built from refurbished computer parts, which keeps the price down. 

Having a home lab isn’t all about work. It can also be your environment for running your side gigs. Game server for your friends? Sure. Home movie streaming for your family? Why not. Chat room for the cause? Right on, brother. 

Pros 

* break services without your teammates yelling at you. 
* learn about new features in your own time. 
* cheaper operating costs than public cloud 
* Full access to the entire tech stack. 
* Standalone. Network down? Doesn’t matter!

Cons 

* Capital expenditure. The up-front cost hurts.
* Sysadmin work required. You install and maintain the system. 
* Not a work environment. This is your playground, not a production system.



== budget choices

What to do when you have limited cash to spend on computer hardware.

You’ve decided to build a home lab. You’re starting from scratch. You don’t have a rack of servers in your garage, and don’t have much cash to buy them. 
Your employer won’t pay for your hardware playground, so it’s your money on the line. 
What do you do?

A home lab can be built from refurbished computer parts, which keeps the price down. And you can start with a single box - you don’t have to go crazy with a rack of machines. 

Here are a couple pointers for getting started with home lab hardware. 

=== New vs. refurbished vs. second-hand

To get your home lab, you are probably going to have to spend some cash on computing resources. Buying new gets you the latest and greatest resources. It’s a safe bet, but the cost limits what you can afford.

The price of second-hand hardware is a fraction of the price of new hardware. OK, a server is big, slow and ugly, but you do get a good cost/performance ratio. Since a home lab doesn’t need the latest and greatest components, buying second-hand is fine. And you can revel in ‘reduce, re-use, recycle’ smugness.

‘Refurbished’ is a subset of ‘second hand’. Second hand hardware may be incomplete, faulty or even dead. Refurbished hardware has been checked by someone who knows what they’re doing, and judged fit for use. A refurbished computer vendor may offer a warranty, answer your awkward questions, and point out your new monitor won’t plug into that old VGA socket. 

Private sellers and refurbished hardware vendors all advertise on eBay. But before you go search, you have to graduate from acronym school. Acronyms like SO-DIMM (Small Outline - Dual Inline Memory Module), SATA (Serial Advanced Technology Attachment) and SSD (Solid State Disk) litter the hardware ads. 


=== $ - old laptop upgrade

Upgrade an old laptop - three figure price tag. I upgraded my old laptop for a total cost of £230 (less than $300 USD). 

The cheapest way I could get my home lab rolling was by blowing the dust off my old  Lenovo Thinkpad W520 laptop and beefing it up. Four new SO-DIMMs (£160) gave me 32GiB memory. A new 2.5” SATA SSD (£70) gave me 500GB storage. The price for buying new components was, strangely, not much more than buying second-hand. 

How old is old? Think London Olympic Games, ‘The Avengers’ movie, and Wikileaks Syria Papers. That old. This laptop is still upgradeable because Lenovo created the W series to be high performance portable workstations.  It had serious hardware for the time, like a quad core processor. Ooh! Aah!

If you add in the original cost of the second hand laptop from eBay (£500), that’s £730 GBP, or $900 USD.

=== $$ - a refurbished server 

Buy a chunky old server - four figure price tag. 

Many companies strip out their old hardware every few years. This old hardware finds its way to  refurbished computer vendors, who store the components then assemble complete systems to order. 

There’s a lot of component detail you can get bogged down in. If you know what you’re looking for, you can pick the spec yourself. If you don’t, the vendors will answer your questions around virtualization extensions, memory speeds and disk drive sizes. 

Old servers and workstations have many sockets for CPUs, memory DIMMS and disk drives. The more sockets you fill, the higher the price. The newer the components, the higher the price. The more powerful the components, the higher the price. - you get the idea. 

=== $$$ - a new server

Buy the latest shiny kit - If you have to ask, you can’t afford it. 

The bottom of the price range for buying new server hardware is surprisingly low. The entry-level pricing on new servers can be $1000. That’s not far off domestic PC prices, so surprisingly cheap for much tougher hardware. Until you realize the specification is so small you can’t see it with your naked eye. 

There is no top of the range. Or perhaps a $70,000 IBM mainframe is the top. With a machine like that, you can help your friends with their banking, aviation and government IT hobbies.






== hardware choices 

A few types of hardware found in home labs, along with some pros and cons.

If you are thinking about setting up a home lab for software experiments, you need hardware. 
If you’re a front-end developer, you can get away with a lightweight laptop. If you want to run up a hundred VMs, you’ll need a stack of servers.  

These hardware types are arranged from smallest to largest. 


=== SBCs and tiny PCs

Tiny is the word. 

An SBC (Single Board Computer) is a tiny complete computer. Chips, interfaces and all other components are soldered onto a circuit board that fits in your hand. SBCs rose from the world of mobile phones and tablets, and so often have ARM processors. 

Intel use laptop parts to create a range of ridiculously tiny PCs called NUC (Next Unit of Computing). The latest models have enough muscle for a home lab, but like all new products, they come with a hefty price tag. Other vendors produce similar models, like the Asrock 4x4, the Zotac Mini-PC, and the Udoo Bolt.  

==== Pros 

* Did I mention tiny? 
* Can be surprisingly powerful.

==== Cons 

* Only the newest and most expensive can handle enterprise applications. 
* Tiny enough to carry, but no battery power means they aren’t really portable.
* SBCs are not upgradeable. Everything is soldered down. 
* Device support can be painful.
* Some OSs don’t support some SBCs. RHEL 8 doesn't run on a Raspberry Pi 4.


=== Lightweight laptop 

The rise of cloud computing fostered the idea that less is more. The front-end developer only needs a hipster laptop, a notebook and a pencil. The back-office developer connects to the corporate network with VPN, and works on a remote desktop. 

==== Pros 

* Plenty of muscle for coding
* Ubiquitous - available in a store near you
* Cheap

==== Cons 

* Too weak for many enterprise applications


=== Beefed up laptop 

You can take an old laptop and give it more grunt by upgrading the storage and memory. Or, if you have the cash, you can buy the latest and greatest mobile workstation. 

==== Pros 

* The only portable option - You’re paying the extra cash for flexibility - wherever you lay your laptop, that’s your office. 

==== Cons 

* Less bang for your buck - Laptop components are expensive. 
* The older the laptop, the less upgradeable it is. A dual core CPU may only hand 16Gib memory.
* Some laptops can’t be upgraded. If memory is in SO-DIMM slots, great. If memory is soldered down, game over. 


=== Domestic PC 

Some - but not all - domestic PCs can be upgraded to handle home lab duty. An office machine and a gaming rig are usually supplied with a few CPU cores and a little memory. If you can make a PC awesome by only upgrading the memory, that’s a bargain. If you have to swap out the power supply, motherboard, CPU and memory, that’s not so great. 

The march of progress means domestic hardware is catching up to server power. The latest and greatest domestic CPUs, like the Intel X-Series and AMD Ryzen Threadripper, have many cores. If you want to pay for cutting-edge CPU, memory and motherboard, you can have a domestic machine that can take on a big old server. But the cost will hurt.

==== Pros 

* Cheap and plentiful
* Can supply server power, for a price
* Many optional extras. Jazz it up with a funky case and pretty LED lighting

==== Cons 

* Not built for heavy use
* You won’t find some server options, like IPMI


=== Workstation 

A workstation is a server that’s been house-trained. It’s a high spec machine aimed at power users, from video editors to scientific data crunchers. 

If you find a monster Dell Precision T7810 with 32 cores, 128GiB of memory, and 2TiB of storage, those are big numbers - can’t it run everything? Possibly. Review your requirements, talk to an expert and check each component. 

==== Pros 

* Server goodness without all the noise
* One big box may meet all your needs

==== Cons 

* You won’t find some server options, like IPMI
* More expensive than a server, and no more portable


=== Server 

Rack-mounted, heavy, noisy - server hardware is not domestic PC hardware. Using a good old vehicle analogy, think truck compared to car. 

You don’t want to work in the same room as a server. HDDs (Hard Disk Drives) in these old machines clunk and whirr. One server may have half a dozen fans. These fans are designed for airflow, not silence - they chop the air and make a racket. 

How old is an HP ProLiant DL740? Is it too old? Talk to your king-of-servers friend with the computer room background (the answer is yes, it’s so old it’s practically steam-powered).

==== Pros 

* true enterprise kit - One tree doesn’t make a forest, but it’s the closest here.
* the best value, in terms of compute resources. They are a great way of getting a lot of hardware grunt for a little money. 
* built to run 24/7.
* If you want to buy more, you can rack up a real enterprise test environment.
* works with server standards and protocols like IPMI, RAID, and Fibre Channel. 

==== Cons 

* learning curve. Get ready to put some work into researching your server’s hardware and software. 
* Noisy
* soaks up the juice - keep an eye on your electricity bill.
* runs hot (hence all the fans). 
* You may need a few. And a managed switch. And a 19” equipment rack to put them in.


=== So which hardware?

There is no one-size-fits-all, because there are so many questions you have to ask yourself. 

* Are you mobile? Perhaps you have the biceps to carry a powerful laptop.
* Do you need 24/7 reliability? If you have a fixed IP address at home, you could permanently connect your home lab to the Internet.
* How quiet does it have to be? Maybe no-one will hear a server in the basement.

There are many ways to start your home lab. And there are many ways to grow your home lab. Just don’t try to collect every type. 


