
= add a KVM volume to the pool 
Nick Hardiman 
:source-highlighter: highlight.js

Start with a basic image, make a few changes.

.storage pool containing two volumes
....
.-------------------------------------.
|                                     |    
|   images                            |    
|                                     |    
|   +-----------------------------+   |    
|   |                             |   |   
|   |  rhel-8.3-x86_64-kvm.qcow2  |   |
|   |                             |   |  
|   +-----------------------------+   |  
|                                     |    
|   +-----------------------------+   |    
|   |                             |   |   
|   |  rhel-8.3-x86_64-dvd.iso    |   |
|   |                             |   |  
|   +-----------------------------+   |  
.-------------------------------------. 
....


Red Hat provide a disk image that's ready to use.  
It's a minimal install, with no graphical desktop. 

This is a qcow2 (QEMU v2) disk image. 
There are many other volume formats, from bochs to vpc. 
The image is split into three parts.

* The first part is tiny and contains the BIOS
* The second part is the /boot partition.
* The third part is another partition. LVM splits this into three volumes - root file system, home directory, and swap space.


== download the RHEL 8 KVM image  

Libvirt does not include any guest images. 
The new storage pool is empty.

[source,shell]
----
[root@host1 libvirt]# virsh vol-list images
 Name   Path
--------------

[root@host1 libvirt]#
----


The https://access.redhat.com/downloads/content/479/ver=/rhel---8/8.2/x86_64/product-software[download page for RHEL 8] lists many installers (including a small ISO and a big DVD) and a ready-made KVM guest image. 
For more information, check out the https://access.redhat.com/solutions/104063[Understanding the various RHEL .iso files] page. 

Download this KVM image and copy to the images directory. 
Authorization tokens are embedded in the URL. The download link is only valid for a few minutes. The link must be put in quotes so the ampersand & does not fool Bash. 

[source,shell]
----
[root@host1 images]# curl --output rhel-8.3-x86_64-kvm.qcow2 --location 'https://access.cdn.redhat.com/content/origin/files/sha256/32/321c20a732419472ba584ea34cd2cab79db2ea1790abe467ea3c0e2ca521a6b7/rhel-8.3-x86_64-kvm.qcow2?user=2cab79db2ea1790abe467ea3c0e2ca52&_auth_=1606150002_8d73cd20ce11b1e007533748ebd743e3'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  3 1255M    3 46.6M    0     0  8711k      0  0:02:27  0:00:05  0:02:22 8860k
...(a couple minutes pass)...
100 1255M  100 1255M    0     0  8666k      0  0:02:28  0:02:28 --:--:-- 8487k
[root@host1 images]# 
[root@host1 images]# file rhel-8.3-x86_64-kvm.qcow2 
rhel-8.3-x86_64-kvm.qcow2: QEMU QCOW Image (v2), 10737418240 bytes
[root@host1 images]# 
----

This image has no root password set. 
It does have cloud-init enabled for public cloud systems. 


