= network
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 13-02-2022


You bring the network. 
This is probaby a home network with at least two boxes attached to it.



== the home network 

Your home already contains a network. 
This probaby has at least three boxes attached to it.

.typical home network  
....
        +----------------------+----------------------+
        |                      |                      | 
.-------+-------.      .-------+-------.      .---------------.
|               |      |               |      |               |
|  workstation  |      |  router       |      | smart devices |
|               |      |               |      |               |
.---------------.      .---------------.      .---------------.
....

* the ISP's router, your gateway to the Internet
* your workstation

The connection is probaby WiFi, not an ethernet cable. 

=== workstation 

The workstation is whatever you work on - it might be a laptop running OS X or a gaming desktop running Windows.

=== router

The box the ISP gave you. 

=== other devices 

* smart devices. There are probably a whole load of smart devices on this home network, from phone to TV. We don't care about those. 
* Network switch. This is probably built into your router. 
* WiFi access point. This is also probably in your router. 
* ethernet cables. 


== add a PC to be the server

You probably have the resources to add a new machine to your home network. 
One PC can be the home lab. 

.home network with server  
....
        +----------------------+----------------------+ WiFi
        |                      |                      |
.-------+-------.      .-------+-------.      .-------+-------.
|               |      |               |      |               |
|  server       |      |  workstation  |      | router        |---------> Internet  
|               |      |               |      |               |  
.---------------.      .---------------.      .---------------.
....



== add a network switch to form the home lab network

Add another network switch to start a seperate home lab network.
A small, cheap, unmanaged ethernet switch is fine. 

Advantages

* the home lab does not have to rely on WiFi.  Servers have network cables hanging out of them, not wifi antennas. 
* the home lab can be extended with more servers
* a seperate home lab network allows experiments with VLANs, IPv6, NAS and other enterprise things. 

.home network with home lab network 
....
        +---------------------------------------------+ Cable
        |                      +----------------------+ WiFi
        |                      |                      |
.-------+-------.      .-------+-------.      .-------+-------.
|  switch       |      |               |      |               |
.-------+-------.      |  workstation  |      | router        |---------> Internet  
        |              |               |      |               |  
.-------+-------.      .---------------.      .---------------.
|               |
|  server       |
|               |
.---------------. 
....

