= a home lab
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 13-02-2022


You bring the network. 
This is probaby a home network with at least two boxes attached to it.

== add a PC to be the server

You probably have the resources to add a new machine to your home network. 
One PC can be the home lab. 

.home network with server  
....
        +----------------------+----------------------+ WiFi
        |                      |                      |
.-------+-------.      .-------+-------.      .-------+-------.
|               |      |               |      |               |
|  server       |      |  workstation  |      | router        |---------> Internet  
|               |      |               |      |               |  
.---------------.      .---------------.      .---------------.
....



== add a network switch to form the home lab network

Add another network switch to start a seperate home lab network.
A small, cheap, unmanaged ethernet switch is fine. 

Advantages

* the home lab does not have to rely on WiFi.  Servers have network cables hanging out of them, not wifi antennas. 
* the home lab can be extended with more servers
* a seperate home lab network allows experiments with VLANs, IPv6, NAS and other enterprise things. 

.home network with home lab network 
....
        +---------------------------------------------+ Cable
        |                      +----------------------+ WiFi
        |                      |                      |
.-------+-------.      .-------+-------.      .-------+-------.
|  switch       |      |               |      |               |
.-------+-------.      |  workstation  |      | router        |---------> Internet  
        |              |               |      |               |  
.-------+-------.      .---------------.      .---------------.
|               |
|  server       |
|               |
.---------------. 
....

