= provide DNS with Bind 9 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 11-01-2021


Use https://www.isc.org/bind/[ISC Bind] to answer DNS queries. 

Install two packages, _bind_ and _bind-utils_. The bind package provides the named service, database and administrator tools like _rndc_ and _named-checkconf_.
The bind_utils package provides more administrator tools like _dig_, _dnssec-keygen_ and _named-checkzone_.


== install bind and bind-utils 

Use the root account. 

Install Bind 9, along with tools we can use to test it. 

[source,shell]
----
[nick@guest1 ~]$ sudo -i
[root@guest1 ~]# 
[root@guest1 ~]# dnf install bind bind-utils
Updating Subscription Management repositories.
Last metadata expiration check: 1:39:20 ago on Wed 13 Jan 2021 09:20:29 GMT.
Dependencies resolved.
================================================================================
 Package        Arch   Version           Repository                        Size
================================================================================
Installing:
 bind           x86_64 32:9.11.20-5.el8  rhel-8-for-x86_64-appstream-rpms 2.1 M
 bind-utils     x86_64 32:9.11.20-5.el8  rhel-8-for-x86_64-appstream-rpms 445 k
Installing dependencies:
 bind-libs      x86_64 32:9.11.20-5.el8  rhel-8-for-x86_64-appstream-rpms 172 k
 bind-libs-lite x86_64 32:9.11.20-5.el8  rhel-8-for-x86_64-appstream-rpms 1.2 M
 bind-license   noarch 32:9.11.20-5.el8  rhel-8-for-x86_64-appstream-rpms 101 k
 python3-bind   noarch 32:9.11.20-5.el8  rhel-8-for-x86_64-appstream-rpms 149 k
 python3-ply    noarch 3.9-8.el8         rhel-8-for-x86_64-baseos-rpms    108 k

Transaction Summary
================================================================================
Install  7 Packages

Total download size: 4.2 M
Installed size: 9.7 M
Is this ok [y/N]: 
----

== start the named service

The DNS service doesn't automatically start. 
Its state is inactive (dead), which sounds a little worrying.
To find out what this means, run `man systemd` and read the CONCEPTS section. 

[source,shell]
----
[root@guest1 ~]# systemctl status named
● named.service - Berkeley Internet Name Domain (DNS)
   Loaded: loaded (/usr/lib/systemd/system/named.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[root@guest1 ~]# 
----

Start the service. 
Bind 9 stays running until the computer is rebooted. 

Enable the service, so it starts when the machine starts. 


[source,shell]
----
[root@guest1 ~]# systemctl enable named
Created symlink /etc/systemd/system/multi-user.target.wants/named.service → /usr/lib/systemd/system/named.service.
[root@guest1 ~]# 
[root@guest1 ~]# systemctl start named
[root@guest1 ~]# 
----

Check.  

[source,shell]
----
[root@guest1 named]# systemctl status named
● named.service - Berkeley Internet Name Domain (DNS)
   Loaded: loaded (/usr/lib/systemd/system/named.service; enabled; vendor prese>
   Active: active (running) since Wed 2020-12-02 16:55:02 GMT; 3h 55min ago
  Process: 6703 ExecStart=/usr/sbin/named -u named -c ${NAMEDCONF} $OPTIONS (co>
  Process: 6700 ExecStartPre=/bin/bash -c if [ ! "$DISABLE_ZONE_CHECKING" == "y>
 Main PID: 6705 (named)
    Tasks: 5 (limit: 23328)
   Memory: 59.5M
   CGroup: /system.slice/named.service
           └─6705 /usr/sbin/named -u named -c /etc/named.conf

Dec 02 16:55:02 guest1.lab.example.com named[6705]: zone 0.in-addr.arpa/IN: loaded >
Dec 02 16:55:02 guest1.lab.example.com named[6705]: zone 1.0.0.127.in-addr.arpa/IN:>
Dec 02 16:55:02 guest1.lab.example.com named[6705]: zone localhost/IN: loaded seria>
Dec 02 16:55:02 guest1.lab.example.com named[6705]: zone 1.0.0.0.0.0.0.0.0.0.0.0.0.>
Dec 02 16:55:02 guest1.lab.example.com named[6705]: zone localhost.localdomain/IN: >
Dec 02 16:55:02 guest1.lab.example.com named[6705]: all zones loaded
Dec 02 16:55:02 guest1.lab.example.com named[6705]: running
Dec 02 16:55:02 guest1.lab.example.com systemd[1]: Started Berkeley Internet Name D>
Dec 02 16:55:02 guest1.lab.example.com named[6705]: managed-keys-zone: Key 20326 fo>
Dec 02 16:55:02 guest1.lab.example.com named[6705]: resolver priming query complete
[root@guest1 named]# 
----

This text is displayed by a pager, which truncates long lines to fit the screen. 
Use arrow keys to scroll to the right and see the rest of the lines. 
To see all of these long lines without the pager, run the same command with more options, like this: `systemctl --no-pager --full status named`.



== Check fowarding 

Name resolution is set to check two DNS servers - one on the home network, and one on the private network. 

[source,shell]
----
[root@guest1 ~]# cat /etc/resolv.conf 
# Generated by NetworkManager
search home lab.example.com
nameserver 192.168.1.254
nameserver 192.168.152.1
[root@guest1 ~]# 
----

NetworkManager received these details from DHCP services when it was bringing up the interfaces, when the OS booted up. 
It copied the details to the /etc/resolv.conf file. 

We don't want these settings. 
We want to use our new local DNS server.

The local name server also uses these nameserver settings.

[source,shell]
----
[root@guest1 ~]# host www.google.com localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

www.google.com has address 216.58.212.196
www.google.com has IPv6 address 2a00:1450:4009:80a::2004
[root@guest1 ~]# 
----


