= libvirt's private0 and dnsmasq 
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 11-01-2021

The _private0_ DHCP setup isn't great if you want to SSH to your new VM, because it takes some work to figure out what IPv4 address to use.  
When the guest VM boots up, it is given the address 192.168.152...er...something. 
The dnsmasq DHCP service assigns addresses from an IP pool, so the VM gets a random address from the range 192.168.152.0/24. 

Instead of searching for the address after every boot, it's easier to assign a fixed IP address. 
All we need to get started is the MAC address, and that was fixed by the _virt-install_ command when the VM was created (``52:54:00:00:00:03``). 

People remember names better than numbers. A fixed IP address is easier to use than a random IP address, and a DNS name is easier still.  


== libvirt's networks 

[source,shell]
....
[nick@host1 ~]$ sudo virsh net-list --all
 Name      State      Autostart   Persistent
----------------------------------------------
 default   active     yes         yes
 private0  active     yes         yes
 public0   active     yes         yes

[nick@host1 ~]$ 
....


== view libvirt's XML config file 

Libvirt creates a dnsmasq config file automatically. 
Libvirt uses settings stored in its own config file. 

There's a lot going on. 

[source,shell]
....
[nick@host1 ~]$ sudo virsh net-dumpxml private0
[sudo] password for nick: 
<network>
  <name>private0</name>
  <uuid>d9c5b855-4cbc-4a98-9779-93f075212a6e</uuid>
  <bridge name='privbr0' stp='on' delay='0'/>
  <mac address='52:54:00:00:01:01'/>
  <ip address='192.168.152.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.152.2' end='192.168.152.254'/>
    </dhcp>
  </ip>
  <ip family='ipv6' address='2001:db8:ca2:3::1' prefix='64'>
  </ip>
</network>

[nick@host1 ~]$ 
....


== view qemu's XML config file 

Libvirt's network config gets stored in a file for qemu to use. 

[source,shell]
....
[nick@host1 ~]$ sudo cat /etc/libvirt/qemu/networks/private0.xml
<!--
WARNING: THIS IS AN AUTO-GENERATED FILE. CHANGES TO IT ARE LIKELY TO BE
OVERWRITTEN AND LOST. Changes to this xml configuration should be made using:
  virsh net-edit private0
or other application using the libvirt API.
-->

<network>
  <name>private0</name>
  <uuid>d9c5b855-4cbc-4a98-9779-93f075212a6e</uuid>
...
....


== view the dnsmasq config file

[nick@host1 ~]$ sudo cat /var/lib/libvirt/dnsmasq/private0.conf
##WARNING:  THIS IS AN AUTO-GENERATED FILE. CHANGES TO IT ARE LIKELY TO BE
##OVERWRITTEN AND LOST.  Changes to this configuration should be made using:
##    virsh net-edit private0
## or other application using the libvirt API.
##
## dnsmasq conf file created by libvirt
strict-order
pid-file=/run/libvirt/network/private0.pid
except-interface=lo
bind-dynamic
interface=privbr0
dhcp-option=3
no-resolv
ra-param=*,0,0
dhcp-range=192.168.152.2,192.168.152.254,255.255.255.0
dhcp-no-override
dhcp-authoritative
dhcp-lease-max=253
dhcp-hostsfile=/var/lib/libvirt/dnsmasq/private0.hostsfile
addn-hosts=/var/lib/libvirt/dnsmasq/private0.addnhosts
dhcp-range=2001:db8:ca2:3::1,ra-only
[nick@host1 ~]$ 


== check the IP pool 

View the dnsmasq configuration. 
Its config files are in the folder /var/lib/libvirt/dnsmasq/. 

This ``dhcp-range`` line tells dnsmasq what IP pool to manage for the _private0_ network. 

[source,shell]
....
[nick@host1 ~]$ sudo grep dhcp-range /var/lib/libvirt/dnsmasq/private0.conf
[sudo] password for nick: 
dhcp-range=192.168.152.2,192.168.152.254,255.255.255.0
dhcp-range=2001:db8:ca2:3::1,ra-only
[nick@host1 ~]$ 
....

View the libvirt configuration. 
libvirt writes that dnsmasq configuration after reading its own network configuration.
You can see libvirt's configuration  using the ``virsh net-dumpxml`` command.
There are about 20 lines of XML that define the network.
These are all listed further down. 

The IP pool config is between a pair of dhcp tags.  

[source,shell]
....
[nick@host1 ~]$ sudo virsh net-dumpxml private0
...
    <dhcp>
      <range start='192.168.152.2' end='192.168.152.254'/>
    </dhcp>
...
[nick@host1 ~]$ 
....

